jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/config/redis",()=>({getRedisPrefix:()=>"synthetic",getRedisClient:jest.fn(),withRedisTimeout:(_label:any,fn:any)=>fn()}));
jest.mock("../../src/modules/analytics-core/config/analyticsConfig",()=>({analyticsConfig:{logLevel:"debug",outbox:{batchSize:10,idleMs:1000,lockTtlSec:30,consumerId:"synthetic",leaderLockEnabled:false,enabled:true}}}));
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents",()=>({appendCargoPilotDomainEvent:jest.fn()}));
import {analyticsLogger} from "../../src/modules/analytics-core/config/analyticsLogger";
import {processAnalyticsOutboxBatchOnce} from "../../src/modules/analytics-core/infrastructure/analyticsOutboxPublisher";
import {analyticsAcceptanceHash} from "../../src/modules/analytics-core/infrastructure/analyticsOutbox";
import {appendCargoPilotDomainEvent} from "../../src/modules/analytics-core/realtime/analyticsEvents";
import {database as db} from "./fixtures";
const privateMarker="synthetic-private-endpoint-password-sql-value";
let error:jest.SpyInstance,warn:jest.SpyInstance,info:jest.SpyInstance;
beforeEach(()=>{jest.clearAllMocks();error=jest.spyOn(console,"error").mockImplementation(()=>undefined);warn=jest.spyOn(console,"warn").mockImplementation(()=>undefined);info=jest.spyOn(console,"log").mockImplementation(()=>undefined);});
afterEach(()=>{error.mockRestore();warn.mockRestore();info.mockRestore();jest.useRealTimers();});
it.each([new Error(privateMarker),{message:privateMarker,name:privateMarker},privateMarker])("analytics error diagnostics contain neither arbitrary exception text nor names (%#)",input=>{analyticsLogger.error("Worker operation failed",input);const line=error.mock.calls[0][0];expect(line).not.toContain(privateMarker);expect(JSON.parse(line).error).toEqual({code:"ANALYTICS_OPERATION_FAILED"});});
it("throttled diagnostics preserve safe operation label and suppression count",()=>{analyticsLogger.throttledWarn("synthetic-throttle","Worker lookup failed",{error:new Error(privateMarker),meta:{operation:"lookup"},throttleMs:60000});analyticsLogger.throttledWarn("synthetic-throttle","Worker lookup failed",{error:privateMarker,throttleMs:60000});expect(warn).toHaveBeenCalledTimes(1);expect(JSON.parse(warn.mock.calls[0][0])).toMatchObject({message:"Worker lookup failed",meta:{operation:"lookup",suppressed:0},error:{code:"ANALYTICS_OPERATION_FAILED"}});expect(JSON.stringify(warn.mock.calls)).not.toContain(privateMarker);});
it("publisher persists only bounded reconciliation code after an uncertain failure",async()=>{
 const orderId="00000000-0000-4000-8000-000000000001",tenantId="00000000-0000-4000-8000-000000000002",companyId="00000000-0000-4000-8000-000000000003";
 const row:any={id:orderId,eventId:"synthetic-event",type:"order_status_changed",tenantScope:`tenant:${tenantId}:company:${companyId}`,entityId:orderId,orderId,ticketId:null,tenantId,companyId,capability:"order_event",acceptedAt:new Date(),occurredAt:new Date(),schemaVersion:1,payload:{}};row.contentHash=analyticsAcceptanceHash(row);
 db.$transaction.mockImplementation((fn:any)=>fn(db));db.$executeRaw.mockResolvedValue(1);db.$executeRawUnsafe.mockResolvedValue(0);db.$queryRaw.mockResolvedValue([{id:orderId,claimToken:orderId}]);(db as any).analyticsDomainEventOutbox.findUniqueOrThrow.mockResolvedValue(row);db.order.findUnique.mockResolvedValue({tenantId,ownerOrgId:companyId,assignedOrgId:null});db.organization.findFirst.mockResolvedValue({id:companyId});(appendCargoPilotDomainEvent as jest.Mock).mockRejectedValue(new Error(privateMarker));
 expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({published:0,contained:1});expect(appendCargoPilotDomainEvent).toHaveBeenCalledTimes(1);const sql=db.$executeRaw.mock.calls.map((args:any[])=>String(args[0])).join("\n");expect(sql).toContain("ANALYTICS_DISPATCH_UNCERTAIN");expect(sql).not.toContain(privateMarker);
});
