jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:new Proxy({}, {get:(_t,k)=>{const v=(mockPrisma as any)[k];return typeof v==="function"?v.bind(mockPrisma):v;}})}));
jest.mock("../../src/config/redis",()=>({withRedisTimeout:(_label:any,fn:any)=>fn(),getRedisPrefix:()=>"synthetic"}));
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents",()=>({buildCargoPilotDomainEvent:(input:any)=>({id:input.id||require("crypto").randomUUID(),type:input.type,tenantScope:input.tenantScope,entityId:input.entityId??null,occurredAt:input.occurredAt||new Date().toISOString(),schemaVersion:1,payload:input.payload}),appendCargoPilotDomainEvent:jest.fn(async()=>undefined)}));
import {Pool} from "pg";import {PrismaClient} from "@prisma/client";import {PrismaPg} from "@prisma/adapter-pg";import {randomUUID} from "crypto";
import {createTenantDemoFixture,TENANT_DEMO_IDS as ids} from "../../src/modules/tenancy/demo-fixtures";import {persistTenantDemoFixture} from "../tenancy/postgres-fixture.persistence";
import {enqueueCargoPilotDomainEventsTx} from "../../src/modules/analytics-core/infrastructure/analyticsOutbox";
import {claimAnalyticsOutboxBatch,prepareAnalyticsDispatch,completeAnalyticsDispatch,processAnalyticsOutboxBatchOnce} from "../../src/modules/analytics-core/infrastructure/analyticsOutboxPublisher";
import {appendCargoPilotDomainEvent} from "../../src/modules/analytics-core/realtime/analyticsEvents";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable analytics identity required");const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing database");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});let mockPrisma:PrismaClient;let ticketId:string;
const owner={tenantId:ids.tenants.transAsia,companyId:ids.organizations.transAsiaUz};
const input=(orderId:string=ids.orders.transAsiaUz)=>({type:"order_status_changed" as const,entityId:orderId,tenantScope:`tenant:${owner.tenantId}:company:${owner.companyId}`,payload:{source:"synthetic",password:"synthetic-private-value"}});
async function enqueue(data:any=input()){const event=(await mockPrisma.$transaction(tx=>enqueueCargoPilotDomainEventsTx(tx,[data])))[0];return mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{eventId:event.id}});}
const business=async()=>({orders:await mockPrisma.order.findMany({orderBy:{id:"asc"}}),tickets:await mockPrisma.supportTicket.findMany({orderBy:{id:"asc"}}),tracking:await mockPrisma.tracking.count(),journals:await mockPrisma.financeJournalEntry.count()});
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Ownership mismatch");const c=await pool.connect();try{await c.query("BEGIN");await persistTenantDemoFixture(c,createTenantDemoFixture());await c.query("COMMIT");}finally{c.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});ticketId=randomUUID();await mockPrisma.supportTicket.create({data:{id:ticketId,ticketNumber:"synthetic-"+runId,title:"Synthetic",tenantId:owner.tenantId,ownerOrgId:owner.companyId}});});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});
beforeEach(async()=>{jest.clearAllMocks();(appendCargoPilotDomainEvent as jest.Mock).mockResolvedValue(undefined);await mockPrisma.analyticsDomainEventOutbox.updateMany({where:{acceptedAt:{not:null},publishedAt:null},data:{publicationState:"quarantined",claimToken:null,claimedAt:null,leaseExpiresAt:null}});await mockPrisma.tenant.update({where:{id:owner.tenantId},data:{status:"active"}});await mockPrisma.organization.update({where:{id:owner.companyId},data:{isActive:true}});});
it("accepted order publication reloads owner and projects only safe reference envelope",async()=>{const before=await business(),row=await enqueue();expect(row).toMatchObject({...owner,orderId:ids.orders.transAsiaUz,ticketId:null,capability:"order_event",publicationState:"ready"});expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({claimed:1,published:1});expect(appendCargoPilotDomainEvent).toHaveBeenCalledWith(expect.objectContaining({id:row.eventId,tenantScope:`tenant:${owner.tenantId}:company:${owner.companyId}`,payload:{}}));expect(JSON.stringify((appendCargoPilotDomainEvent as jest.Mock).mock.calls)).not.toContain("synthetic-private-value");expect(await business()).toEqual(before);});
it("ticket and explicit company configuration subjects preserve distinct typed ownership",async()=>{await enqueue({type:"support_ticket_changed",entityId:ticketId,tenantScope:input().tenantScope,payload:{reason:"ticket_updated"}});await enqueue({type:"support_ticket_changed",entityId:null,companySubjectId:owner.companyId,tenantScope:input().tenantScope,payload:{reason:"configuration_changed"}});const claims=await claimAnalyticsOutboxBatch(10);expect(claims).toHaveLength(2);for(const claim of claims)expect(await prepareAnalyticsDispatch(claim)).toMatchObject({type:"support_ticket_changed",tenantScope:input().tenantScope});});
it.each(["foreign-tenant","foreign-company","unbound-ticket","global","null-order","unsupported"])("source %s rejects without outbox/business effects",async kind=>{let data:any=input();if(kind==="foreign-tenant")data=input(ids.orders.unrelated);if(kind==="foreign-company")data=input(ids.orders.transAsiaDe);if(kind==="unbound-ticket")data={...data,type:"support_ticket_changed",entityId:null};if(kind==="global")data.tenantScope="global";if(kind==="null-order")data.entityId=null;if(kind==="unsupported")data.type="driver_location_upsert";const before=await business(),count=await mockPrisma.analyticsDomainEventOutbox.count();await expect(enqueue(data)).rejects.toMatchObject({statusCode:409});expect(await mockPrisma.analyticsDomainEventOutbox.count()).toBe(count);expect(await business()).toEqual(before);expect(appendCargoPilotDomainEvent).not.toHaveBeenCalled();});
it("source transaction failure rolls back acceptance and its business mutation",async()=>{const before=await business(),count=await mockPrisma.analyticsDomainEventOutbox.count();await expect(mockPrisma.$transaction(async tx=>{await tx.order.update({where:{id:ids.orders.transAsiaUz},data:{pickupAddress:"synthetic rollback"}});await enqueueCargoPilotDomainEventsTx(tx,[input()]);throw Error("synthetic failure");})).rejects.toThrow("synthetic failure");expect(await business()).toEqual(before);expect(await mockPrisma.analyticsDomainEventOutbox.count()).toBe(count);});
it("three competing workers claim one row once",async()=>{const row=await enqueue();const batches=await Promise.all([claimAnalyticsOutboxBatch(),claimAnalyticsOutboxBatch(),claimAnalyticsOutboxBatch()]);expect(batches.flat()).toHaveLength(1);expect(batches.flat()[0].id).toBe(row.id);expect((await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}})).attempts).toBe(1);});
it("expired pre-dispatch lease is reclaimable and old token cannot dispatch or confirm",async()=>{const row=await enqueue(),[old]=await claimAnalyticsOutboxBatch();await mockPrisma.analyticsDomainEventOutbox.update({where:{id:row.id},data:{leaseExpiresAt:new Date(0)}});const [fresh]=await claimAnalyticsOutboxBatch();expect(fresh.claimToken).not.toBe(old.claimToken);expect(await prepareAnalyticsDispatch(old)).toBeNull();expect(await completeAnalyticsDispatch(old)).toBe(false);expect(await prepareAnalyticsDispatch(fresh)).not.toBeNull();expect(await completeAnalyticsDispatch(fresh)).toBe(true);expect(appendCargoPilotDomainEvent).not.toHaveBeenCalled();});
it("expired dispatched lease remains reconciliation required and is never reclaimed",async()=>{const row=await enqueue(),[claim]=await claimAnalyticsOutboxBatch();expect(await prepareAnalyticsDispatch(claim)).not.toBeNull();await mockPrisma.analyticsDomainEventOutbox.update({where:{id:row.id},data:{leaseExpiresAt:new Date(0)}});expect(await claimAnalyticsOutboxBatch()).toEqual([]);expect(await completeAnalyticsDispatch(claim)).toBe(false);expect(await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}})).toMatchObject({publicationState:"reconciliation_required",publishedAt:null});});
it.each(["tenant","company"])("disabled current %s quarantines accepted work before transport",async kind=>{const row=await enqueue(),before=await business();if(kind==="tenant")await mockPrisma.tenant.update({where:{id:owner.tenantId},data:{status:"suspended"}});else await mockPrisma.organization.update({where:{id:owner.companyId},data:{isActive:false}});expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({claimed:1,published:0,contained:1});expect(appendCargoPilotDomainEvent).not.toHaveBeenCalled();expect(await business()).toEqual(before);expect((await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}})).publicationState).toBe("quarantined");});
it("unaccepted legacy row is not claimed or falsely acknowledged",async()=>{const row=await mockPrisma.analyticsDomainEventOutbox.create({data:{eventId:randomUUID(),type:"order_status_changed",entityId:ids.orders.transAsiaUz,tenantScope:"global",payload:{},occurredAt:new Date()}});expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({claimed:0,published:0});expect((await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}})).publishedAt).toBeNull();expect(appendCargoPilotDomainEvent).not.toHaveBeenCalled();});
it("uncertain append leaves durable reconciliation state and no retry",async()=>{const row=await enqueue();(appendCargoPilotDomainEvent as jest.Mock).mockRejectedValue(Error("synthetic private transport failure"));expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({published:0,contained:1});expect((await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}}))).toMatchObject({publicationState:"reconciliation_required",publishedAt:null,lastError:"ANALYTICS_DISPATCH_UNCERTAIN"});await processAnalyticsOutboxBatchOnce();expect(appendCargoPilotDomainEvent).toHaveBeenCalledTimes(1);});
it("accepted identity and payload updates cannot retarget work",async()=>{const row=await enqueue(),before=await business();for(const data of [{orderId:ids.orders.unrelated},{companyId:ids.organizations.transAsiaDe},{payload:{forged:true}},{contentHash:"0".repeat(64)}])await expect(mockPrisma.analyticsDomainEventOutbox.update({where:{id:row.id},data})).rejects.toThrow("Analytics acceptance is immutable");expect(await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}})).toEqual(row);expect(await business()).toEqual(before);});
it("partial accepted and foreign compound references are rejected on inserts",async()=>{const row=await enqueue(),{id,...data}=row;for(const patch of [{tenantId:null},{companyId:null},{orderId:ids.orders.unrelated},{companyId:ids.organizations.transAsiaDe},{contentHash:null},{capability:"cash_event",type:"cash_handoff",entityId:null},{capability:"cash_finance_source",type:"finance_source_event",entityId:null}])await expect(mockPrisma.analyticsDomainEventOutbox.create({data:{...data,eventId:randomUUID(),...patch} as any})).rejects.toThrow();expect(await mockPrisma.analyticsDomainEventOutbox.count({where:{acceptedAt:{not:null},publicationState:"ready"}})).toBe(1);});
it("failed dispatch marker rolls back and safe retry backs off without transport",async()=>{const row=await enqueue(),before=await business();await pool.query(`CREATE FUNCTION cp_analytics_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."publicationState"='dispatching' THEN RAISE EXCEPTION 'synthetic marker failure'; END IF; RETURN NEW; END $$;CREATE TRIGGER cp_analytics_fail BEFORE UPDATE ON "AnalyticsDomainEventOutbox" FOR EACH ROW EXECUTE FUNCTION cp_analytics_fail();`);try{await processAnalyticsOutboxBatchOnce();const current=await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}});expect(current).toMatchObject({publicationState:"ready",dispatchStartedAt:null,publishedAt:null,attempts:1});expect(current.nextAttemptAt.getTime()).toBeGreaterThan(row.nextAttemptAt.getTime());expect(appendCargoPilotDomainEvent).not.toHaveBeenCalled();expect(await business()).toEqual(before);}finally{await pool.query('DROP TRIGGER cp_analytics_fail ON "AnalyticsDomainEventOutbox";DROP FUNCTION cp_analytics_fail();');}await mockPrisma.analyticsDomainEventOutbox.update({where:{id:row.id},data:{nextAttemptAt:new Date(0)}});expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({published:1});});
it("transport success then database confirmation failure does not replay",async()=>{const row=await enqueue();await pool.query(`CREATE FUNCTION cp_analytics_confirm_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."publicationState"='published' THEN RAISE EXCEPTION 'synthetic confirmation failure'; END IF; RETURN NEW; END $$;CREATE TRIGGER cp_analytics_confirm_fail BEFORE UPDATE ON "AnalyticsDomainEventOutbox" FOR EACH ROW EXECUTE FUNCTION cp_analytics_confirm_fail();`);try{await processAnalyticsOutboxBatchOnce();expect((await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}})).publicationState).toBe("reconciliation_required");expect(appendCargoPilotDomainEvent).toHaveBeenCalledTimes(1);await processAnalyticsOutboxBatchOnce();expect(appendCargoPilotDomainEvent).toHaveBeenCalledTimes(1);}finally{await pool.query('DROP TRIGGER cp_analytics_confirm_fail ON "AnalyticsDomainEventOutbox";DROP FUNCTION cp_analytics_confirm_fail();');}});
it("last expired pre-dispatch attempt becomes exhausted without publication",async()=>{const row=await enqueue();await mockPrisma.analyticsDomainEventOutbox.update({where:{id:row.id},data:{attempts:7}});const [claim]=await claimAnalyticsOutboxBatch();await mockPrisma.analyticsDomainEventOutbox.update({where:{id:row.id},data:{leaseExpiresAt:new Date(0)}});expect(await claimAnalyticsOutboxBatch()).toEqual([]);expect(await prepareAnalyticsDispatch(claim)).toBeNull();expect((await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}})).publicationState).toBe("exhausted");});

it("new outbox compound target prevents an otherwise unrelated parent owner retarget",async()=>{const parent=await mockPrisma.order.findUniqueOrThrow({where:{id:ids.orders.transAsiaUz}}),cloneId=randomUUID();await mockPrisma.order.create({data:{...parent,id:cloneId,orderNumber:"synthetic-owned-"+cloneId} as any});const row=await enqueue(input(cloneId)),before=await business();await expect(mockPrisma.order.update({where:{id:cloneId},data:{ownerOrgId:ids.organizations.transAsiaDe}})).rejects.toMatchObject({code:"P2003"});expect(await business()).toEqual(before);const catalog=await pool.query('SELECT conname,convalidated FROM pg_constraint WHERE conname LIKE $1',["AnalyticsOutbox_%"]);expect(catalog.rows.filter(r=>r.conname.endsWith("fkey"))).toHaveLength(4);expect(catalog.rows.every(r=>r.convalidated===false)).toBe(true);expect((await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:row.id}})).companyId).toBe(owner.companyId);});
it("competing batch claims partition multiple records without repeated identities",async()=>{for(let n=0;n<4;n++)await enqueue();const batches=await Promise.all([claimAnalyticsOutboxBatch(2),claimAnalyticsOutboxBatch(2),claimAnalyticsOutboxBatch(2)]),rows=batches.flat();expect(rows).toHaveLength(4);expect(new Set(rows.map(r=>r.id)).size).toBe(4);expect(await mockPrisma.analyticsDomainEventOutbox.count({where:{publicationState:"claimed",attempts:1}})).toBe(4);});

it("oversized durable payload is quarantined before hashing or transport",async()=>{const row=await enqueue(),{id,...data}=row;await mockPrisma.analyticsDomainEventOutbox.update({where:{id},data:{publicationState:"quarantined"}});const oversized=await mockPrisma.analyticsDomainEventOutbox.create({data:{...data,eventId:randomUUID(),payload:{oversized:"x".repeat(65537)},publicationState:"ready"} as any});const before=await business();expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({claimed:1,published:0,contained:1});expect(appendCargoPilotDomainEvent).not.toHaveBeenCalled();expect((await mockPrisma.analyticsDomainEventOutbox.findUniqueOrThrow({where:{id:oversized.id}})).publicationState).toBe("quarantined");expect(await business()).toEqual(before);});
