jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/config/redis",()=>({getRedisPrefix:()=>"synthetic",withRedisTimeout:jest.fn((_label:any,fn:any)=>fn())}));
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents",()=>({buildCargoPilotDomainEvent:jest.fn((input:any)=>({id:input.id||"synthetic-event",occurredAt:input.occurredAt||new Date().toISOString(),schemaVersion:1,...input})),appendCargoPilotDomainEvent:jest.fn()}));
import * as redis from "../../src/config/redis";
import {database as db} from "./fixtures";import {enqueueCargoPilotDomainEventsTx,analyticsAcceptanceHash} from "../../src/modules/analytics-core/infrastructure/analyticsOutbox";
import {processAnalyticsOutboxBatchOnce} from "../../src/modules/analytics-core/infrastructure/analyticsOutboxPublisher";
import {buildCargoPilotDomainEvent,appendCargoPilotDomainEvent} from "../../src/modules/analytics-core/realtime/analyticsEvents";
const id=(n:number)=>`00000000-0000-4000-8000-${n.toString().padStart(12,"0")}`;
const input={type:"order_status_changed" as const,entityId:id(1),tenantScope:`tenant:${id(2)}:company:${id(3)}`,payload:{source:"synthetic"}};
beforeEach(()=>{jest.clearAllMocks();db.$transaction.mockImplementation((fn:any)=>fn(db));db.$executeRaw.mockResolvedValue(1);db.$executeRawUnsafe.mockResolvedValue(0);db.$queryRaw.mockResolvedValue([]);db.order.findUnique.mockResolvedValue({tenantId:id(2),ownerOrgId:id(3),assignedOrgId:null});db.organization.findFirst.mockResolvedValue({id:id(3)});(db as any).analyticsDomainEventOutbox.createMany.mockResolvedValue({count:1});});
it("writer derives typed authority from the order and inserts one complete receipt",async()=>{await enqueueCargoPilotDomainEventsTx(db as any,[input]);const rows=(db as any).analyticsDomainEventOutbox.createMany.mock.calls[0][0].data;expect(rows).toHaveLength(1);expect(rows[0]).toMatchObject({tenantId:id(2),companyId:id(3),orderId:id(1),ticketId:null,capability:"order_event",publicationState:"ready"});expect(rows[0].contentHash).toBe(analyticsAcceptanceHash(rows[0]));});
it("same-tenant assigned company consistency reference does not choose event owner",async()=>{db.order.findUnique.mockResolvedValue({tenantId:id(2),ownerOrgId:id(3),assignedOrgId:id(4)});await enqueueCargoPilotDomainEventsTx(db as any,[{...input,tenantScope:`tenant:${id(2)}:company:${id(4)}`}]);expect((db as any).analyticsDomainEventOutbox.createMany.mock.calls[0][0].data[0].companyId).toBe(id(3));});
it.each(["foreign-claim","null-owner","missing-order","inactive-company","unsupported","oversized","incomplete-ticket"])("%s cannot produce accepted work",async kind=>{let data:any=input;if(kind==="foreign-claim")data={...input,tenantScope:`tenant:${id(8)}:company:${id(9)}`};if(kind==="null-owner")db.order.findUnique.mockResolvedValue({tenantId:null,ownerOrgId:id(3)});if(kind==="missing-order")db.order.findUnique.mockResolvedValue(null);if(kind==="inactive-company")db.organization.findFirst.mockResolvedValue(null);if(kind==="unsupported")data={...input,type:"driver_presence_update"};if(kind==="oversized")data={...input,payload:{unsafe:"x".repeat(65537)}};if(kind==="incomplete-ticket")data={...input,type:"support_ticket_changed",entityId:null};await expect(enqueueCargoPilotDomainEventsTx(db as any,[data])).rejects.toMatchObject({statusCode:409});expect((db as any).analyticsDomainEventOutbox.createMany).not.toHaveBeenCalled();expect(buildCargoPilotDomainEvent).not.toHaveBeenCalled();expect(appendCargoPilotDomainEvent).not.toHaveBeenCalled();});
it("invalid later member writes no partial accepted batch",async()=>{await expect(enqueueCargoPilotDomainEventsTx(db as any,[input,{...input,entityId:null}])).rejects.toMatchObject({statusCode:409});expect((db as any).analyticsDomainEventOutbox.createMany).not.toHaveBeenCalled();});
it("unsettled transport retains process admission until actual settlement",async()=>{const row:any={id:id(1),eventId:"synthetic-event",type:input.type,entityId:id(1),tenantId:id(2),companyId:id(3),orderId:id(1),ticketId:null,capability:"order_event",tenantScope:input.tenantScope,occurredAt:new Date(),acceptedAt:new Date(),schemaVersion:1,payload:input.payload};row.contentHash=analyticsAcceptanceHash(row);(db as any).analyticsDomainEventOutbox.findUniqueOrThrow.mockResolvedValue(row);db.$queryRaw.mockResolvedValue([{id:id(1),claimToken:id(5)}]);let release!:()=>void;(appendCargoPilotDomainEvent as jest.Mock).mockImplementation(()=>new Promise<void>(resolve=>release=resolve));const pending=processAnalyticsOutboxBatchOnce();for(let n=0;n<30&&!release;n++)await Promise.resolve();expect(release).toBeDefined();expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({busy:true,claimed:0});expect(appendCargoPilotDomainEvent).toHaveBeenCalledTimes(1);release();await pending;});

it("append timeout cannot release admission while underlying work remains pending",async()=>{
 const row:any={id:id(1),eventId:"synthetic-timeout",type:input.type,entityId:id(1),tenantId:id(2),companyId:id(3),orderId:id(1),ticketId:null,capability:"order_event",tenantScope:input.tenantScope,occurredAt:new Date(),acceptedAt:new Date(),schemaVersion:1,payload:input.payload};row.contentHash=analyticsAcceptanceHash(row);(db as any).analyticsDomainEventOutbox.findUniqueOrThrow.mockResolvedValue(row);db.$queryRaw.mockResolvedValue([{id:id(1),claimToken:id(5)}]);let release!:()=>void;(appendCargoPilotDomainEvent as jest.Mock).mockImplementation(()=>new Promise<void>(resolve=>release=resolve));const timeout=redis.withRedisTimeout as jest.Mock;timeout.mockRejectedValueOnce(Error("synthetic deadline"));
 try {expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({published:0,contained:1});expect(release).toBeDefined();const calls=db.$queryRaw.mock.calls.length;expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({busy:true,claimed:0});expect(db.$queryRaw.mock.calls).toHaveLength(calls);expect(appendCargoPilotDomainEvent).toHaveBeenCalledTimes(1);release();for(let n=0;n<10;n++)await Promise.resolve();db.$queryRaw.mockResolvedValue([]);expect(await processAnalyticsOutboxBatchOnce()).toMatchObject({busy:false,claimed:0});}finally{release?.();timeout.mockImplementation((_label:any,fn:any)=>fn());}
});
