jest.mock("../../src/config/prismaClient", () => ({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/modules/analytics-core/infrastructure/analyticsOutbox",()=>({enqueueCargoPilotDomainEventsTx:jest.fn(async()=>undefined)}));
import {database as db} from "./fixtures";
import { requireDispatchAuthority,dispatchOrderWhere } from "../../src/modules/orders-core/domain/dispatch-authority";
import { assignDriversBulk, updateOrdersStatusBulk, updateDriverOrderStatus } from "../../src/modules/orders-core/operations/order-status";
import { enqueueCargoPilotDomainEventsTx } from "../../src/modules/analytics-core/infrastructure/analyticsOutbox";
const id=(n:number)=>`a0000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const actor={id:id(1),membershipId:id(2),companyMembershipId:id(2),companyId:id(3),tenantId:id(4),tenantMembershipId:id(5),warehouseId:id(6),scopes:[{scopeType:"company" as const,scopeRefId:id(99)}],permissionCodes:["shipment.changeStatus","shipment.assignCourier"]};
function record(patch:Record<string,unknown>={}){return{id:actor.membershipId,userId:actor.id,status:"active",companyId:actor.companyId,tenantId:actor.tenantId,tenantMembershipId:actor.tenantMembershipId,branchId:null,branch:null,tenant:{id:actor.tenantId,status:"active"},tenantMembership:{id:actor.tenantMembershipId,userId:actor.id,tenantId:actor.tenantId,status:"active"},company:{id:actor.companyId,tenantId:actor.tenantId,isActive:true},user:{id:actor.id,name:"Synthetic dispatcher",email:"synthetic@example.test",warehouseId:actor.warehouseId,customerEntityId:id(7)},scopes:[{scopeType:"company",scopeRefId:actor.companyId}],roles:[{role:{code:"dispatcher",rolePermissions:[{permission:{key:"shipment.changeStatus"}}]}}],...patch};}
beforeEach(()=>{jest.clearAllMocks();db.orderCustodyAction.count.mockResolvedValue(0);db.companyMembership.findFirst.mockReset().mockResolvedValue(record());db.order.findMany.mockReset().mockResolvedValue([]);db.order.findFirst.mockReset().mockResolvedValue(null);db.user.findUnique.mockReset().mockResolvedValue({id:id(10),driverType:"local"});db.$transaction.mockReset().mockImplementation(async(fn:any)=>fn(db));});
function noEffects(){expect(db.order.updateMany).not.toHaveBeenCalled();expect(db.tracking.create).not.toHaveBeenCalled();expect(db.tracking.createMany).not.toHaveBeenCalled();expect(enqueueCargoPilotDomainEventsTx).not.toHaveBeenCalled();}
it("current stored scope replaces caller global warehouse/customer/company claims",async()=>{const authority=await requireDispatchAuthority(actor,"shipment.changeStatus");expect(authority.actor.scopes).toEqual(record().scopes);expect(authority.actor.warehouseId).toBeNull();expect(authority.actor.customerEntityId).toBeNull();const text=JSON.stringify(dispatchOrderWhere(authority,[id(8)]));expect(text).toContain(actor.tenantId);expect(text).toContain(actor.companyId);expect(text).not.toContain(id(99));expect(text).not.toContain(actor.warehouseId);expect(db.companyMembership.findFirst).toHaveBeenCalledTimes(2);});
it("explicit stored warehouse scope retains the warehouse restriction without first-warehouse selection",async()=>{db.companyMembership.findFirst.mockResolvedValue(record({scopes:[{scopeType:"warehouse",scopeRefId:actor.warehouseId},{scopeType:"warehouse",scopeRefId:id(66)}]}));const authority=await requireDispatchAuthority(actor,"shipment.changeStatus");expect(authority.actor.warehouseId).toBe(actor.warehouseId);expect(JSON.stringify(dispatchOrderWhere(authority,[id(8)]))).toContain(actor.warehouseId);});
it.each(["id","membershipId","companyMembershipId","companyId","tenantId","tenantMembershipId"])("missing %s rejects before protected reads or writes",async field=>{await expect(requireDispatchAuthority({...actor,[field]:undefined} as any,"shipment.changeStatus")).rejects.toMatchObject({statusCode:403});expect(db.companyMembership.findFirst).not.toHaveBeenCalled();expect(db.order.findMany).not.toHaveBeenCalled();noEffects();});
it("mismatched membership aliases reject before lookup",async()=>{await expect(requireDispatchAuthority({...actor,membershipId:id(99)},"shipment.changeStatus")).rejects.toMatchObject({statusCode:403});expect(db.companyMembership.findFirst).not.toHaveBeenCalled();noEffects();});
it.each([
  {status:"revoked"},{tenantId:id(44)},{companyId:id(33)},{tenantMembershipId:null},
  {tenant:{id:actor.tenantId,status:"suspended"}},
  {tenantMembership:{id:actor.tenantMembershipId,userId:id(11),tenantId:actor.tenantId,status:"active"}},
  {company:{id:actor.companyId,tenantId:id(44),isActive:true}},
])("inactive/foreign/partial authoritative context rejects before business access: %j",async patch=>{db.companyMembership.findFirst.mockResolvedValue(record(patch));await expect(updateOrdersStatusBulk({actor,orderIds:[id(8)],status:"exception",reasonCode:"NO_CAPACITY_PICKUP"})).rejects.toMatchObject({statusCode:403});expect(db.order.findMany).not.toHaveBeenCalled();noEffects();});
it("request permission claims cannot grant missing stored action",async()=>{db.companyMembership.findFirst.mockResolvedValue(record({roles:[]}));await expect(updateDriverOrderStatus({actor,orderId:id(8),status:"pickup_in_progress"})).rejects.toMatchObject({statusCode:403});expect(db.order.findFirst).not.toHaveBeenCalled();noEffects();});
it("missing stored scope never produces company-wide fallback",async()=>{db.companyMembership.findFirst.mockResolvedValue(record({scopes:[]}));await expect(updateOrdersStatusBulk({actor,orderIds:[id(8)],status:"exception",reasonCode:"NO_CAPACITY_PICKUP"})).rejects.toMatchObject({statusCode:403});expect(db.order.findMany).not.toHaveBeenCalled();noEffects();});
it("scope revoked during resolution fails closed",async()=>{db.companyMembership.findFirst.mockResolvedValueOnce(record()).mockResolvedValueOnce(null);await expect(requireDispatchAuthority(actor,"shipment.changeStatus")).rejects.toMatchObject({statusCode:403});expect(db.order.findMany).not.toHaveBeenCalled();noEffects();});
it.each([null,{id:id(10),roles:[]},{id:id(10),roles:[{role:{companyId:id(99),isSystem:false,rolePermissions:[{permission:{key:"drivers.telemetry"}}]}}]}])("driver missing applicable selected-company telemetry authority rejects: %j",async target=>{const dispatcher=record({roles:[{role:{code:"dispatcher",rolePermissions:[{permission:{key:"shipment.assignCourier"}}]}}]});db.companyMembership.findFirst.mockResolvedValueOnce(dispatcher).mockResolvedValueOnce(dispatcher).mockResolvedValueOnce(dispatcher).mockResolvedValueOnce(dispatcher).mockResolvedValueOnce(target);db.companyMembership.findUnique.mockResolvedValue({id:id(10)});db.$executeRawUnsafe.mockResolvedValue(0);db.$queryRaw.mockResolvedValue([{id:id(8)}]);db.order.findMany.mockResolvedValue([{id:id(8),status:"pending",assignedDriverId:null,currentWarehouseId:null,updatedAt:new Date("2026-10-03T00:00:00.000Z")}]);await expect(assignDriversBulk({actor,orderIds:[id(8)],expectedStates:[{orderId:id(8),updatedAt:"2026-10-03T00:00:00.000Z",status:"pending",assignedDriverId:null,currentWarehouseId:null}],driverId:id(10)})).rejects.toMatchObject({statusCode:403});expect(db.order.findMany).toHaveBeenCalledTimes(2);const where=db.companyMembership.findFirst.mock.calls[4][0].where;expect(where).toMatchObject({companyId:actor.companyId,tenantId:actor.tenantId,status:"active",company:{tenantId:actor.tenantId,isActive:true,type:"company"}});noEffects();});
it.each([{tenantId:id(44),companyId:id(33)},{companyId:id(33)}])("selected context requires exact owner or assigned company in addition to object scope: %j",async patch=>{const selected={...actor,...patch};const row=record({...patch,company:{id:selected.companyId,tenantId:selected.tenantId,isActive:true},tenant:{id:selected.tenantId,status:"active"},tenantMembership:{id:selected.tenantMembershipId,userId:selected.id,tenantId:selected.tenantId,status:"active"},scopes:[{scopeType:"company",scopeRefId:selected.companyId}]});db.companyMembership.findFirst.mockResolvedValue(row);const authority=await requireDispatchAuthority(selected,"shipment.changeStatus");expect(dispatchOrderWhere(authority,[id(8)]).AND).toContainEqual({OR:[{ownerOrgId:selected.companyId},{assignedOrgId:selected.companyId}]});});
