jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:new Proxy({}, {get:(_t,name)=>{const value=(mockPrisma as any)[name];return typeof value==="function"?value.bind(mockPrisma):value;}})}));
import {Pool} from "pg";
import {PrismaClient} from "@prisma/client";
import {PrismaPg} from "@prisma/adapter-pg";
import {randomUUID} from "crypto";
import {createTenantDemoFixture,TENANT_DEMO_IDS as ids} from "../../src/modules/tenancy/demo-fixtures";
import {persistTenantDemoFixture} from "../tenancy/postgres-fixture.persistence";
import {readDownstreamRecovery} from "../../src/modules/orders-core/read/downstream-recovery";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,run=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!run||!/^[a-f0-9]{12}$/.test(run))throw Error("Disposable run required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!=="/cp_worker_"+run)throw Error("Refusing existing database");
const options="-c statement_timeout=5000 -c lock_timeout=2000 -c idle_in_transaction_session_timeout=5000";
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options});let mockPrisma:PrismaClient;
const fixture=createTenantDemoFixture(),memberships=fixture.companyMemberships.filter(m=>m.userId===ids.users.multiTenant),roles:string[]=[];
const actor=(i=0):any=>({...memberships[i],id:memberships[i].userId,membershipId:memberships[i].id,companyMembershipId:memberships[i].id});
const orderIds=memberships.map(m=>fixture.orders.find(o=>o.ownerOrgId===m.companyId)!.id),jobs:string[]=[],outboxes:string[]=[],providers:string[]=[],legs:string[]=[];
async function snapshot(){const tables=['Order','OrderCreationIntent','OrderCreationReceipt','PricingComponent','OrderLeg','OrderLabelJob','Parcel','IntegrationOutbox','IntegrationCanonicalEvent','IntegrationDeliveryAttempt','Tracking','UserNotification','AnalyticsDomainEventOutbox'];const result:any={};for(const table of tables)result[table]=(await pool.query('SELECT to_jsonb(t) AS row FROM "'+table+'" t ORDER BY to_jsonb(t)::text')).rows;return result;}
beforeAll(async()=>{const marker=(await pool.query('SELECT "runId" FROM "_CPDisposableRun"')).rows;if(marker.length!==1||marker[0].runId!==run)throw Error("Ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{await client.query("ROLLBACK");client.release();}
mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:4,connectionTimeoutMillis:3000,options})});const p=await mockPrisma.permission.create({data:{key:"shipment.view",resource:"synthetic",action:"view"}});
for(let i=0;i<memberships.length;i++){const m=memberships[i],orderId=orderIds[i];const role=await mockPrisma.role.create({data:{code:randomUUID(),name:"Synthetic recovery viewer",companyId:m.companyId}});roles.push(role.id);await mockPrisma.rolePermission.create({data:{roleId:role.id,permissionId:p.id}});await mockPrisma.membershipRole.create({data:{membershipId:m.id,roleId:role.id}});await mockPrisma.membershipScope.create({data:{membershipId:m.id,scopeType:"company",scopeRefId:m.companyId}});
await mockPrisma.$transaction(async tx=>{const intent=await tx.orderCreationIntent.create({data:{tenantId:m.tenantId,companyId:m.companyId,userId:m.userId,tenantMembershipId:m.tenantMembershipId,companyMembershipId:m.id,operationId:randomUUID(),kind:"order",fingerprint:"a".repeat(64),rowCount:1}});await tx.orderCreationReceipt.create({data:{intentId:intent.id,ordinal:0,tenantId:m.tenantId,companyId:m.companyId,orderId}});});
for(let j=0;j<5;j++)await mockPrisma.pricingComponent.create({data:{orderId,componentType:"handling",source:"rule",amount:"12.30",currency:"USD",description:"SENSITIVE-CANARY",referenceKey:"SENSITIVE-CANARY"}});
const job=await mockPrisma.orderLabelJob.create({data:{orderId,ownershipTenantId:m.tenantId,ownershipCompanyId:m.companyId,acceptedAt:new Date(),capability:"label.generate",error:"SENSITIVE-CANARY"}});jobs.push(job.id);
await mockPrisma.parcel.create({data:{orderId,pieceNo:1,pieceTotal:1,parcelCode:randomUUID()}});
const provider=await mockPrisma.integrationProvider.create({data:{companyId:m.companyId,domain:"carrier",providerCode:randomUUID(),environment:"sandbox"}});providers.push(provider.id);
const leg=await mockPrisma.orderLeg.create({data:{orderId,sequence:10,carrierProviderId:provider.id,carrierBookingStatus:"requested",carrierBookingError:"SENSITIVE-CANARY",carrierRef:"SENSITIVE-CANARY",metadata:{secret:"SENSITIVE-CANARY"}}});legs.push(leg.id);
const outbox=await mockPrisma.integrationOutbox.create({data:{companyId:m.companyId,providerId:provider.id,domain:"carrier",providerCode:provider.providerCode,environment:"sandbox",aggregateType:"shipment",aggregateId:leg.id,operation:"create_shipment",eventType:"shipment.assigned",idempotencyKey:randomUUID(),payload:{secret:"SENSITIVE-CANARY"},lastError:"SENSITIVE-CANARY",ownershipTenantId:m.tenantId,ownershipOrderId:orderId,acceptedAt:new Date()}});outboxes.push(outbox.id);
}});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});
it("actual owned queries expose four sections with safe projections and no business changes",async()=>{const before=await snapshot();for(let i=0;i<3;i++)for(const section of ['creation','pricing','labels','carrier']){const result=await readDownstreamRecovery(actor(i),orderIds[i],{section});expect(result.orderId).toBe(orderIds[i]);expect(JSON.stringify(result)).not.toContain('SENSITIVE-CANARY');if(section==='creation')expect(result).toMatchObject({state:'confirmed_completion',items:[{visibleConfirmedRows:1,batchEvidence:'confirmed_completion'}]});if(section==='labels'||section==='carrier')expect(result.items[0]).toMatchObject({evidence:{state:'pending_work'}});}expect(await snapshot()).toEqual(before);});
it("foreign tenant/company, missing context and legacy parent are invisible without changes",async()=>{const legacy=await mockPrisma.order.create({data:{orderNumber:randomUUID(),customerId:actor().id,ownerOrgId:actor().companyId,pickupAddress:'Synthetic',dropoffAddress:'Synthetic'}}),before=await snapshot();for(const orderId of [orderIds[1],orderIds[2],legacy.id])await expect(readDownstreamRecovery(actor(),orderId,{section:'carrier'})).rejects.toMatchObject({statusCode:404});await expect(readDownstreamRecovery({} as any,orderIds[0])).rejects.toMatchObject({statusCode:403});expect(await snapshot()).toEqual(before);});
it("actual scoped seek pagination cannot return foreign components",async()=>{const before=await snapshot(),seen:string[]=[];let cursor:string|undefined;do{const result=await readDownstreamRecovery(actor(),orderIds[0],{section:'pricing',limit:2,cursor});expect(result.items.length).toBeLessThanOrEqual(2);seen.push(...result.items.map((x:any)=>x.id));cursor=result.nextCursor??undefined;}while(cursor);expect(new Set(seen).size).toBe(5);const own=await mockPrisma.pricingComponent.findMany({where:{orderId:orderIds[0]},select:{id:true}});expect(seen.sort()).toEqual(own.map(x=>x.id).sort());const foreign=await mockPrisma.pricingComponent.findFirstOrThrow({where:{orderId:orderIds[2]}});const result=await readDownstreamRecovery(actor(),orderIds[0],{section:'pricing',cursor:foreign.id});expect(result.items.every((x:any)=>seen.includes(x.id))).toBe(true);expect(await snapshot()).toEqual(before);});
it("fresh permission and object scope removal deny the next read",async()=>{const grant=await mockPrisma.rolePermission.findFirstOrThrow({where:{roleId:roles[0]}}),scope=await mockPrisma.membershipScope.findFirstOrThrow({where:{membershipId:memberships[0].id}}),before=await snapshot();await mockPrisma.rolePermission.delete({where:{id:grant.id}});try{await expect(readDownstreamRecovery(actor(),orderIds[0])).rejects.toMatchObject({statusCode:403});}finally{await mockPrisma.rolePermission.create({data:grant});}await mockPrisma.membershipScope.delete({where:{id:scope.id}});try{await expect(readDownstreamRecovery(actor(),orderIds[0])).rejects.toMatchObject({statusCode:403});}finally{await mockPrisma.membershipScope.create({data:scope});}expect(await snapshot()).toEqual(before);});
it("durable completion and timeout/failed attempts remain distinct without payload disclosure",async()=>{await mockPrisma.orderLabelJob.update({where:{id:jobs[0]},data:{status:'completed',attempts:1}});await mockPrisma.parcel.updateMany({where:{orderId:orderIds[0]},data:{labelKey:'synthetic/stored-reference.pdf'}});await mockPrisma.integrationOutbox.update({where:{id:outboxes[0]},data:{status:'failed',executionStartedAt:new Date(),attemptCount:1}});let before=await snapshot();expect((await readDownstreamRecovery(actor(),orderIds[0],{section:'labels'})).items[0]).toMatchObject({evidence:{state:'confirmed_completion'}});expect((await readDownstreamRecovery(actor(),orderIds[0],{section:'carrier'})).items[0]).toMatchObject({evidence:{state:'uncertain_external_outcome'}});expect(await snapshot()).toEqual(before);await mockPrisma.orderLabelJob.update({where:{id:jobs[0]},data:{status:'failed'}});before=await snapshot();expect((await readDownstreamRecovery(actor(),orderIds[0],{section:'labels'})).items[0]).toMatchObject({evidence:{state:'uncertain_external_outcome'}});expect(await snapshot()).toEqual(before);});
it("wrong child binding and unaccepted legacy work never become proven completion",async()=>{const p=await mockPrisma.integrationProvider.findUniqueOrThrow({where:{id:providers[0]}});await mockPrisma.integrationOutbox.update({where:{id:outboxes[0]},data:{aggregateId:legs[2]}});await mockPrisma.integrationOutbox.create({data:{companyId:p.companyId,providerId:p.id,domain:p.domain,providerCode:p.providerCode,aggregateType:'shipment',aggregateId:legs[0],operation:'create_shipment',eventType:'synthetic-legacy',payload:{secret:'SENSITIVE-CANARY'},idempotencyKey:randomUUID()}});const before=await snapshot(),result=await readDownstreamRecovery(actor(),orderIds[0],{section:'carrier'});expect(result.items).toHaveLength(1);expect(result.items[0]).toMatchObject({legId:null,evidence:{state:'insufficient_evidence'}});expect(JSON.stringify(result)).not.toContain('SENSITIVE-CANARY');expect(await snapshot()).toEqual(before);});

it("authoritative canonical binding proves local application only, not independent provider verification",async()=>{const row=await mockPrisma.integrationOutbox.findUniqueOrThrow({where:{id:outboxes[1]}});await mockPrisma.integrationOutbox.update({where:{id:row.id},data:{status:'sent',attemptCount:1,executionStartedAt:new Date()}});await mockPrisma.orderLeg.update({where:{id:legs[1]},data:{carrierBookingStatus:'booked'}});await mockPrisma.integrationCanonicalEvent.create({data:{companyId:row.companyId,providerId:row.providerId,domain:row.domain,providerCode:row.providerCode,source:'outbound_response',outboxId:row.id,status:'processed',processedAt:new Date(),aggregateType:'shipment',aggregateId:legs[1],eventType:'carrier.shipment.created',payloadJson:{secret:'SENSITIVE-CANARY'},occurredAt:new Date()}});const before=await snapshot(),result=await readDownstreamRecovery(actor(1),orderIds[1],{section:'carrier'});expect(result.items[0]).toMatchObject({legId:legs[1],evidence:{state:'confirmed_completion'}});expect(JSON.stringify(result)).not.toContain('SENSITIVE-CANARY');expect(await snapshot()).toEqual(before);});
