jest.mock("../../src/config/prismaClient", () => ({__esModule:true,default:new Proxy({}, {get:(_target,name)=>{const value=(mockPrisma as any)[name];return typeof value==="function"?value.bind(mockPrisma):value;}})}));
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents",()=>({buildCargoPilotDomainEvent:(input:any)=>({...input,id:require("crypto").randomUUID(),occurredAt:new Date().toISOString(),schemaVersion:1})}));
import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import {createTenantDemoFixture,TENANT_DEMO_IDS as ids} from "../../src/modules/tenancy/demo-fixtures";
import {persistTenantDemoFixture} from "../tenancy/postgres-fixture.persistence";
import {updateDriverOrderStatus} from "../../src/modules/orders-core/operations/order-status";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable driver lifecycle identity required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing PostgreSQL target");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});let mockPrisma:PrismaClient;
const actor={id:ids.users.maker,membershipId:ids.companyMemberships.makerTransAsiaUz,companyMembershipId:ids.companyMemberships.makerTransAsiaUz,tenantId:ids.tenants.transAsia,tenantMembershipId:ids.tenantMemberships.makerTransAsia,companyId:ids.organizations.transAsiaUz};const orderId=ids.orders.transAsiaUz;
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,createTenantDemoFixture());await client.query("COMMIT");}finally{client.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});const role=await mockPrisma.role.create({data:{code:"synthetic_lifecycle_driver",name:"Synthetic lifecycle driver",companyId:actor.companyId,isSystem:false}});const permission=await mockPrisma.permission.create({data:{key:"shipment.changeStatus",resource:"orders",action:"update",description:"Synthetic lifecycle test"}});await mockPrisma.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}});await mockPrisma.membershipRole.create({data:{membershipId:actor.membershipId,roleId:role.id}});await mockPrisma.membershipScope.create({data:{membershipId:actor.membershipId,scopeType:"company",scopeRefId:actor.companyId}});});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});
beforeEach(async()=>{await mockPrisma.order.update({where:{id:orderId},data:{status:"assigned",assignedDriverId:actor.id,serviceCharge:0,codAmount:0,serviceChargePaidStatus:"NOT_PAID",codPaidStatus:"NOT_PAID",deliveryChargePaidBy:"SENDER"}});});
const snapshot=async()=>({orders:await mockPrisma.order.findMany({orderBy:{id:"asc"}}),tracking:await mockPrisma.tracking.findMany({orderBy:{id:"asc"}}),outbox:await mockPrisma.analyticsDomainEventOutbox.findMany({orderBy:{id:"asc"}}),cash:await mockPrisma.cashCollection.findMany({orderBy:{id:"asc"}}),finance:await mockPrisma.financeJournalEntry.findMany({orderBy:{id:"asc"}})});
it("driver lifecycle PostgreSQL valid transition commits one tracking and durable outbox with unchanged financial state",async()=>{const before=await snapshot();const result=await updateDriverOrderStatus({actor,orderId,status:"pickup_in_progress"});expect(result).toMatchObject({id:orderId,status:"pickup_in_progress",assignedDriverId:actor.id});expect(Object.keys(result!).sort()).toEqual(["id","orderNumber","status","assignedDriverId","currentWarehouseId","updatedAt"].sort());const after=await snapshot();expect(after.tracking.length-before.tracking.length).toBe(1);expect(after.outbox.length-before.outbox.length).toBe(1);expect(after.cash).toEqual(before.cash);expect(after.finance).toEqual(before.finance);});
it("driver lifecycle PostgreSQL three concurrent identical transitions accept one without duplicate history/outbox",async()=>{const before=await snapshot();const results=await Promise.allSettled(Array.from({length:3},()=>updateDriverOrderStatus({actor,orderId,status:"pickup_in_progress"})));expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect(results.filter(r=>r.status==="rejected")).toHaveLength(2);const after=await snapshot();expect(after.orders.find(o=>o.id===orderId)!.status).toBe("pickup_in_progress");expect(after.tracking.length-before.tracking.length).toBe(1);expect(after.outbox.length-before.outbox.length).toBe(1);expect(after.cash).toEqual(before.cash);expect(after.finance).toEqual(before.finance);});
it.each(["assignment","status","cash"])("driver lifecycle PostgreSQL committed %s between initial scoped read and lock is reloaded and rejects without effects",async condition=>{
  if(condition==="cash")await mockPrisma.order.update({where:{id:orderId},data:{status:"pickup_in_progress"}});
  const original=mockPrisma.$transaction.bind(mockPrisma);let baseline:Awaited<ReturnType<typeof snapshot>>|undefined;
  const spy=jest.spyOn(mockPrisma,"$transaction").mockImplementation(async(fn:any,options:any)=>original(async(tx:any)=>{const find=tx.order.findFirst.bind(tx.order);let calls=0;const inner=jest.spyOn(tx.order,"findFirst").mockImplementation(async(query:any)=>{const result=await find(query);if(++calls===1){if(condition==="assignment")await mockPrisma.order.update({where:{id:orderId},data:{assignedDriverId:ids.users.checker}});else if(condition==="status")await mockPrisma.order.update({where:{id:orderId},data:{status:"cancelled"}});else await mockPrisma.cashCollection.create({data:{orderId,kind:"service_charge",status:"expected",expectedAmount:5}});baseline=await snapshot();}return result;});try{return await fn(tx);}finally{inner.mockRestore();}},options));
  try{await expect(updateDriverOrderStatus({actor,orderId,status:condition==="cash"?"picked_up":"pickup_in_progress"})).rejects.toThrow(condition==="assignment"?"not assigned":condition==="status"?"final state":"Collect cash first");expect(baseline).toBeDefined();expect(await snapshot()).toEqual(baseline);}finally{spy.mockRestore();if(condition==="cash")await mockPrisma.cashCollection.deleteMany({where:{orderId}});}
});
it("driver lifecycle PostgreSQL failed outbox insert rolls back order and tracking",async()=>{const before=await snapshot();await pool.query(`CREATE FUNCTION cp_lifecycle_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic lifecycle outbox failure'; END $$;CREATE TRIGGER cp_lifecycle_fail BEFORE INSERT ON "AnalyticsDomainEventOutbox" FOR EACH ROW EXECUTE FUNCTION cp_lifecycle_fail();`);try{await expect(updateDriverOrderStatus({actor,orderId,status:"pickup_in_progress"})).rejects.toThrow("synthetic lifecycle outbox failure");expect(await snapshot()).toEqual(before);}finally{await pool.query('DROP TRIGGER cp_lifecycle_fail ON "AnalyticsDomainEventOutbox"; DROP FUNCTION cp_lifecycle_fail();');}});
it("driver lifecycle PostgreSQL foreign tenant and same-tenant company parents reject without protected response or writes",async()=>{const before=await snapshot();for(const foreign of [ids.orders.transAsiaDe,ids.orders.unrelated])await expect(updateDriverOrderStatus({actor,orderId:foreign,status:"pickup_in_progress"})).rejects.toMatchObject({statusCode:404});expect(await snapshot()).toEqual(before);});
it("driver lifecycle PostgreSQL observed Order lock wait serializes a competing accepted mutation",async()=>{
  const held=await pool.connect();let release=false;const before=await snapshot();let pending:Promise<unknown>|undefined;
  try{await held.query("BEGIN");await held.query('SELECT "id" FROM "Order" WHERE "id"=$1 FOR UPDATE',[orderId]);pending=updateDriverOrderStatus({actor,orderId,status:"pickup_in_progress"});pending.catch(()=>undefined);
    let observed=false;for(let n=0;n<20;n++){const waiting=await pool.query(`SELECT count(*)::int AS count FROM pg_stat_activity WHERE datname=current_database() AND wait_event_type='Lock' AND query LIKE '%FOR UPDATE%' AND query LIKE '%"Order"%'`);if(waiting.rows[0].count>0){observed=true;break;}await new Promise(resolve=>setTimeout(resolve,50));}expect(observed).toBe(true);
    await held.query("COMMIT");release=true;await pending;const after=await snapshot();expect(after.orders.find(o=>o.id===orderId)!.status).toBe("pickup_in_progress");expect(after.tracking.length-before.tracking.length).toBe(1);expect(after.outbox.length-before.outbox.length).toBe(1);expect(after.cash).toEqual(before.cash);expect(after.finance).toEqual(before.finance);
  }finally{if(!release)await held.query("ROLLBACK");held.release();if(pending)await Promise.allSettled([pending]);}
});
