jest.mock('../../src/config/prismaClient',()=>({__esModule:true,default:{}}));
jest.mock('../../src/config/redis',()=>({getRedisClient:async()=>null,getRedisPrefix:()=> 'test',withRedisTimeout:(_n:any,w:any)=>w()}));
jest.mock('../../src/modules/identity-access/access-control',()=>({clearIdentityAccessCacheForUser:jest.fn()}));
import {readDriverDelegation,listDriverInvitations,listDriverEligibility} from '../../src/modules/identity-access/application/driver-delegation';
import {DRIVER_PROFILES} from '../../src/modules/identity-access/application/driver-profiles';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor:any={id:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),companyMembershipId:id(5),membershipId:id(5)};
function harness(){
 const a:any={membershipId:id(5),userId:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),ceilingRevision:'driver-delegation.v1',profileRevisions:['local-driver.v1'],enabled:true};
 const m:any={id:id(5),userId:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),status:'active',user:{id:id(1),email:'synthetic@example.invalid'},company:{id:id(3),tenantId:id(2),type:'company',isActive:true},tenant:{status:'active'},tenantMembership:{id:id(4),tenantId:id(2),userId:id(1),status:'active'},roles:[{roleId:id(9),role:{companyId:id(3),isSystem:false,rolePermissions:['membership.delegateDrivers','membership.invite'].map(key=>({permission:{key}}))}}],scopes:[{scopeType:'company',scopeRefId:id(3)}]};
 const tx:any={$queryRaw:jest.fn(async(s:any)=>s.join('').includes('CompanyDriverDelegationAuthority')?[a]:[]),$executeRaw:jest.fn(()=>{throw Error('Read wrote state')}),companyMembership:{findUnique:jest.fn(async()=>m)},companyDriverInvitation:{findMany:jest.fn(async()=>[])},companyDriverEligibility:{findMany:jest.fn(async()=>[])},companyDriverDelegationAuthority:{findUnique:jest.fn(async()=>null)},companyDelegationAuthority:{findUnique:jest.fn(async()=>null)}};
 return{a,m,tx,db:{$transaction:jest.fn((f:any)=>f(tx))} as any};
}
test('driver context mandatory before transaction',async()=>{const h=harness();await expect(readDriverDelegation(h.db,{} as any)).rejects.toMatchObject({code:'DELEGATION_CONTEXT_REQUIRED'});expect(h.db.$transaction).not.toHaveBeenCalled()});
test.each(['revoked','operational-only','foreign'])('driver accepted authority rejects %s',async(kind)=>{const h=harness();if(kind==='revoked')h.a.enabled=false;if(kind==='operational-only')h.m.roles[0].role.rolePermissions=[{permission:{key:'membership.delegateOperational'}}];if(kind==='foreign')h.a.companyId=id(99);await expect(readDriverDelegation(h.db,actor)).rejects.toMatchObject({code:'DELEGATION_AUTHORITY_REQUIRED'});expect(h.tx.$executeRaw).not.toHaveBeenCalled()});
test('ceiling exposes only accepted driver profiles without secret evidence',async()=>{const h=harness();h.a.secret='hidden';expect(await readDriverDelegation(h.db,actor)).toEqual({ceilingRevision:'driver-delegation.v1',companyMembershipId:id(5),profiles:[{revision:'local-driver.v1',driverType:'local'}],canInvite:true});expect(h.tx.$executeRaw).not.toHaveBeenCalled()});
test('invitation metadata, expired status and cursor binding remain bounded/no-write',async()=>{const h=harness();h.tx.companyDriverInvitation.findMany.mockResolvedValue([1,2].map(n=>({id:id(30+n),operationId:id(n),email:'synthetic@example.invalid',profileRevision:'local-driver.v1',state:'pending',expiresAt:new Date(0),createdAt:new Date(0),acceptedMembershipId:null,tokenHash:'hidden'})));const r=await listDriverInvitations(h.db,actor,{limit:1});expect(r.items[0].state).toBe('expired');expect(JSON.stringify(r)).not.toContain('hidden');expect(h.tx.companyDriverInvitation.findMany.mock.calls[0][0]).toMatchObject({where:{tenantId:id(2),companyId:id(3),inviterMembershipId:id(5)},take:2});await expect(listDriverEligibility(h.db,actor,{cursor:r.nextCursor})).rejects.toMatchObject({code:'DELEGATION_CURSOR_REJECTED'});await expect(listDriverInvitations(h.db,{...actor,companyMembershipId:id(55),membershipId:id(55)},{cursor:r.nextCursor})).rejects.toMatchObject({code:'DELEGATION_CURSOR_REJECTED'});await expect(listDriverInvitations(h.db,actor,{limit:51})).rejects.toBeTruthy();expect(h.tx.$executeRaw).not.toHaveBeenCalled()});
test('managed eligibility projects active work and excludes scopes/foreign acceptance/unrelated roles',async()=>{const h=harness();const e:any={membershipId:id(20),userId:id(21),tenantMembershipId:id(22),profileRevision:'local-driver.v1',driverType:'local',roleId:id(23),enabled:true,member:{user:{name:'Synthetic driver'}},acceptedAction:{action:'accept',result:{companyMembershipId:id(20),profileRevision:'local-driver.v1'}}};const m:any={...h.m,id:id(20),userId:id(21),tenantMembershipId:id(22),tenantMembership:{id:id(22),tenantId:id(2),userId:id(21),status:'active'},scopes:[],roles:[{roleId:id(23),role:{id:id(23),companyId:id(3),code:'local-driver.v1',isSystem:false,isOwnerRole:false,rolePermissions:DRIVER_PROFILES['local-driver.v1'].map(key=>({permission:{key}}))}}]};h.tx.companyMembership.findUnique.mockImplementation(async({where}:any)=>where.id===id(5)?h.m:m);h.tx.companyDriverEligibility.findMany.mockResolvedValue([e]);h.tx.$queryRaw.mockImplementation(async(s:any)=>s.join('').includes('CompanyDriverDelegationAuthority')?[h.a]:[{id:id(44)}]);expect((await listDriverEligibility(h.db,actor,{})).items[0]).toMatchObject({managed:true,activeWork:true});m.scopes=[{scopeType:'company',scopeRefId:id(3)}];expect((await listDriverEligibility(h.db,actor,{})).items).toEqual([]);m.scopes=[];e.acceptedAction.result.companyMembershipId=id(88);expect((await listDriverEligibility(h.db,actor,{})).items).toEqual([]);e.acceptedAction.result.companyMembershipId=id(20);m.roles[0].roleId=id(99);expect((await listDriverEligibility(h.db,actor,{})).items).toEqual([]);expect(h.tx.$executeRaw).not.toHaveBeenCalled();expect(h.tx.$queryRaw.mock.calls.every(([s]:any)=>!s.join('').includes('FOR SHARE'))).toBe(true)});
