jest.mock("../../src/config/prismaClient", () => ({ __esModule: true, default: new Proxy({}, { get: (_target, name) => { const value = (mockPrisma as any)[name]; return typeof value === "function" ? value.bind(mockPrisma) : value; } }) }));
// Domain envelope only is mocked to guarantee no Redis/logger import; actual transactional outbox writes run.
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents", () => ({ buildCargoPilotDomainEvent: (input: any) => ({ ...input, id: require("crypto").randomUUID(), occurredAt: new Date().toISOString(), schemaVersion: 1 }) }));
import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { randomUUID } from "crypto";
import { createTenantDemoFixture, TENANT_DEMO_IDS as ids } from "../../src/modules/tenancy/demo-fixtures";
import { persistTenantDemoFixture } from "../tenancy/postgres-fixture.persistence";
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"disposable-finance",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
import { prismaFinanceRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance.repository";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable legal entity identity required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing PostgreSQL target");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});let mockPrisma:PrismaClient;const fixture=createTenantDemoFixture();
function actor(m:any){return {id:m.userId,tenantId:m.tenantId,tenantMembershipId:m.tenantMembershipId,companyId:m.companyId,companyMembershipId:m.id,membershipId:m.id} as any;}
const owned=fixture.companyMemberships.find(m=>m.id===ids.companyMemberships.makerTransAsiaUz)!;
async function business(){return {entities:await mockPrisma.financeLegalEntity.findMany({orderBy:{id:"asc"}}),audit:await mockPrisma.financeAuditEvent.count(),outbox:await mockPrisma.financeDomainEventOutbox.count()};}
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{client.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});for(const key of ["finance.accounts.read"])await mockPrisma.permission.create({data:{key,resource:"synthetic-finance",action:key}});for(const m of fixture.companyMemberships){const role=await mockPrisma.role.create({data:{companyId:m.companyId,code:randomUUID(),name:"Synthetic Finance"}});for(const key of ["finance.accounts.read"]){const permission=await mockPrisma.permission.findUniqueOrThrow({where:{key}});await mockPrisma.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}});}await mockPrisma.membershipRole.create({data:{membershipId:m.id,roleId:role.id}});await mockPrisma.membershipScope.create({data:{membershipId:m.id,scopeType:"company",scopeRefId:m.companyId}});}});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});
const accounts=new Map<string,string>();
beforeAll(async()=>{for(const entity of fixture.financeLegalEntities){const row=await mockPrisma.financeAccount.create({data:{legalEntityId:entity.id,code:"001",name:"Synthetic account",type:"asset"}});accounts.set(entity.companyId,row.id);}});
it("account lists isolate same user across two tenants and same-tenant companies",async()=>{for(const membership of fixture.companyMemberships.filter(m=>m.userId===ids.users.multiTenant)){const result:any=await repo.listAccounts(actor(membership),{limit:10});expect(result.items.map((r:any)=>r.id)).toEqual([accounts.get(membership.companyId)]);expect(result.items[0]).not.toHaveProperty("metadataJson");}});
it.each([ids.organizations.unrelated,ids.organizations.transAsiaDe])("compound ownership rejects a foreign parent insert and update without changing rows",async company=>{const id=accounts.get(owned.companyId)!;const foreign=accounts.get(company)!;const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;const before=await mockPrisma.financeAccount.findMany({orderBy:{id:"asc"}});for(const sql of ['INSERT INTO "FinanceAccount" ("id","legalEntityId","parentId","code","name","type","updatedAt") VALUES ($1,$2,$3,$4,$5,$6::"FinanceAccountType",CURRENT_TIMESTAMP)','UPDATE "FinanceAccount" SET "parentId"=$3 WHERE "id"=$1 AND "legalEntityId"=$2']){const args=sql.startsWith("INSERT")?[randomUUID(),entity.id,foreign,randomUUID(),"Synthetic rejected","asset"]:[id,entity.id,foreign];await expect(pool.query(sql,args)).rejects.toMatchObject({code:"23503",constraint:"FinanceAccount_owned_parent_fkey"});}expect(await mockPrisma.financeAccount.findMany({orderBy:{id:"asc"}})).toEqual(before);});

it("valid parent and owned code/id pagination work; foreign cursor rejects without writes",async()=>{const id=accounts.get(owned.companyId)!;const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;const parent=await mockPrisma.financeAccount.create({data:{legalEntityId:entity.id,code:"002",name:"Synthetic parent",type:"asset"}});await mockPrisma.financeAccount.update({where:{id},data:{parentId:parent.id}});const before=await mockPrisma.financeAccount.findMany({orderBy:{id:"asc"}});const first:any=await repo.listAccounts(actor(owned),{limit:1});expect(first.items[0]).toMatchObject({id,parentId:parent.id,parent:{id:parent.id,name:"Synthetic parent"}});expect(first.pageInfo).toMatchObject({hasMore:true,nextCursor:id});const next:any=await repo.listAccounts(actor(owned),{limit:1,cursor:id});expect(next.items.map((r:any)=>r.id)).toEqual([parent.id]);await expect(repo.listAccounts(actor(owned),{limit:1,cursor:accounts.get(ids.organizations.unrelated)})).rejects.toMatchObject({statusCode:404});expect(await mockPrisma.financeAccount.findMany({orderBy:{id:"asc"}})).toEqual(before);});
it("legacy null-owned legal entity hides its accounts without mutation",async()=>{const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{tenantId:null}});const before=await mockPrisma.financeAccount.findMany({orderBy:{id:"asc"}});try{expect(await repo.listAccounts(actor(owned),{limit:10})).toMatchObject({items:[],pageInfo:{hasMore:false}});expect(await mockPrisma.financeAccount.findMany({orderBy:{id:"asc"}})).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{tenantId:owned.tenantId}});}});
it("changing child legal entity while retaining its parent rejects without mutation",async()=>{const child=await mockPrisma.financeAccount.findUniqueOrThrow({where:{id:accounts.get(owned.companyId)!}});expect(child.parentId).not.toBeNull();const foreign=fixture.financeLegalEntities.find(e=>e.companyId===ids.organizations.transAsiaDe)!;await expect(pool.query('UPDATE "FinanceAccount" SET "legalEntityId"=$2,"code"=$3 WHERE "id"=$1',[child.id,foreign.id,randomUUID()])).rejects.toMatchObject({code:"23503",constraint:"FinanceAccount_owned_parent_fkey"});expect(await mockPrisma.financeAccount.findUniqueOrThrow({where:{id:child.id}})).toEqual(child);});
it("schema-to-migration target columns agree; transitional constraint remains NOT VALID",async()=>{const result=await pool.query(`SELECT convalidated,pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conname='FinanceAccount_owned_parent_fkey'`);expect(result.rows).toHaveLength(1);expect(result.rows[0].convalidated).toBe(false);expect(result.rows[0].definition).toContain('FOREIGN KEY ("legalEntityId", "parentId")');expect(result.rows[0].definition).toContain('REFERENCES "FinanceAccount"("legalEntityId", id)');expect(result.rows[0].definition).toContain('ON UPDATE RESTRICT ON DELETE RESTRICT');});
