jest.mock("../../src/config/prismaClient", () => ({ __esModule: true, default: new Proxy({}, { get: (_target, name) => { const value = (mockPrisma as any)[name]; return typeof value === "function" ? value.bind(mockPrisma) : value; } }) }));
// Domain envelope only is mocked to guarantee no Redis/logger import; actual transactional outbox writes run.
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents", () => ({ buildCargoPilotDomainEvent: (input: any) => ({ ...input, id: require("crypto").randomUUID(), occurredAt: new Date().toISOString(), schemaVersion: 1 }) }));
import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { randomUUID } from "crypto";
import { createTenantDemoFixture, TENANT_DEMO_IDS as ids } from "../../src/modules/tenancy/demo-fixtures";
import { persistTenantDemoFixture } from "../tenancy/postgres-fixture.persistence";
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"disposable-finance",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
import { prismaFinanceRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance.repository";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable legal entity identity required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing PostgreSQL target");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});let mockPrisma:PrismaClient;const fixture=createTenantDemoFixture();
function actor(m:any){return {id:m.userId,tenantId:m.tenantId,tenantMembershipId:m.tenantMembershipId,companyId:m.companyId,companyMembershipId:m.id,membershipId:m.id} as any;}
const owned=fixture.companyMemberships.find(m=>m.id===ids.companyMemberships.makerTransAsiaUz)!;
async function business(){return {entities:await mockPrisma.financeLegalEntity.findMany({orderBy:{id:"asc"}}),audit:await mockPrisma.financeAuditEvent.count(),outbox:await mockPrisma.financeDomainEventOutbox.count()};}
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{client.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});for(const key of ["finance.journals.read","finance.journals.create","finance.journals.post","finance.journals.reverse","finance.reports.read","finance.postingRules.read","finance.postingRules.manage"])await mockPrisma.permission.create({data:{key,resource:"synthetic-finance",action:key}});for(const m of fixture.companyMemberships){const role=await mockPrisma.role.create({data:{companyId:m.companyId,code:randomUUID(),name:"Synthetic Finance"}});for(const key of ["finance.journals.read","finance.journals.create","finance.journals.post","finance.journals.reverse","finance.reports.read","finance.postingRules.read","finance.postingRules.manage"]){const permission=await mockPrisma.permission.findUniqueOrThrow({where:{key}});await mockPrisma.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}});}await mockPrisma.membershipRole.create({data:{membershipId:m.id,roleId:role.id}});await mockPrisma.membershipScope.create({data:{membershipId:m.id,scopeType:"company",scopeRefId:m.companyId}});}});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});

const journals=new Map<string,string[]>(), accounts=new Map<string,string>();
beforeAll(async()=>{for(const entity of fixture.financeLegalEntities){const account=await mockPrisma.financeAccount.create({data:{legalEntityId:entity.id,code:"SYNTH",name:"Synthetic asset",type:"asset"}});accounts.set(entity.companyId,account.id);const rows=[];for(const n of [1,2]){const document=await mockPrisma.financeDocument.create({data:{legalEntityId:entity.id,documentNumber:"SYN-DOC-"+n,type:"manual_journal",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:"0.1000",baseAmount:"0.1000",fxRate:"1.0000000001",idempotencyKey:"synthetic-"+n,createdByUserId:owned.userId,metadataJson:{private:"SYNTHETIC-CANARY"}}});const row=await mockPrisma.financeJournalEntry.create({data:{legalEntityId:entity.id,documentId:document.id,journalNumber:"SYN-JRN-"+n,postingDate:new Date("2026-01-01"),createdAt:new Date("2026-01-0"+n),totalDebitBase:"0.1000",totalCreditBase:"0.1000",lines:{create:[{legalEntityId:entity.id,lineNumber:1,accountId:account.id,debitAmount:"0.1000",currency:"UZS",fxRate:"1.0000000001",debitBase:"0.1000",metadataJson:{private:"SYNTHETIC-CANARY"}},{legalEntityId:entity.id,lineNumber:2,accountId:account.id,creditAmount:"0.1000",currency:"UZS",fxRate:"1.0000000001",creditBase:"0.1000"}]}}});rows.push(row.id);}journals.set(entity.companyId,rows);}});
async function records(){return{...await business(),documents:await mockPrisma.financeDocument.findMany({orderBy:{id:"asc"}}),journals:await mockPrisma.financeJournalEntry.findMany({orderBy:{id:"asc"}}),lines:await mockPrisma.financeJournalLine.findMany({orderBy:{id:"asc"}})};}
it("selected context separates two tenants/three companies and safely preserves exact journal decimals",async()=>{const before=await records();for(const membership of fixture.companyMemberships.filter(m=>m.userId===ids.users.multiTenant)){const result:any=await repo.listJournals(actor(membership),{limit:10});expect(result.items.map((r:any)=>r.id)).toEqual([...journals.get(membership.companyId)!].reverse());for(const row of result.items){expect(row.document.totalAmount.toString()).toBe("0.1");expect(row.document.fxRate.toString()).toBe("1.0000000001");expect(row).not.toHaveProperty("postedByUserId");expect(row.document).not.toHaveProperty("metadataJson");const detail:any=await repo.getJournal(actor(membership),row.id);expect(detail.lines).toHaveLength(2);expect(detail._count.lines).toBe(2);for(const line of detail.lines){expect(line.account.id).toBe(accounts.get(membership.companyId));expect(line).not.toHaveProperty("metadataJson");expect(line).not.toHaveProperty("customerEntityId");}}}expect(await records()).toEqual(before);});
it("owned cursor paginates and foreign cursor/detail reject without configuration or business changes",async()=>{const before=await records();const first:any=await repo.listJournals(actor(owned),{limit:1});const next:any=await repo.listJournals(actor(owned),{limit:1,cursor:first.pageInfo.nextCursor});expect(next.items.map((r:any)=>r.id)).toEqual([journals.get(owned.companyId)![0]]);for(const company of [ids.organizations.unrelated,ids.organizations.transAsiaDe]){const foreign=journals.get(company)![0];await expect(repo.getJournal(actor(owned),foreign)).rejects.toMatchObject({statusCode:404});await expect(repo.listJournals(actor(owned),{limit:1,cursor:foreign})).rejects.toMatchObject({statusCode:404});}expect(await records()).toEqual(before);});
it.each(["document","account","reversal"] as const)("foreign-tenant %s reference update rejects atomically",async relationship=>{await inconsistent(relationship,ids.organizations.unrelated);});
it.each(["document","account","reversal"] as const)("same-tenant foreign-company %s reference update rejects atomically",async relationship=>{await inconsistent(relationship,ids.organizations.transAsiaDe);});
async function rejected(sql:string,values:any[],constraint:string,code="23503"){const client=await pool.connect();try{await client.query("BEGIN");const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;await client.query('INSERT INTO "FinanceAuditEvent" ("legalEntityId",action,"actorUserId") VALUES ($1,$2,$3)',[entity.id,"synthetic-before-rejection",owned.userId]);await client.query('INSERT INTO "FinanceDomainEventOutbox" ("legalEntityId","aggregateType","aggregateId","eventType","occurredAt","payloadJson","updatedAt") VALUES ($1,$2,$3,$4,NOW(),$5,NOW())',[entity.id,"synthetic-journal",journals.get(owned.companyId)![0],"synthetic.rejected",{}]);try{await client.query(sql,values);throw Error("Invalid reference accepted");}catch(error:any){expect(error.code).toBe(code);expect(error.constraint).toBe(constraint);}await client.query("ROLLBACK");}finally{await client.query("ROLLBACK");client.release();}}
async function inconsistent(relationship:string,company:string){const id=journals.get(owned.companyId)![0],foreign=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(company)![0]}});const line=await mockPrisma.financeJournalLine.findFirstOrThrow({where:{journalEntryId:id,lineNumber:1}});let doc:any;if(relationship==="document")doc=await mockPrisma.financeDocument.create({data:{legalEntityId:foreign.legalEntityId,documentNumber:randomUUID(),type:"manual_journal",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:"0.1000",baseAmount:"0.1000",fxRate:"1",idempotencyKey:randomUUID(),createdByUserId:owned.userId}});const before=await records();try{if(relationship==="document")await rejected('UPDATE "FinanceJournalEntry" SET "documentId"=$1 WHERE id=$2',[doc.id,id],"FinanceJournalEntry_document_entity_fkey");else if(relationship==="account")await rejected('UPDATE "FinanceJournalLine" SET "accountId"=$1 WHERE id=$2',[accounts.get(company)!,line.id],"FinanceJournalLine_account_entity_fkey");else await rejected('UPDATE "FinanceJournalEntry" SET "reversalOfId"=$1 WHERE id=$2',[foreign.id,id],"FinanceJournalEntry_reversal_entity_fkey");expect(await records()).toEqual(before);}finally{if(doc)await mockPrisma.financeDocument.delete({where:{id:doc.id}});}}

it("null/inactive finance ownership hides journals without read-driven configuration",async()=>{const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;for(const data of [{tenantId:null},{isActive:false}]){await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data});const before=await records();try{expect(await repo.listJournals(actor(owned),{limit:10})).toMatchObject({items:[]});await expect(repo.getJournal(actor(owned),journals.get(owned.companyId)![0])).rejects.toMatchObject({statusCode:404});expect(await records()).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{tenantId:owned.tenantId,isActive:true}});}}});
it("current suspended membership denies previously authorized journal reads",async()=>{await repo.listJournals(actor(owned),{limit:10});await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"suspended"}});const before=await records();try{await expect(repo.getJournal(actor(owned),journals.get(owned.companyId)![0])).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);}finally{await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"active"}});}});

function entity(company=owned.companyId){return fixture.financeLegalEntities.find(e=>e.companyId===company)!;}
async function draftDocument(company:string){return mockPrisma.financeDocument.create({data:{legalEntityId:entity(company).id,documentNumber:randomUUID(),type:"manual_journal",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:"0.1000",baseAmount:"0.1000",fxRate:"1",idempotencyKey:randomUUID(),createdByUserId:owned.userId}});}
it.each([ids.organizations.unrelated,ids.organizations.transAsiaDe])("foreign entity %s reference inserts reject with audit/outbox rollback",async company=>{const doc=await draftDocument(company),local=await draftDocument(owned.companyId);const before=await records();try{await rejected('INSERT INTO "FinanceJournalEntry" ("legalEntityId","documentId","journalNumber","postingDate","totalDebitBase","totalCreditBase","updatedAt") VALUES ($1,$2,$3,$4,1,1,NOW())',[entity().id,doc.id,randomUUID(),new Date("2026-01-01")],"FinanceJournalEntry_document_entity_fkey");await rejected('INSERT INTO "FinanceJournalLine" ("legalEntityId","journalEntryId","lineNumber","accountId",currency,"fxRate") VALUES ($1,$2,99,$3,$4,1)',[entity().id,journals.get(owned.companyId)![0],accounts.get(company),"UZS"],"FinanceJournalLine_account_entity_fkey");await rejected('INSERT INTO "FinanceJournalEntry" ("legalEntityId","documentId","journalNumber","postingDate","totalDebitBase","totalCreditBase","reversalOfId","updatedAt") VALUES ($1,$2,$3,$4,1,1,$5,NOW())',[entity().id,local.id,randomUUID(),new Date("2026-01-01"),journals.get(company)![0]],"FinanceJournalEntry_reversal_entity_fkey");await rejected('INSERT INTO "FinanceDocument" ("legalEntityId","documentNumber",type,"documentDate","postingDate",currency,"totalAmount","baseAmount","fxRate","idempotencyKey","createdByUserId","reversalOfId","updatedAt") VALUES ($1,$2,$3,$4,$4,$5,1,1,1,$6,$7,$8,NOW())',[entity().id,randomUUID(),"adjustment",new Date("2026-01-01"),"UZS",randomUUID(),owned.userId,doc.id],"FinanceDocument_reversal_entity_fkey");expect(await records()).toEqual(before);}finally{await mockPrisma.financeDocument.deleteMany({where:{id:{in:[doc.id,local.id]}}});}});
it("line parent/bridge retarget and null bridge cannot bypass compound equality",async()=>{const line=await mockPrisma.financeJournalLine.findFirstOrThrow({where:{journalEntryId:journals.get(owned.companyId)![0]}});const before=await records();await rejected('UPDATE "FinanceJournalLine" SET "journalEntryId"=$1,"lineNumber"=99 WHERE id=$2',[journals.get(ids.organizations.transAsiaDe)![0],line.id],"FinanceJournalLine_journal_entity_fkey");await rejected('UPDATE "FinanceJournalLine" SET "legalEntityId"=NULL WHERE id=$1',[line.id],"FinanceJournalLine_entity_required_check","23514");await rejected('INSERT INTO "FinanceJournalLine" ("journalEntryId","lineNumber","accountId",currency,"fxRate") VALUES ($1,99,$2,$3,1)',[journals.get(owned.companyId)![0],accounts.get(owned.companyId),"UZS"],"FinanceJournalLine_entity_required_check","23514");expect(await records()).toEqual(before);});
it("document reversal update and linked-document entity retarget are rejected",async()=>{const original=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(owned.companyId)![0]}});const foreign=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(ids.organizations.unrelated)![0]}});const before=await records();await rejected('UPDATE "FinanceDocument" SET "reversalOfId"=$1 WHERE id=$2',[foreign.documentId,original.documentId],"FinanceDocument_reversal_entity_fkey");await rejected('UPDATE "FinanceDocument" SET "legalEntityId"=$1,"documentNumber"=$3,"idempotencyKey"=$4 WHERE id=$2',[foreign.legalEntityId,original.documentId,randomUUID(),randomUUID()],"FinanceJournalEntry_document_entity_fkey");expect(await records()).toEqual(before);});
function command(){return{companyId:owned.companyId,actorUserId:owned.userId,idempotencyKey:randomUUID(),documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",fxRate:"1",lines:[{accountId:accounts.get(owned.companyId)!,debitAmount:"0.1000",creditAmount:"0"},{accountId:accounts.get(owned.companyId)!,debitAmount:"0",creditAmount:"0.1000"}]};}
it("valid draft remains balanced while manual posting/reversal require independent acceptance",async()=>{await mockPrisma.financeFiscalPeriod.create({data:{legalEntityId:entity().id,fiscalYear:2026,periodNumber:1,name:"Synthetic open",startDate:new Date("2026-01-01"),endDate:new Date("2026-01-31")}});const draft:any=await repo.createDraftJournal(command(),actor(owned));const storedLines=await mockPrisma.financeJournalLine.findMany({where:{journalEntryId:draft.id}});expect(storedLines.every(l=>l.legalEntityId===entity().id)).toBe(true);expect(draft.totalDebitBase.eq(draft.totalCreditBase)).toBe(true);const before=await records();await expect(repo.postJournal(actor(owned),draft.id)).rejects.toMatchObject({code:"FINANCE_MANUAL_APPROVAL_REQUIRED"});await expect(repo.reverseJournal({companyId:owned.companyId,actorUserId:owned.userId,journalId:draft.id,postingDate:new Date("2026-01-01"),reason:"Synthetic reversal",idempotencyKey:randomUUID()},actor(owned))).rejects.toMatchObject({code:"FINANCE_MANUAL_APPROVAL_REQUIRED"});expect(await records()).toEqual(before);});
it("late outbox failure rolls back draft, lines, sequence and audit",async()=>{const before=await records(),numbers=await mockPrisma.financeNumberSequence.findMany();await pool.query(`CREATE FUNCTION public.cp_journal_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic journal outbox failure'; END $$;CREATE TRIGGER cp_journal_fail BEFORE INSERT ON "FinanceDomainEventOutbox" FOR EACH ROW EXECUTE FUNCTION public.cp_journal_fail();`);try{await expect(repo.createDraftJournal(command(),actor(owned))).rejects.toThrow("synthetic journal outbox failure");}finally{await pool.query('DROP TRIGGER cp_journal_fail ON "FinanceDomainEventOutbox"; DROP FUNCTION public.cp_journal_fail();');}expect(await records()).toEqual(before);expect(await mockPrisma.financeNumberSequence.findMany()).toEqual(numbers);});
it("compound catalog matches target columns and keeps historical certification unresolved",async()=>{const names=["FinanceDocument_reversal_entity_fkey","FinanceJournalEntry_document_entity_fkey","FinanceJournalEntry_reversal_entity_fkey","FinanceJournalLine_journal_entity_fkey","FinanceJournalLine_account_entity_fkey","FinanceJournalLine_entity_required_check"];const result=await pool.query('SELECT conname,convalidated,pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conname = ANY($1) ORDER BY conname',[names]);expect(result.rows).toHaveLength(6);for(const r of result.rows){expect(r.convalidated).toBe(false);expect(r.definition).toContain('"legalEntityId"');}expect(result.rows.find(r=>r.conname==="FinanceJournalLine_account_entity_fkey").definition).toContain('FOREIGN KEY ("accountId", "legalEntityId") REFERENCES "FinanceAccount"(id, "legalEntityId")');});

it("foreign parent-key mutation waits for a valid line insert then rejects without audit/outbox effects",async()=>{const local=journals.get(owned.companyId)![0],foreignDoc=await draftDocument(ids.organizations.transAsiaDe),before=await records();const child=await pool.connect(),parent=await pool.connect();let lineId:string|undefined;try{await child.query("BEGIN");await parent.query("BEGIN");const inserted=await child.query('INSERT INTO "FinanceJournalLine" ("legalEntityId","journalEntryId","lineNumber","accountId",currency,"fxRate") VALUES ($1,$2,98,$3,$4,1) RETURNING id',[entity().id,local,accounts.get(owned.companyId),"UZS"]);lineId=inserted.rows[0].id;await parent.query('INSERT INTO "FinanceAuditEvent" ("legalEntityId",action) VALUES ($1,$2)',[entity().id,"synthetic-competing-parent"]);await parent.query('INSERT INTO "FinanceDomainEventOutbox" ("legalEntityId","aggregateType","aggregateId","eventType","occurredAt","payloadJson","updatedAt") VALUES ($1,$2,$3,$4,NOW(),$5,NOW())',[entity().id,"synthetic-journal",local,"synthetic.competing",{}]);const pid=(await parent.query('SELECT pg_backend_pid() AS pid')).rows[0].pid;const pending=parent.query('UPDATE "FinanceJournalEntry" SET "legalEntityId"=$1,"documentId"=$2,"journalNumber"=$3 WHERE id=$4',[foreignDoc.legalEntityId,foreignDoc.id,randomUUID(),local]).then(()=>({accepted:true}),error=>({error}));let blocked=false;for(let attempt=0;attempt<40;attempt++){const activity:any[]=await mockPrisma.$queryRaw`SELECT wait_event_type FROM pg_stat_activity WHERE pid = ${pid}`;if(activity[0]?.wait_event_type==="Lock"){blocked=true;break;}await new Promise(resolve=>setTimeout(resolve,25));}expect(blocked).toBe(true);await child.query("COMMIT");const result:any=await pending;expect(result.error?.code).toBe("23503");expect(result.error?.constraint).toBe("FinanceJournalLine_journal_entity_fkey");await parent.query("ROLLBACK");const current=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:local}});expect(current.legalEntityId).toBe(entity().id);expect(current.totalDebitBase.eq(current.totalCreditBase)).toBe(true);}finally{await child.query("ROLLBACK");await parent.query("ROLLBACK");child.release();parent.release();if(lineId)await mockPrisma.financeJournalLine.delete({where:{id:lineId}});}expect(await records()).toEqual(before);await mockPrisma.financeDocument.delete({where:{id:foreignDoc.id}});});

it("manual legacy retry fields cannot substitute for independently accepted operation",async()=>{const before=await records();await expect(repo.reverseJournal({companyId:owned.companyId,actorUserId:owned.userId,journalId:journals.get(owned.companyId)![0],postingDate:new Date("2026-01-01"),reason:"Synthetic reversal",idempotencyKey:randomUUID(),approved:true,checkerUserId:ids.users.checker}as any,actor(owned))).rejects.toMatchObject({code:"FINANCE_MANUAL_APPROVAL_REQUIRED"});expect(await records()).toEqual(before);});
it("competing unapproved reversals both deny without effects",async()=>{const before=await records();const intent={companyId:owned.companyId,actorUserId:owned.userId,journalId:journals.get(owned.companyId)![0],postingDate:new Date("2026-01-01"),reason:"Synthetic reversal"};for(const result of await Promise.allSettled([repo.reverseJournal({...intent,idempotencyKey:randomUUID()},actor(owned)),repo.reverseJournal({...intent,idempotencyKey:randomUUID()},actor(owned))])){expect(result.status).toBe("rejected");expect((result as PromiseRejectedResult).reason.code).toBe("FINANCE_MANUAL_APPROVAL_REQUIRED");}expect(await records()).toEqual(before);});

it("draft receipt identical normalized retry returns original without business writes",async()=>{
  const c=command(),first:any=await repo.createDraftJournal(c,actor(owned)),before=await records();
  const retry={...c,fxRate:"1.0000",lines:c.lines.map(l=>({...l,debitAmount:l.debitAmount==="0"?"0.0000":"0.1",creditAmount:l.creditAmount==="0"?"0.0000":"0.1"}))};
  const result:any=await repo.createDraftJournal(retry,actor(owned));expect(result.id).toBe(first.id);expect(result.document).not.toHaveProperty("draftIntentHash");expect(await records()).toEqual(before);
  const doc=await mockPrisma.financeDocument.findUniqueOrThrow({where:{id:first.documentId}});
  expect(doc).toMatchObject({draftTenantId:owned.tenantId,draftCompanyId:owned.companyId,draftTenantMembershipId:owned.tenantMembershipId,draftCompanyMembershipId:owned.id,createdByUserId:owned.userId});expect(doc.draftIntentHash).toMatch(/^[a-f0-9]{64}$/);
});
it("draft receipt conflicts bind complete intent and selected actor",async()=>{
  const c=command();await repo.createDraftJournal(c,actor(owned));const before=await records();
  const checker=fixture.companyMemberships.find(m=>m.id===ids.companyMemberships.checkerTransAsiaUz)!;
  for(const changed of [{...c,description:"Changed"},{...c,metadata:{synthetic:"changed"}},{...c,postingDate:new Date("2026-01-02")},{...c,lines:c.lines.map(l=>({...l,debitAmount:l.debitAmount==="0"?"0":"0.10001",creditAmount:l.creditAmount==="0"?"0":"0.10001"}))}])await expect(repo.createDraftJournal(changed,actor(owned))).rejects.toMatchObject({code:"FINANCE_DRAFT_IDEMPOTENCY_CONFLICT"});
  await expect(repo.createDraftJournal({...c,actorUserId:checker.userId},actor(checker))).rejects.toMatchObject({code:"FINANCE_DRAFT_IDEMPOTENCY_CONFLICT"});
  await expect(repo.createDraftJournal({...c,companyId:ids.organizations.unrelated},actor(owned))).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);
});
it("draft receipt concurrent matching delivery creates one atomic result",async()=>{
  const c=command(),before=await records();const results:any[]=await Promise.all([1,2,3].map(()=>repo.createDraftJournal(c,actor(owned))));expect(new Set(results.map(r=>r.id)).size).toBe(1);
  const after=await records();expect(after.documents.length).toBe(before.documents.length+1);expect(after.journals.length).toBe(before.journals.length+1);expect(after.lines.length).toBe(before.lines.length+2);expect(after.audit).toBe(before.audit+1);expect(after.outbox).toBe(before.outbox+1);expect(results[0].totalDebitBase.eq(results[0].totalCreditBase)).toBe(true);
});
it("draft receipt competing conflicting deliveries accept exactly one intent",async()=>{
  const c=command(),before=await records();const results=await Promise.allSettled([repo.createDraftJournal({...c,description:"A"},actor(owned)),repo.createDraftJournal({...c,description:"B"},actor(owned))]);
  expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect((results.find(r=>r.status==="rejected") as PromiseRejectedResult).reason.code).toBe("FINANCE_DRAFT_IDEMPOTENCY_CONFLICT");
  const after=await records();expect(after.documents.length).toBe(before.documents.length+1);expect(after.journals.length).toBe(before.journals.length+1);expect(after.audit).toBe(before.audit+1);expect(after.outbox).toBe(before.outbox+1);
  const accepted:any=(results.find(r=>r.status==="fulfilled") as PromiseFulfilledResult<any>).value;expect(accepted.totalDebitBase.eq(accepted.totalCreditBase)).toBe(true);
});
it("draft receipt legacy unbound and incomplete keys cannot be adopted",async()=>{
  const legacy=await mockPrisma.financeDocument.findUniqueOrThrow({where:{id:(await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(owned.companyId)![0]}})).documentId}}),incomplete=await draftDocument(owned.companyId),before=await records();
  for(const doc of [legacy,incomplete])await expect(repo.createDraftJournal({...command(),idempotencyKey:doc.idempotencyKey},actor(owned))).rejects.toMatchObject({code:"FINANCE_DRAFT_IDEMPOTENCY_CONFLICT"});expect(await records()).toEqual(before);
});
it("draft receipt current suspension or removed scope denies retry without business effects",async()=>{
  const c=command();await repo.createDraftJournal(c,actor(owned));await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"suspended"}});let before=await records();
  try{await expect(repo.createDraftJournal(c,actor(owned))).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);}finally{await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"active"}});}
  await mockPrisma.membershipScope.deleteMany({where:{membershipId:owned.id,scopeType:"company"}});before=await records();try{await expect(repo.createDraftJournal(c,actor(owned))).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);}finally{await mockPrisma.membershipScope.create({data:{membershipId:owned.id,scopeType:"company",scopeRefId:owned.companyId}});}
});
it("draft receipt document binding and financial snapshot cannot be rewritten or attached historically",async()=>{
  const draft:any=await repo.createDraftJournal(command(),actor(owned)),before=await records();
  for(const sql of ['UPDATE "FinanceDocument" SET "draftCompanyMembershipId"=NULL WHERE id=$1','UPDATE "FinanceDocument" SET "totalAmount"=2 WHERE id=$1','UPDATE "FinanceDocument" SET "draftIntentHash"=NULL WHERE id=$1',`UPDATE "FinanceDocument" SET "idempotencyKey"='changed-key' WHERE id=$1`])await rejected(sql,[draft.documentId],"FinanceDocument_draft_immutable","23514");
  const legacy=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(owned.companyId)![0]}});await rejected('UPDATE "FinanceDocument" SET "draftIntentHash"=$2 WHERE id=$1',[legacy.documentId,"0".repeat(64)],"FinanceDocument_draft_immutable","23514");expect(await records()).toEqual(before);
});
it("draft receipt compound context constraints reject forged inserts with complete rollback",async()=>{
  const c=command(),draft:any=await repo.createDraftJournal(c,actor(owned)),doc:any=await mockPrisma.financeDocument.findUniqueOrThrow({where:{id:draft.documentId}}),before=await records();
  const checker=fixture.companyMemberships.find(m=>m.id===ids.companyMemberships.checkerTransAsiaUz)!;
  const other=fixture.companyMemberships.find(m=>m.companyId===ids.organizations.transAsiaDe)!;
  const foreign=fixture.companyMemberships.find(m=>m.companyId===ids.organizations.unrelated)!;
  const changes:[Record<string,unknown>,string,string][]=[
    [{draftCompanyId:other.companyId},"FinanceDocument_draft_entity_fkey","23503"],
    [{draftCompanyMembershipId:checker.id},"FinanceDocument_draft_company_fkey","23503"],
    [{draftTenantMembershipId:checker.tenantMembershipId},"FinanceDocument_draft_bridge_fkey","23503"],
    [{draftTenantId:foreign.tenantId,draftCompanyId:foreign.companyId},"FinanceDocument_draft_entity_fkey","23503"],
    [{draftTenantMembershipId:null},"FinanceDocument_draft_complete_check","23514"]
  ];
  for(const [change,constraint,code] of changes){const row={legalEntityId:doc.legalEntityId,documentNumber:randomUUID(),type:"manual_journal",documentDate:doc.documentDate,postingDate:doc.postingDate,currency:"UZS",totalAmount:"0.1",baseAmount:"0.1",fxRate:"1",idempotencyKey:randomUUID(),createdByUserId:owned.userId,draftIntentHash:doc.draftIntentHash,draftTenantId:doc.draftTenantId,draftCompanyId:doc.draftCompanyId,draftTenantMembershipId:doc.draftTenantMembershipId,draftCompanyMembershipId:doc.draftCompanyMembershipId,...change};const keys=Object.keys(row);await rejected('INSERT INTO "FinanceDocument" ('+keys.map(k=>'"'+k+'"').join(',')+',"updatedAt") VALUES ('+keys.map((_,i)=>'$'+(i+1)).join(',')+',NOW())',Object.values(row),constraint,code);}expect(await records()).toEqual(before);
});
it("draft receipt catalog establishes selected compound targets, not historical certification",async()=>{
  const names=["FinanceDocument_draft_complete_check","FinanceDocument_draft_entity_fkey","FinanceDocument_draft_company_fkey","FinanceDocument_draft_bridge_fkey","FinanceDocument_draft_tenant_fkey"];
  const rows=(await pool.query('SELECT conname,convalidated,pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conname=ANY($1)',[names])).rows;expect(rows).toHaveLength(5);for(const row of rows)expect(row.convalidated).toBe(false);
  expect(rows.find(r=>r.conname==="FinanceDocument_draft_entity_fkey").definition).toContain('REFERENCES "FinanceLegalEntity"(id, "tenantId", "companyId")');
  expect(rows.find(r=>r.conname==="FinanceDocument_draft_bridge_fkey").definition).toContain('REFERENCES "CompanyMembership"(id, "tenantMembershipId", "userId", "tenantId")');
  expect((await pool.query("SELECT tgname FROM pg_trigger WHERE tgname='cp_protect_draft_intent' AND NOT tgisinternal")).rows).toHaveLength(1);
});
it("draft receipt rejects foreign accounts and caller ownership before draft/audit/outbox writes",async()=>{
  const before=await records();
  for(const company of [ids.organizations.transAsiaDe,ids.organizations.unrelated])await expect(repo.createDraftJournal({...command(),lines:command().lines.map(l=>({...l,accountId:accounts.get(company)!}))},actor(owned))).rejects.toMatchObject({code:"FINANCE_ACCOUNT_SCOPE_MISMATCH"});
  await expect(repo.createDraftJournal({...command(),draftTenantId:ids.tenants.unrelated}as any,actor(owned))).rejects.toMatchObject({code:"FINANCE_DRAFT_INTENT_INVALID"});expect(await records()).toEqual(before);
});

async function syntheticPostedReportRows(){let n=1;for(const e of fixture.financeLegalEntities){const journalId=journals.get(e.companyId)![0],amount="0."+(n++)+"000";await mockPrisma.$transaction(async tx=>{const j=await tx.financeJournalEntry.findUniqueOrThrow({where:{id:journalId}});await tx.financeDocument.update({where:{id:j.documentId},data:{status:"posted",totalAmount:amount,baseAmount:amount}});await tx.financeJournalEntry.update({where:{id:journalId},data:{status:"posted",totalDebitBase:amount,totalCreditBase:amount}});await tx.financeJournalLine.updateMany({where:{journalEntryId:journalId,lineNumber:1},data:{debitAmount:amount,debitBase:amount}});await tx.financeJournalLine.updateMany({where:{journalEntryId:journalId,lineNumber:2},data:{creditAmount:amount,creditBase:amount}});});}}
it("trial balance selected multi-tenant contexts retain company isolation and exact posted totals",async()=>{
  // Direct synthetic posted fixtures are not an approved manual execution workflow.
  await syntheticPostedReportRows();const before=await records();
  let n=1;for(const e of fixture.financeLegalEntities){const member=fixture.companyMemberships.find(m=>m.companyId===e.companyId&&m.userId===ids.users.multiTenant)!;const report:any=await repo.getTrialBalance(actor(member),new Date("2026-01-01"),new Date("2026-01-31"));expect(report.totalDebit.toString()).toBe("0."+n++);expect(report.totalCredit.eq(report.totalDebit)).toBe(true);expect(report.balanced).toBe(true);expect(report.rows).toHaveLength(1);expect(report.rows[0].account.id).toBe(accounts.get(e.companyId));expect(report.rows[0].account).not.toHaveProperty("metadataJson");}expect(await records()).toEqual(before);
});
it("trial balance current suspension and removed explicit scope deny without business effects",async()=>{
  await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"suspended"}});let before=await records();try{await expect(repo.getTrialBalance(actor(owned),new Date("2026-01-01"),new Date("2026-01-31"))).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);}finally{await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"active"}});}
  await mockPrisma.membershipScope.deleteMany({where:{membershipId:owned.id,scopeType:"company"}});before=await records();try{await expect(repo.getTrialBalance(actor(owned),new Date("2026-01-01"),new Date("2026-01-31"))).rejects.toMatchObject({code:"FINANCE_COMPANY_SCOPE_REQUIRED"});expect(await records()).toEqual(before);}finally{await mockPrisma.membershipScope.create({data:{membershipId:owned.id,scopeType:"company",scopeRefId:owned.companyId}});}
});
it("trial balance null or inactive ownership rejects instead of configuring financial state",async()=>{
  for(const change of [{tenantId:null},{isActive:false}]){await mockPrisma.financeLegalEntity.update({where:{id:entity().id},data:change});const before=await records();try{await expect(repo.getTrialBalance(actor(owned),new Date("2026-01-01"),new Date("2026-01-31"))).rejects.toMatchObject({code:"FINANCE_ENTITY_NOT_CONFIGURED"});expect(await records()).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:entity().id},data:{tenantId:owned.tenantId,isActive:true}});}}
});
it("trial balance includes reversals consistently while date filters exclude other periods and drafts",async()=>{
  const id=journals.get(owned.companyId)![0];const journal=await mockPrisma.financeJournalEntry.update({where:{id},data:{status:"reversed"}});await mockPrisma.financeDocument.update({where:{id:journal.documentId},data:{status:"reversed"}});const before=await records();const included:any=await repo.getTrialBalance(actor(owned),new Date("2026-01-01"),new Date("2026-01-31"));expect(included.totalDebit.toString()).toBe("0.1");expect(included.balanced).toBe(true);const empty:any=await repo.getTrialBalance(actor(owned),new Date("2026-02-01"),new Date("2026-02-28"));expect(empty.rows).toEqual([]);expect(empty.totalDebit.toString()).toBe("0");expect(await records()).toEqual(before);
});
it("trial balance rejects conflicting document lifecycle without financial read side effects",async()=>{
  const j=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(owned.companyId)![0]}});const doc=await mockPrisma.financeDocument.findUniqueOrThrow({where:{id:j.documentId}});await mockPrisma.financeDocument.update({where:{id:doc.id},data:{status:"draft"}});const before=await records();try{await expect(repo.getTrialBalance(actor(owned),new Date("2026-01-01"),new Date("2026-01-31"))).rejects.toMatchObject({code:"FINANCE_REPORT_INTEGRITY_REJECTED"});expect(await records()).toEqual(before);}finally{await mockPrisma.financeDocument.update({where:{id:doc.id},data:{status:doc.status}});}
});
it("trial balance large PostgreSQL aggregates retain exact numeric scale beyond Decimal default precision",async()=>{
  for(let i=0;i<2;i++)await mockPrisma.$transaction(async tx=>{const amount="9999999999999999.9999";const doc=await tx.financeDocument.create({data:{legalEntityId:entity().id,documentNumber:randomUUID(),type:"manual_journal",status:"posted",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:amount,baseAmount:amount,fxRate:"1",idempotencyKey:randomUUID(),createdByUserId:owned.userId}});await tx.financeJournalEntry.create({data:{legalEntityId:entity().id,documentId:doc.id,journalNumber:randomUUID(),status:"posted",postingDate:new Date("2026-01-01"),totalDebitBase:amount,totalCreditBase:amount,lines:{create:[{legalEntityId:entity().id,lineNumber:1,accountId:accounts.get(owned.companyId)!,currency:"UZS",fxRate:"1",debitAmount:amount,debitBase:amount},{legalEntityId:entity().id,lineNumber:2,accountId:accounts.get(owned.companyId)!,currency:"UZS",fxRate:"1",creditAmount:amount,creditBase:amount}]}}});});
  const before=await records();const report:any=await repo.getTrialBalance(actor(owned),new Date("2026-01-01"),new Date("2026-01-31"));expect(report.totalDebit.toString()).toBe("20000000000000000.0998");expect(report.totalCredit.toString()).toBe("20000000000000000.0998");expect(report.rows[0].debit.toString()).toBe("20000000000000000.0998");expect(report.balanced).toBe(true);expect(await records()).toEqual(before);
});

const postingRules=new Map<string,string[]>();
async function ruleRecords(){return {...await records(),rules:await mockPrisma.financePostingRule.findMany({orderBy:{id:"asc"}}),ruleLines:await mockPrisma.financePostingRuleLine.findMany({orderBy:{id:"asc"}})};}
it("posting rule selected contexts isolate two tenants and same-tenant companies with safe related accounts",async()=>{
  for(const e of fixture.financeLegalEntities){const rows=[];for(const n of [1,2]){const r=await mockPrisma.financePostingRule.create({data:{legalEntityId:e.id,code:"synthetic."+n,name:"Synthetic",sourceType:"payment",eventType:"payment.succeeded",conditionsJson:{private:"SYNTHETIC-CANARY"},createdAt:new Date("2026-01-0"+n),lines:{create:[{lineNumber:1,side:"debit",accountId:accounts.get(e.companyId)!,dimensionsJson:{private:"SYNTHETIC-CANARY"}},{lineNumber:2,side:"credit",accountId:accounts.get(e.companyId)!}]}}});rows.push(r.id);}postingRules.set(e.companyId,rows);}
  const before=await ruleRecords();for(const m of fixture.companyMemberships.filter(m=>m.userId===ids.users.multiTenant)){const list:any=await repo.listPostingRules(actor(m),{limit:10});expect(list.items.map((r:any)=>r.id)).toEqual([...postingRules.get(m.companyId)!].reverse());for(const r of list.items){const detail:any=await repo.getPostingRule(actor(m),r.id);expect(detail.lines).toHaveLength(2);expect(detail).not.toHaveProperty("conditionsJson");for(const l of detail.lines){expect(l.account.id).toBe(accounts.get(m.companyId));expect(l).not.toHaveProperty("dimensionsJson");}}}expect(await ruleRecords()).toEqual(before);
});
it("posting rule foreign detail/cursor deny and owned cursor pages without business writes",async()=>{const before=await ruleRecords();for(const company of [ids.organizations.transAsiaDe,ids.organizations.unrelated]){const id=postingRules.get(company)![0];await expect(repo.getPostingRule(actor(owned),id)).rejects.toMatchObject({statusCode:404});await expect(repo.listPostingRules(actor(owned),{limit:1,cursor:id})).rejects.toMatchObject({statusCode:404});}const first:any=await repo.listPostingRules(actor(owned),{limit:1});const second:any=await repo.listPostingRules(actor(owned),{limit:1,cursor:first.pageInfo.nextCursor});expect(second.items.map((r:any)=>r.id)).toEqual([postingRules.get(owned.companyId)![0]]);expect(await ruleRecords()).toEqual(before);});
it.each([ids.organizations.transAsiaDe,ids.organizations.unrelated])("posting rule foreign account insert/update rejects atomically: %s",async company=>{const id=postingRules.get(owned.companyId)![0],line=await mockPrisma.financePostingRuleLine.findFirstOrThrow({where:{postingRuleId:id}}),before=await ruleRecords();await rejected('UPDATE "FinancePostingRuleLine" SET "accountId"=$1 WHERE id=$2',[accounts.get(company)!,line.id],"FinancePostingRuleLine_account_entity_fkey");await rejected('INSERT INTO "FinancePostingRuleLine" ("postingRuleId","legalEntityId","lineNumber",side,"accountId","updatedAt") VALUES ($1,$2,99,$3,$4,NOW())',[id,entity().id,"debit",accounts.get(company)!],"FinancePostingRuleLine_account_entity_fkey");expect(await ruleRecords()).toEqual(before);});
it.each([ids.organizations.transAsiaDe,ids.organizations.unrelated])("posting rule foreign parent insert/update rejects atomically: %s",async company=>{const line=await mockPrisma.financePostingRuleLine.findFirstOrThrow({where:{postingRuleId:postingRules.get(owned.companyId)![0]}}),before=await ruleRecords();await rejected('UPDATE "FinancePostingRuleLine" SET "postingRuleId"=$1,"lineNumber"=99 WHERE id=$2',[postingRules.get(company)![0],line.id],"FinancePostingRuleLine_rule_entity_fkey");await rejected('INSERT INTO "FinancePostingRuleLine" ("postingRuleId","legalEntityId","lineNumber",side,"accountId","updatedAt") VALUES ($1,$2,99,$3,$4,NOW())',[postingRules.get(company)![0],entity().id,"debit",accounts.get(owned.companyId)!],"FinancePostingRuleLine_rule_entity_fkey");expect(await ruleRecords()).toEqual(before);});
it("posting rule null bridge insert/update rejects and catalog retains historical certification gaps",async()=>{const id=postingRules.get(owned.companyId)![0],line=await mockPrisma.financePostingRuleLine.findFirstOrThrow({where:{postingRuleId:id}}),before=await ruleRecords();await rejected('UPDATE "FinancePostingRuleLine" SET "legalEntityId"=NULL WHERE id=$1',[line.id],"FinancePostingRuleLine_entity_required_check","23514");await rejected('INSERT INTO "FinancePostingRuleLine" ("postingRuleId","lineNumber",side,"accountId","updatedAt") VALUES ($1,99,$2,$3,NOW())',[id,"debit",line.accountId],"FinancePostingRuleLine_entity_required_check","23514");const catalog=await pool.query('SELECT conname,convalidated FROM pg_constraint WHERE conname LIKE $1',["FinancePostingRuleLine%entity%"]);expect(catalog.rows).toHaveLength(3);expect(catalog.rows.every(r=>r.convalidated===false)).toBe(true);expect(await ruleRecords()).toEqual(before);});
it("posting rule null/inactive ownership and missing stored scope fail closed; configuration remains unaccepted",async()=>{const id=postingRules.get(owned.companyId)![0];for(const data of [{tenantId:null},{isActive:false}]){await mockPrisma.financeLegalEntity.update({where:{id:entity().id},data});const before=await ruleRecords();try{expect((await repo.listPostingRules(actor(owned),{limit:10})as any).items).toEqual([]);await expect(repo.getPostingRule(actor(owned),id)).rejects.toMatchObject({statusCode:404});expect(await ruleRecords()).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:entity().id},data:{tenantId:owned.tenantId,isActive:true}});}}
  const before=await ruleRecords();const intent:any={companyId:owned.companyId,actorUserId:owned.userId};await expect(repo.createPostingRule(intent,actor(owned))).rejects.toMatchObject({code:"FINANCE_POSTING_RULE_APPROVAL_REQUIRED"});await expect(repo.createPostingRuleVersion({...intent,ruleId:id},actor(owned))).rejects.toMatchObject({code:"FINANCE_POSTING_RULE_APPROVAL_REQUIRED"});await expect(repo.changePostingRuleStatus(owned.companyId,id,owned.userId,"inactive",actor(owned))).rejects.toMatchObject({code:"FINANCE_POSTING_RULE_APPROVAL_REQUIRED"});expect(await ruleRecords()).toEqual(before);
  await mockPrisma.membershipScope.deleteMany({where:{membershipId:owned.id,scopeType:"company"}});try{await expect(repo.listPostingRules(actor(owned),{limit:10})).rejects.toMatchObject({statusCode:403});expect(await ruleRecords()).toEqual(before);}finally{await mockPrisma.membershipScope.create({data:{membershipId:owned.id,scopeType:"company",scopeRefId:owned.companyId}});}
});

it("posting rule competing parent retarget waits for valid insertion then rejects atomically",async()=>{
  const rule=await mockPrisma.financePostingRule.create({data:{legalEntityId:entity().id,code:randomUUID(),name:"Synthetic lock",sourceType:"payment",eventType:"synthetic"}}),before=await ruleRecords();
  const child=await pool.connect(),parent=await pool.connect();let lineId:string|undefined;
  try{await child.query("BEGIN");await parent.query("BEGIN");lineId=(await child.query('INSERT INTO "FinancePostingRuleLine" ("postingRuleId","legalEntityId","lineNumber",side,"accountId","updatedAt") VALUES ($1,$2,1,$3,$4,NOW()) RETURNING id',[rule.id,entity().id,"debit",accounts.get(owned.companyId)])).rows[0].id;
    await parent.query('INSERT INTO "FinanceAuditEvent" ("legalEntityId",action) VALUES ($1,$2)',[entity().id,"synthetic-rule-race"]);
    await parent.query('INSERT INTO "FinanceDomainEventOutbox" ("legalEntityId","aggregateType","aggregateId","eventType","occurredAt","payloadJson","updatedAt") VALUES ($1,$2,$3,$4,NOW(),$5,NOW())',[entity().id,"synthetic-rule",rule.id,"synthetic.race",{}]);
    const pid=(await parent.query('SELECT pg_backend_pid() AS pid')).rows[0].pid;
    const pending=parent.query('UPDATE "FinancePostingRule" SET "legalEntityId"=$1 WHERE id=$2',[entity(ids.organizations.transAsiaDe).id,rule.id]).then(()=>({accepted:true}),error=>({error}));
    let blocked=false;for(let i=0;i<40;i++){const activity:any[]=await mockPrisma.$queryRaw`SELECT wait_event_type FROM pg_stat_activity WHERE pid = ${pid}`;if(activity[0]?.wait_event_type==="Lock"){blocked=true;break;}await new Promise(resolve=>setTimeout(resolve,25));}expect(blocked).toBe(true);await child.query("COMMIT");const result:any=await pending;expect(result.error?.code).toBe("23503");expect(result.error?.constraint).toBe("FinancePostingRuleLine_rule_entity_fkey");await parent.query("ROLLBACK");
    expect((await mockPrisma.financePostingRule.findUniqueOrThrow({where:{id:rule.id}})).legalEntityId).toBe(entity().id);
    await mockPrisma.financePostingRuleLine.update({where:{id:lineId},data:{lineNumber:2}});
  }finally{await child.query("ROLLBACK");await parent.query("ROLLBACK");child.release();parent.release();if(lineId)await mockPrisma.financePostingRuleLine.delete({where:{id:lineId}});}
  expect(await ruleRecords()).toEqual(before);await mockPrisma.financePostingRule.delete({where:{id:rule.id}});
});
