jest.mock("../../src/config/prismaClient", () => ({ __esModule: true, default: new Proxy({}, { get: (_target, name) => { const value = (mockPrisma as any)[name]; return typeof value === "function" ? value.bind(mockPrisma) : value; } }) }));
// Domain envelope only is mocked to guarantee no Redis/logger import; actual transactional outbox writes run.
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents", () => ({ buildCargoPilotDomainEvent: (input: any) => ({ ...input, id: require("crypto").randomUUID(), occurredAt: new Date().toISOString(), schemaVersion: 1 }) }));
import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { randomUUID } from "crypto";
import { createTenantDemoFixture, TENANT_DEMO_IDS as ids } from "../../src/modules/tenancy/demo-fixtures";
import { persistTenantDemoFixture } from "../tenancy/postgres-fixture.persistence";
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"disposable-finance",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
import { prismaFinanceRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance.repository";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable legal entity identity required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing PostgreSQL target");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});let mockPrisma:PrismaClient;const fixture=createTenantDemoFixture();
function actor(m:any){return {id:m.userId,tenantId:m.tenantId,tenantMembershipId:m.tenantMembershipId,companyId:m.companyId,companyMembershipId:m.id,membershipId:m.id} as any;}
const owned=fixture.companyMemberships.find(m=>m.id===ids.companyMemberships.makerTransAsiaUz)!;
async function business(){return {entities:await mockPrisma.financeLegalEntity.findMany({orderBy:{id:"asc"}}),audit:await mockPrisma.financeAuditEvent.count(),outbox:await mockPrisma.financeDomainEventOutbox.count()};}
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{client.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});for(const key of ["finance.periods.read"])await mockPrisma.permission.create({data:{key,resource:"synthetic-finance",action:key}});for(const m of fixture.companyMemberships){const role=await mockPrisma.role.create({data:{companyId:m.companyId,code:randomUUID(),name:"Synthetic Finance"}});for(const key of ["finance.periods.read"]){const permission=await mockPrisma.permission.findUniqueOrThrow({where:{key}});await mockPrisma.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}});}await mockPrisma.membershipRole.create({data:{membershipId:m.id,roleId:role.id}});await mockPrisma.membershipScope.create({data:{membershipId:m.id,scopeType:"company",scopeRefId:m.companyId}});}});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});
const periods=new Map<string,string[]>();
beforeAll(async()=>{for(const entity of fixture.financeLegalEntities){const ids=[];for(const month of [1,2]){const row=await mockPrisma.financeFiscalPeriod.create({data:{legalEntityId:entity.id,fiscalYear:2026,periodNumber:month,name:"Synthetic period",startDate:new Date(`2026-0${month}-01`),endDate:new Date(`2026-0${month}-28`),status:month===1?"closed":"open",closedByUserId:month===1?owned.userId:null,closedAt:month===1?new Date("2026-02-01"):null}});ids.push(row.id);}periods.set(entity.companyId,ids);}});
async function records(){return {periods:await mockPrisma.financeFiscalPeriod.findMany({orderBy:{id:"asc"}}),...await business()};}
it("same user in two tenants and two same-tenant companies reads only selected periods with safe projection",async()=>{const before=await records();for(const membership of fixture.companyMemberships.filter(m=>m.userId===ids.users.multiTenant)){const result:any=await repo.listPeriods(actor(membership),{limit:10});expect(result.items.map((r:any)=>r.id)).toEqual([...periods.get(membership.companyId)!].reverse());for(const row of result.items){expect(row).not.toHaveProperty("closedByUserId");expect(row).not.toHaveProperty("reopenedByUserId");expect(row).not.toHaveProperty("legalEntity");}}expect(await records()).toEqual(before);});
it("owned date/id cursor paginates correctly and foreign cursor denies without mutations",async()=>{const before=await records();const first:any=await repo.listPeriods(actor(owned),{limit:1});expect(first.pageInfo).toMatchObject({hasMore:true,nextCursor:periods.get(owned.companyId)![1]});const next:any=await repo.listPeriods(actor(owned),{limit:1,cursor:first.pageInfo.nextCursor});expect(next.items.map((r:any)=>r.id)).toEqual([periods.get(owned.companyId)![0]]);await expect(repo.listPeriods(actor(owned),{limit:1,cursor:periods.get(ids.organizations.unrelated)![1]})).rejects.toMatchObject({statusCode:404});expect(await records()).toEqual(before);});
it("legacy null-owned legal entity hides periods without configuration changes",async()=>{const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{tenantId:null}});const before=await records();try{expect(await repo.listPeriods(actor(owned),{limit:10})).toMatchObject({items:[]});expect(await records()).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{tenantId:owned.tenantId}});}});
it("inactive legal entity hides periods and makes its cursor inaccessible",async()=>{const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{isActive:false}});const before=await records();try{expect(await repo.listPeriods(actor(owned),{limit:10})).toMatchObject({items:[]});await expect(repo.listPeriods(actor(owned),{limit:10,cursor:periods.get(owned.companyId)![0]})).rejects.toMatchObject({statusCode:404});expect(await records()).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{isActive:true}});}});
it("fresh membership revocation denies even after a prior authorized cached read",async()=>{await repo.listPeriods(actor(owned),{limit:10});await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"suspended"}});const before=await records();try{await expect(repo.listPeriods(actor(owned),{limit:10})).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);}finally{await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"active"}});}});
it("loss of explicit company scope denies without changing periods or configuration",async()=>{await mockPrisma.membershipScope.deleteMany({where:{membershipId:owned.id,scopeType:"company"}});const before=await records();try{await expect(repo.listPeriods(actor(owned),{limit:10})).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);}finally{await mockPrisma.membershipScope.create({data:{membershipId:owned.id,scopeType:"company",scopeRefId:owned.companyId}});}});
