jest.mock("../../src/config/prismaClient", () => ({ __esModule: true, default: new Proxy({}, { get: (_target, name) => { const value = (mockPrisma as any)[name]; return typeof value === "function" ? value.bind(mockPrisma) : value; } }) }));
// Domain envelope only is mocked to guarantee no Redis/logger import; actual transactional outbox writes run.
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents", () => ({ buildCargoPilotDomainEvent: (input: any) => ({ ...input, id: require("crypto").randomUUID(), occurredAt: new Date().toISOString(), schemaVersion: 1 }) }));
import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { randomUUID } from "crypto";
import { createTenantDemoFixture, TENANT_DEMO_IDS as ids } from "../../src/modules/tenancy/demo-fixtures";
import { persistTenantDemoFixture } from "../tenancy/postgres-fixture.persistence";
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"disposable-finance",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
import { prismaFinanceRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance.repository";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable legal entity identity required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing PostgreSQL target");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});let mockPrisma:PrismaClient;const fixture=createTenantDemoFixture();
function actor(m:any){return {id:m.userId,tenantId:m.tenantId,tenantMembershipId:m.tenantMembershipId,companyId:m.companyId,companyMembershipId:m.id,membershipId:m.id} as any;}
const owned=fixture.companyMemberships.find(m=>m.id===ids.companyMemberships.makerTransAsiaUz)!;
async function business(){return {entities:await mockPrisma.financeLegalEntity.findMany({orderBy:{id:"asc"}}),audit:await mockPrisma.financeAuditEvent.count(),outbox:await mockPrisma.financeDomainEventOutbox.count()};}
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{client.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});for(const key of ["finance.journals.read"])await mockPrisma.permission.create({data:{key,resource:"synthetic-finance",action:key}});for(const m of fixture.companyMemberships){const role=await mockPrisma.role.create({data:{companyId:m.companyId,code:randomUUID(),name:"Synthetic Finance"}});for(const key of ["finance.journals.read"]){const permission=await mockPrisma.permission.findUniqueOrThrow({where:{key}});await mockPrisma.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}});}await mockPrisma.membershipRole.create({data:{membershipId:m.id,roleId:role.id}});await mockPrisma.membershipScope.create({data:{membershipId:m.id,scopeType:"company",scopeRefId:m.companyId}});}});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});

const journals=new Map<string,string[]>(), accounts=new Map<string,string>();
beforeAll(async()=>{for(const entity of fixture.financeLegalEntities){const account=await mockPrisma.financeAccount.create({data:{legalEntityId:entity.id,code:"SYNTH",name:"Synthetic asset",type:"asset"}});accounts.set(entity.companyId,account.id);const rows=[];for(const n of [1,2]){const document=await mockPrisma.financeDocument.create({data:{legalEntityId:entity.id,documentNumber:"SYN-DOC-"+n,type:"manual_journal",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:"0.1000",baseAmount:"0.1000",fxRate:"1.0000000001",idempotencyKey:"synthetic-"+n,createdByUserId:owned.userId,metadataJson:{private:"SYNTHETIC-CANARY"}}});const row=await mockPrisma.financeJournalEntry.create({data:{legalEntityId:entity.id,documentId:document.id,journalNumber:"SYN-JRN-"+n,postingDate:new Date("2026-01-01"),createdAt:new Date("2026-01-0"+n),totalDebitBase:"0.1000",totalCreditBase:"0.1000",lines:{create:[{lineNumber:1,accountId:account.id,debitAmount:"0.1000",currency:"UZS",fxRate:"1.0000000001",debitBase:"0.1000",metadataJson:{private:"SYNTHETIC-CANARY"}},{lineNumber:2,accountId:account.id,creditAmount:"0.1000",currency:"UZS",fxRate:"1.0000000001",creditBase:"0.1000"}]}}});rows.push(row.id);}journals.set(entity.companyId,rows);}});
async function records(){return{...await business(),documents:await mockPrisma.financeDocument.findMany({orderBy:{id:"asc"}}),journals:await mockPrisma.financeJournalEntry.findMany({orderBy:{id:"asc"}}),lines:await mockPrisma.financeJournalLine.findMany({orderBy:{id:"asc"}})};}
it("selected context separates two tenants/three companies and safely preserves exact journal decimals",async()=>{const before=await records();for(const membership of fixture.companyMemberships.filter(m=>m.userId===ids.users.multiTenant)){const result:any=await repo.listJournals(actor(membership),{limit:10});expect(result.items.map((r:any)=>r.id)).toEqual([...journals.get(membership.companyId)!].reverse());for(const row of result.items){expect(row.document.totalAmount.toString()).toBe("0.1");expect(row.document.fxRate.toString()).toBe("1.0000000001");expect(row).not.toHaveProperty("postedByUserId");expect(row.document).not.toHaveProperty("metadataJson");const detail:any=await repo.getJournal(actor(membership),row.id);expect(detail.lines).toHaveLength(2);expect(detail._count.lines).toBe(2);for(const line of detail.lines){expect(line.account.id).toBe(accounts.get(membership.companyId));expect(line).not.toHaveProperty("metadataJson");expect(line).not.toHaveProperty("customerEntityId");}}}expect(await records()).toEqual(before);});
it("owned cursor paginates and foreign cursor/detail reject without configuration or business changes",async()=>{const before=await records();const first:any=await repo.listJournals(actor(owned),{limit:1});const next:any=await repo.listJournals(actor(owned),{limit:1,cursor:first.pageInfo.nextCursor});expect(next.items.map((r:any)=>r.id)).toEqual([journals.get(owned.companyId)![0]]);for(const company of [ids.organizations.unrelated,ids.organizations.transAsiaDe]){const foreign=journals.get(company)![0];await expect(repo.getJournal(actor(owned),foreign)).rejects.toMatchObject({statusCode:404});await expect(repo.listJournals(actor(owned),{limit:1,cursor:foreign})).rejects.toMatchObject({statusCode:404});}expect(await records()).toEqual(before);});
it.each(["document","account","reversal"] as const)("foreign-tenant %s nested reference is hidden; database acceptance remains an integrity gap",async relationship=>{await inconsistent(relationship,ids.organizations.unrelated);});
it.each(["document","account","reversal"] as const)("same-tenant foreign-company %s nested reference is hidden",async relationship=>{await inconsistent(relationship,ids.organizations.transAsiaDe);});
async function inconsistent(relationship:string,company:string){const id=journals.get(owned.companyId)![0],foreign=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(company)![0]}});const line=await mockPrisma.financeJournalLine.findFirstOrThrow({where:{journalEntryId:id,lineNumber:1}});const original=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id}});let detachedDocument:string|undefined;if(relationship==="document"){const doc=await mockPrisma.financeDocument.create({data:{legalEntityId:foreign.legalEntityId,documentNumber:randomUUID(),type:"manual_journal",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:"0.1000",baseAmount:"0.1000",fxRate:"1",idempotencyKey:randomUUID(),createdByUserId:owned.userId}});detachedDocument=doc.id;await mockPrisma.financeJournalEntry.update({where:{id},data:{documentId:doc.id}});}else if(relationship==="account")await mockPrisma.financeJournalLine.update({where:{id:line.id},data:{accountId:accounts.get(company)!}});else await mockPrisma.financeJournalEntry.update({where:{id},data:{reversalOfId:foreign.id}});const before=await records();try{const list:any=await repo.listJournals(actor(owned),{limit:10});expect(list.items.map((r:any)=>r.id)).not.toContain(id);await expect(repo.getJournal(actor(owned),id)).rejects.toMatchObject({statusCode:404});await expect(repo.listJournals(actor(owned),{limit:10,cursor:id})).rejects.toMatchObject({statusCode:404});expect(await records()).toEqual(before);}finally{if(relationship==="account")await mockPrisma.financeJournalLine.update({where:{id:line.id},data:{accountId:line.accountId}});else await mockPrisma.financeJournalEntry.update({where:{id},data:relationship==="document"?{documentId:original.documentId}:{reversalOfId:null}});if(detachedDocument)await mockPrisma.financeDocument.delete({where:{id:detachedDocument}});}}
it("null/inactive finance ownership hides journals without read-driven configuration",async()=>{const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;for(const data of [{tenantId:null},{isActive:false}]){await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data});const before=await records();try{expect(await repo.listJournals(actor(owned),{limit:10})).toMatchObject({items:[]});await expect(repo.getJournal(actor(owned),journals.get(owned.companyId)![0])).rejects.toMatchObject({statusCode:404});expect(await records()).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{tenantId:owned.tenantId,isActive:true}});}}});
it("current suspended membership denies previously authorized journal reads",async()=>{await repo.listJournals(actor(owned),{limit:10});await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"suspended"}});const before=await records();try{await expect(repo.getJournal(actor(owned),journals.get(owned.companyId)![0])).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);}finally{await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"active"}});}});
