jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"test",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents",()=>({buildCargoPilotDomainEvent:jest.fn()}));
jest.mock("../../src/modules/identity-access/access-control",()=>({loadAccessSnapshot:jest.fn(),hasAnyPermissionSync:jest.fn(()=>true)}));
jest.mock("../../src/modules/identity-access/transport/fastify-auth",()=>({fastifyAuth:()=>async(request:any)=>{request.user=actor;}}));
import Fastify from "fastify";
import { database } from "./fixtures";
import { loadAccessSnapshot } from "../../src/modules/identity-access/access-control";
import { prismaFinanceDocumentsRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance-documents.repository";
import { FinanceDocumentsService } from "../../src/modules/finance-core/application/finance-documents.service";
import routes from "../../src/modules/finance-core/transport/fastify-routes";



import { Prisma } from "@prisma/client";
const actor:any={id:"u",tenantId:"t",tenantMembershipId:"tm",companyId:"c",companyMembershipId:"cm",membershipId:"cm"},snapshot:any={...actor,userId:"u",permissionCodes:["finance.settlements.read"],scopes:[{scopeType:"company",scopeRefId:"c"}]},id="11111111-1111-4111-8111-111111111111";
const row={id,periodEnd:new Date("2026-01-01"),netAmount:new Prisma.Decimal("10000000000000.0001"),fxRate:new Prisma.Decimal("1.0000000001"),lines:[]};const service=new FinanceDocumentsService(repo,{} as any);
beforeEach(()=>{jest.clearAllMocks();jest.mocked(loadAccessSnapshot).mockResolvedValue(snapshot);database.membershipScope.findFirst.mockReset().mockResolvedValue({id:"scope"});database.financeLegalEntity.findFirst.mockReset().mockResolvedValue({id:"entity"});database.paymentProviderConfig.findMany.mockReset().mockResolvedValue([{id:"config",provider:"CLICK",environment:"TEST"}]);database.financeProviderSettlement.findMany.mockReset().mockResolvedValue([row]);database.financeProviderSettlement.findFirst.mockReset().mockResolvedValue(row);});
afterEach(()=>{expect(database.$transaction).not.toHaveBeenCalled();for(const model of ["financeProviderSettlement","paymentProviderConfig","financeAuditEvent","financeDomainEventOutbox"])for(const method of ["create","update","upsert","delete"])expect(database[model][method]).not.toHaveBeenCalled();});
it("reads repeat selected ownership and authoritative provider tuple with exact safe projections",async()=>{await service.listProviderSettlements(actor,{limit:10});const detail=await service.getProviderSettlement(actor,id);expect(detail.netAmount.toString()).toBe("10000000000000.0001");expect(detail.fxRate.toString()).toBe("1.0000000001");const q=database.financeProviderSettlement.findMany.mock.calls[0][0];expect(q.where.AND[0]).toMatchObject({companyId:"c",legalEntityId:"entity",legalEntity:{is:{tenantId:"t",companyId:"c",isActive:true}},OR:[{providerConfigId:"config",providerCode:"CLICK",environment:"TEST"}]});expect(database.paymentProviderConfig.findMany.mock.calls[0][0]).toMatchObject({where:{companyId:"c",company:{is:{tenantId:"t",isActive:true}}},select:{id:true,provider:true,environment:true},take:33});for(const key of ["metadataJson","payloadHash","externalReference","idempotencyKey","createdByUserId","providerConfigId"])expect(q.select).not.toHaveProperty(key);const selected=database.financeProviderSettlement.findFirst.mock.calls[0][0].select.lines.select;for(const key of ["orderId","paymentIntentId","paymentRefundId","externalTransactionId","description","metadataJson"])expect(selected).not.toHaveProperty(key);expect(loadAccessSnapshot).toHaveBeenCalledWith(expect.objectContaining({requireFresh:true}));});
it.each([null,{...actor,tenantId:null},{...actor,membershipId:"wrong"}])("missing context denies before protected reads",async a=>{await expect(repo.listProviderSettlements(a,{limit:10})).rejects.toMatchObject({statusCode:403});await expect(repo.getProviderSettlement(a,id)).rejects.toMatchObject({statusCode:403});expect(database.financeProviderSettlement.findFirst).not.toHaveBeenCalled();});
it.each([null,{...snapshot,permissionCodes:[]},{...snapshot,scopes:[]},{...snapshot,tenantId:"foreign"},{...snapshot,companyId:"foreign"}])("fresh revocation/permission/context mismatch fails closed",async value=>{jest.mocked(loadAccessSnapshot).mockResolvedValue(value);await expect(service.getProviderSettlement(actor,id)).rejects.toMatchObject({statusCode:403});});
it("stored scope removal denies",async()=>{database.membershipScope.findFirst.mockResolvedValue(null);await expect(repo.getProviderSettlement(actor,id)).rejects.toMatchObject({code:"FINANCE_COMPANY_SCOPE_REQUIRED"});});
it.each(["entity","provider"])("unbound %s hides data and rejects cursor",async missing=>{if(missing==="entity")database.financeLegalEntity.findFirst.mockResolvedValue(null);else database.paymentProviderConfig.findMany.mockResolvedValue([]);expect(await repo.listProviderSettlements(actor,{limit:10})).toMatchObject({items:[]});await expect(repo.getProviderSettlement(actor,id)).rejects.toMatchObject({statusCode:404});await expect(repo.listProviderSettlements(actor,{limit:10,cursor:id})).rejects.toMatchObject({statusCode:404});});
it("provider configuration overflow denies without querying documents",async()=>{database.paymentProviderConfig.findMany.mockResolvedValue(Array(33).fill({}));await expect(repo.listProviderSettlements(actor,{limit:10})).rejects.toMatchObject({code:"FINANCE_SETTLEMENT_PROVIDER_LIMIT"});expect(database.financeProviderSettlement.findMany).not.toHaveBeenCalled();});
it("owned keyset and foreign cursor deny preserve provider/status predicates",async()=>{database.financeProviderSettlement.findFirst.mockResolvedValueOnce(null);await expect(repo.listProviderSettlements(actor,{limit:1,cursor:id})).rejects.toMatchObject({statusCode:404});expect(database.financeProviderSettlement.findMany).not.toHaveBeenCalled();await repo.listProviderSettlements(actor,{limit:1,cursor:id,status:"submitted"});const q=database.financeProviderSettlement.findMany.mock.calls[0][0];expect(q.where.AND[0].status).toBe("submitted");expect(q.where.AND[1]).toEqual({OR:[{periodEnd:{lt:row.periodEnd}},{periodEnd:row.periodEnd,id:{lt:id}}]});});
it.each([{limit:0},{limit:101},{limit:10,cursor:"bad"},{limit:10,status:"bad"},{limit:10,companyId:"foreign"}])("invalid input denies",async page=>{await expect(repo.listProviderSettlements(actor,page as any)).rejects.toMatchObject({statusCode:400});});
it("detail overflow denies",async()=>{database.financeProviderSettlement.findFirst.mockResolvedValue({...row,lines:Array(5001).fill({})});await expect(repo.getProviderSettlement(actor,id)).rejects.toMatchObject({code:"FINANCE_SETTLEMENT_DETAIL_LIMIT"});});
it("list, cursor and detail require the complete configured child source graph",async()=>{
 await repo.listProviderSettlements(actor,{limit:1,cursor:id});await repo.getProviderSettlement(actor,id);
 for(const call of [...database.financeProviderSettlement.findMany.mock.calls,...database.financeProviderSettlement.findFirst.mock.calls]){
  const where=call[0].where.AND[0].OR[0].lines.every;
  expect(where).toMatchObject({legalEntityId:"entity",tenantId:"t",companyId:"c",providerConfigId:"config",currency:{not:null},ownedHeader:{is:{companyId:"c",legalEntityId:"entity",providerConfigId:"config"}}});
  expect(where.AND[0].OR).toContainEqual({type:"payment",paymentIntentId:{not:null},paymentRefundId:null});
 }
});
it("HTTP read consumers send selected context and preserve envelopes",async()=>{const app=Fastify();await app.register(routes);try{expect((await app.inject({method:"GET",url:"/provider-settlements?companyId=foreign"})).statusCode).toBe(400);expect((await app.inject({method:"GET",url:"/provider-settlements?limit=10"})).json().items[0].id).toBe(id);expect((await app.inject({method:"GET",url:"/provider-settlements/"+id})).json().netAmount).toBe("10000000000000.0001");}finally{await app.close();}},15000);
