import { Prisma } from "@prisma/client";
import { projectFinanceSubledgerEvent } from "../../src/modules/finance-core/infrastructure/finance-subledger.projector";
import { normalizeFinanceSourceEvent } from "../../src/modules/finance-core/domain/source-event";
const event=normalizeFinanceSourceEvent({sourceEventId:"synthetic-payable",companyId:"company",sourceType:"payable",eventType:"payable.payment_executed",sourceId:"line",occurredAt:"2026-01-01T00:00:00Z",currency:"UZS",fxRate:"1",amounts:{payable_amount:"0.1000"},dimensions:{},attributes:{},metadata:{payableItemId:"payable",paymentRunLineId:"line"}});
let tx:any;
beforeEach(()=>{tx={$queryRaw:jest.fn(async()=>[]),financeLegalEntity:{findFirst:jest.fn(async()=>({tenantId:"tenant"}))},financePayableItem:{findFirst:jest.fn(async()=>({id:"payable",currency:"UZS",originalAmount:new Prisma.Decimal("0.1000"),outstandingAmount:new Prisma.Decimal("0.1000")})),update:jest.fn()},financePaymentRunLine:{findFirst:jest.fn(async()=>({id:"line",amount:new Prisma.Decimal("0.1000")})),update:jest.fn()},financePayableAllocation:{create:jest.fn()}};});
function noWrites(){expect(tx.financePayableItem.update).not.toHaveBeenCalled();expect(tx.financePaymentRunLine.update).not.toHaveBeenCalled();expect(tx.financePayableAllocation.create).not.toHaveBeenCalled();}
it("private projection derives bridge from entity and requires executed owned parent before exact allocation",async()=>{await projectFinanceSubledgerEvent(tx,"entity",event);expect(tx.financePaymentRunLine.findFirst.mock.calls[0][0].where).toMatchObject({id:"line",legalEntityId:"entity",payableItemId:"payable",status:"executed",accountingSourceEventId:event.sourceEventId,paymentRun:{is:{legalEntityId:"entity",status:"executed",currency:"UZS",fxRate:event.fxRate,bankAccount:{is:{legalEntityId:"entity",currency:"UZS"}},legalEntity:{is:{companyId:"company",tenantId:"tenant",company:{is:{tenantId:"tenant",isActive:true}}}}}}});expect(tx.financePayableAllocation.create.mock.calls[0][0].data).toMatchObject({legalEntityId:"entity",payableItemId:"payable",paymentRunLineId:"line",currency:"UZS"});expect(tx.financePayableAllocation.create.mock.calls[0][0].data.amount.toFixed(4)).toBe("0.1000");expect(tx.financePayableItem.update.mock.calls[0][0].data.outstandingAmount.toFixed(4)).toBe("0.0000");});
it.each([null,{tenantId:null}])("missing/null owner denies before financial reads and writes",async owner=>{tx.financeLegalEntity.findFirst.mockResolvedValue(owner);await expect(projectFinanceSubledgerEvent(tx,"entity",event)).rejects.toMatchObject({code:"FINANCE_PAYABLE_ALLOCATION_REFERENCE_INVALID"});expect(tx.financePayableItem.findFirst).not.toHaveBeenCalled();noWrites();});
it("foreign/unbound or unexecuted line denies without allocation",async()=>{tx.financePaymentRunLine.findFirst.mockResolvedValue(null);await expect(projectFinanceSubledgerEvent(tx,"entity",event)).rejects.toMatchObject({code:"FINANCE_PAYABLE_ALLOCATION_REFERENCE_INVALID"});noWrites();});
it("inconsistent exact money denies without financial changes",async()=>{tx.financePaymentRunLine.findFirst.mockResolvedValue({id:"line",amount:new Prisma.Decimal("0.2000")});await expect(projectFinanceSubledgerEvent(tx,"entity",event)).rejects.toMatchObject({code:"FINANCE_PAYABLE_ALLOCATION_MISMATCH"});noWrites();});
