jest.mock("../../src/config/prismaClient", () => ({ __esModule: true, default: new Proxy({}, { get: (_target, name) => { const value = (mockPrisma as any)[name]; return typeof value === "function" ? value.bind(mockPrisma) : value; } }) }));
// Domain envelope only is mocked to guarantee no Redis/logger import; actual transactional outbox writes run.
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents", () => ({ buildCargoPilotDomainEvent: (input: any) => ({ ...input, id: require("crypto").randomUUID(), occurredAt: new Date().toISOString(), schemaVersion: 1 }) }));
import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { randomUUID } from "crypto";
import { createTenantDemoFixture, TENANT_DEMO_IDS as ids } from "../../src/modules/tenancy/demo-fixtures";
import { persistTenantDemoFixture } from "../tenancy/postgres-fixture.persistence";
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"disposable-finance",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
import { prismaFinanceRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance.repository";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable legal entity identity required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing PostgreSQL target");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});let mockPrisma:PrismaClient;const fixture=createTenantDemoFixture();
function actor(m:any){return {id:m.userId,tenantId:m.tenantId,tenantMembershipId:m.tenantMembershipId,companyId:m.companyId,companyMembershipId:m.id,membershipId:m.id} as any;}
const owned=fixture.companyMemberships.find(m=>m.id===ids.companyMemberships.makerTransAsiaUz)!;
async function business(){return {entities:await mockPrisma.financeLegalEntity.findMany({orderBy:{id:"asc"}}),audit:await mockPrisma.financeAuditEvent.count(),outbox:await mockPrisma.financeDomainEventOutbox.count()};}
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{client.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});for(const key of ["finance.journals.read","finance.journals.create","finance.journals.post","finance.journals.reverse"])await mockPrisma.permission.create({data:{key,resource:"synthetic-finance",action:key}});for(const m of fixture.companyMemberships){const role=await mockPrisma.role.create({data:{companyId:m.companyId,code:randomUUID(),name:"Synthetic Finance"}});for(const key of ["finance.journals.read","finance.journals.create","finance.journals.post","finance.journals.reverse"]){const permission=await mockPrisma.permission.findUniqueOrThrow({where:{key}});await mockPrisma.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}});}await mockPrisma.membershipRole.create({data:{membershipId:m.id,roleId:role.id}});await mockPrisma.membershipScope.create({data:{membershipId:m.id,scopeType:"company",scopeRefId:m.companyId}});}});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});

const journals=new Map<string,string[]>(), accounts=new Map<string,string>();
beforeAll(async()=>{for(const entity of fixture.financeLegalEntities){const account=await mockPrisma.financeAccount.create({data:{legalEntityId:entity.id,code:"SYNTH",name:"Synthetic asset",type:"asset"}});accounts.set(entity.companyId,account.id);const rows=[];for(const n of [1,2]){const document=await mockPrisma.financeDocument.create({data:{legalEntityId:entity.id,documentNumber:"SYN-DOC-"+n,type:"manual_journal",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:"0.1000",baseAmount:"0.1000",fxRate:"1.0000000001",idempotencyKey:"synthetic-"+n,createdByUserId:owned.userId,metadataJson:{private:"SYNTHETIC-CANARY"}}});const row=await mockPrisma.financeJournalEntry.create({data:{legalEntityId:entity.id,documentId:document.id,journalNumber:"SYN-JRN-"+n,postingDate:new Date("2026-01-01"),createdAt:new Date("2026-01-0"+n),totalDebitBase:"0.1000",totalCreditBase:"0.1000",lines:{create:[{legalEntityId:entity.id,lineNumber:1,accountId:account.id,debitAmount:"0.1000",currency:"UZS",fxRate:"1.0000000001",debitBase:"0.1000",metadataJson:{private:"SYNTHETIC-CANARY"}},{legalEntityId:entity.id,lineNumber:2,accountId:account.id,creditAmount:"0.1000",currency:"UZS",fxRate:"1.0000000001",creditBase:"0.1000"}]}}});rows.push(row.id);}journals.set(entity.companyId,rows);}});
async function records(){return{...await business(),documents:await mockPrisma.financeDocument.findMany({orderBy:{id:"asc"}}),journals:await mockPrisma.financeJournalEntry.findMany({orderBy:{id:"asc"}}),lines:await mockPrisma.financeJournalLine.findMany({orderBy:{id:"asc"}})};}
it("selected context separates two tenants/three companies and safely preserves exact journal decimals",async()=>{const before=await records();for(const membership of fixture.companyMemberships.filter(m=>m.userId===ids.users.multiTenant)){const result:any=await repo.listJournals(actor(membership),{limit:10});expect(result.items.map((r:any)=>r.id)).toEqual([...journals.get(membership.companyId)!].reverse());for(const row of result.items){expect(row.document.totalAmount.toString()).toBe("0.1");expect(row.document.fxRate.toString()).toBe("1.0000000001");expect(row).not.toHaveProperty("postedByUserId");expect(row.document).not.toHaveProperty("metadataJson");const detail:any=await repo.getJournal(actor(membership),row.id);expect(detail.lines).toHaveLength(2);expect(detail._count.lines).toBe(2);for(const line of detail.lines){expect(line.account.id).toBe(accounts.get(membership.companyId));expect(line).not.toHaveProperty("metadataJson");expect(line).not.toHaveProperty("customerEntityId");}}}expect(await records()).toEqual(before);});
it("owned cursor paginates and foreign cursor/detail reject without configuration or business changes",async()=>{const before=await records();const first:any=await repo.listJournals(actor(owned),{limit:1});const next:any=await repo.listJournals(actor(owned),{limit:1,cursor:first.pageInfo.nextCursor});expect(next.items.map((r:any)=>r.id)).toEqual([journals.get(owned.companyId)![0]]);for(const company of [ids.organizations.unrelated,ids.organizations.transAsiaDe]){const foreign=journals.get(company)![0];await expect(repo.getJournal(actor(owned),foreign)).rejects.toMatchObject({statusCode:404});await expect(repo.listJournals(actor(owned),{limit:1,cursor:foreign})).rejects.toMatchObject({statusCode:404});}expect(await records()).toEqual(before);});
it.each(["document","account","reversal"] as const)("foreign-tenant %s reference update rejects atomically",async relationship=>{await inconsistent(relationship,ids.organizations.unrelated);});
it.each(["document","account","reversal"] as const)("same-tenant foreign-company %s reference update rejects atomically",async relationship=>{await inconsistent(relationship,ids.organizations.transAsiaDe);});
async function rejected(sql:string,values:any[],constraint:string,code="23503"){const client=await pool.connect();try{await client.query("BEGIN");const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;await client.query('INSERT INTO "FinanceAuditEvent" ("legalEntityId",action,"actorUserId") VALUES ($1,$2,$3)',[entity.id,"synthetic-before-rejection",owned.userId]);await client.query('INSERT INTO "FinanceDomainEventOutbox" ("legalEntityId","aggregateType","aggregateId","eventType","occurredAt","payloadJson","updatedAt") VALUES ($1,$2,$3,$4,NOW(),$5,NOW())',[entity.id,"synthetic-journal",journals.get(owned.companyId)![0],"synthetic.rejected",{}]);try{await client.query(sql,values);throw Error("Invalid reference accepted");}catch(error:any){expect(error.code).toBe(code);expect(error.constraint).toBe(constraint);}await client.query("ROLLBACK");}finally{await client.query("ROLLBACK");client.release();}}
async function inconsistent(relationship:string,company:string){const id=journals.get(owned.companyId)![0],foreign=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(company)![0]}});const line=await mockPrisma.financeJournalLine.findFirstOrThrow({where:{journalEntryId:id,lineNumber:1}});let doc:any;if(relationship==="document")doc=await mockPrisma.financeDocument.create({data:{legalEntityId:foreign.legalEntityId,documentNumber:randomUUID(),type:"manual_journal",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:"0.1000",baseAmount:"0.1000",fxRate:"1",idempotencyKey:randomUUID(),createdByUserId:owned.userId}});const before=await records();try{if(relationship==="document")await rejected('UPDATE "FinanceJournalEntry" SET "documentId"=$1 WHERE id=$2',[doc.id,id],"FinanceJournalEntry_document_entity_fkey");else if(relationship==="account")await rejected('UPDATE "FinanceJournalLine" SET "accountId"=$1 WHERE id=$2',[accounts.get(company)!,line.id],"FinanceJournalLine_account_entity_fkey");else await rejected('UPDATE "FinanceJournalEntry" SET "reversalOfId"=$1 WHERE id=$2',[foreign.id,id],"FinanceJournalEntry_reversal_entity_fkey");expect(await records()).toEqual(before);}finally{if(doc)await mockPrisma.financeDocument.delete({where:{id:doc.id}});}}

it("null/inactive finance ownership hides journals without read-driven configuration",async()=>{const entity=fixture.financeLegalEntities.find(e=>e.companyId===owned.companyId)!;for(const data of [{tenantId:null},{isActive:false}]){await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data});const before=await records();try{expect(await repo.listJournals(actor(owned),{limit:10})).toMatchObject({items:[]});await expect(repo.getJournal(actor(owned),journals.get(owned.companyId)![0])).rejects.toMatchObject({statusCode:404});expect(await records()).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:entity.id},data:{tenantId:owned.tenantId,isActive:true}});}}});
it("current suspended membership denies previously authorized journal reads",async()=>{await repo.listJournals(actor(owned),{limit:10});await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"suspended"}});const before=await records();try{await expect(repo.getJournal(actor(owned),journals.get(owned.companyId)![0])).rejects.toMatchObject({statusCode:403});expect(await records()).toEqual(before);}finally{await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"active"}});}});

function entity(company=owned.companyId){return fixture.financeLegalEntities.find(e=>e.companyId===company)!;}
async function draftDocument(company:string){return mockPrisma.financeDocument.create({data:{legalEntityId:entity(company).id,documentNumber:randomUUID(),type:"manual_journal",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",totalAmount:"0.1000",baseAmount:"0.1000",fxRate:"1",idempotencyKey:randomUUID(),createdByUserId:owned.userId}});}
it.each([ids.organizations.unrelated,ids.organizations.transAsiaDe])("foreign entity %s reference inserts reject with audit/outbox rollback",async company=>{const doc=await draftDocument(company),local=await draftDocument(owned.companyId);const before=await records();try{await rejected('INSERT INTO "FinanceJournalEntry" ("legalEntityId","documentId","journalNumber","postingDate","totalDebitBase","totalCreditBase","updatedAt") VALUES ($1,$2,$3,$4,1,1,NOW())',[entity().id,doc.id,randomUUID(),new Date("2026-01-01")],"FinanceJournalEntry_document_entity_fkey");await rejected('INSERT INTO "FinanceJournalLine" ("legalEntityId","journalEntryId","lineNumber","accountId",currency,"fxRate") VALUES ($1,$2,99,$3,$4,1)',[entity().id,journals.get(owned.companyId)![0],accounts.get(company),"UZS"],"FinanceJournalLine_account_entity_fkey");await rejected('INSERT INTO "FinanceJournalEntry" ("legalEntityId","documentId","journalNumber","postingDate","totalDebitBase","totalCreditBase","reversalOfId","updatedAt") VALUES ($1,$2,$3,$4,1,1,$5,NOW())',[entity().id,local.id,randomUUID(),new Date("2026-01-01"),journals.get(company)![0]],"FinanceJournalEntry_reversal_entity_fkey");await rejected('INSERT INTO "FinanceDocument" ("legalEntityId","documentNumber",type,"documentDate","postingDate",currency,"totalAmount","baseAmount","fxRate","idempotencyKey","createdByUserId","reversalOfId","updatedAt") VALUES ($1,$2,$3,$4,$4,$5,1,1,1,$6,$7,$8,NOW())',[entity().id,randomUUID(),"adjustment",new Date("2026-01-01"),"UZS",randomUUID(),owned.userId,doc.id],"FinanceDocument_reversal_entity_fkey");expect(await records()).toEqual(before);}finally{await mockPrisma.financeDocument.deleteMany({where:{id:{in:[doc.id,local.id]}}});}});
it("line parent/bridge retarget and null bridge cannot bypass compound equality",async()=>{const line=await mockPrisma.financeJournalLine.findFirstOrThrow({where:{journalEntryId:journals.get(owned.companyId)![0]}});const before=await records();await rejected('UPDATE "FinanceJournalLine" SET "journalEntryId"=$1,"lineNumber"=99 WHERE id=$2',[journals.get(ids.organizations.transAsiaDe)![0],line.id],"FinanceJournalLine_journal_entity_fkey");await rejected('UPDATE "FinanceJournalLine" SET "legalEntityId"=NULL WHERE id=$1',[line.id],"FinanceJournalLine_entity_required_check","23514");await rejected('INSERT INTO "FinanceJournalLine" ("journalEntryId","lineNumber","accountId",currency,"fxRate") VALUES ($1,99,$2,$3,1)',[journals.get(owned.companyId)![0],accounts.get(owned.companyId),"UZS"],"FinanceJournalLine_entity_required_check","23514");expect(await records()).toEqual(before);});
it("document reversal update and linked-document entity retarget are rejected",async()=>{const original=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(owned.companyId)![0]}});const foreign=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:journals.get(ids.organizations.unrelated)![0]}});const before=await records();await rejected('UPDATE "FinanceDocument" SET "reversalOfId"=$1 WHERE id=$2',[foreign.documentId,original.documentId],"FinanceDocument_reversal_entity_fkey");await rejected('UPDATE "FinanceDocument" SET "legalEntityId"=$1,"documentNumber"=$3,"idempotencyKey"=$4 WHERE id=$2',[foreign.legalEntityId,original.documentId,randomUUID(),randomUUID()],"FinanceJournalEntry_document_entity_fkey");expect(await records()).toEqual(before);});
function command(){return{companyId:owned.companyId,actorUserId:owned.userId,idempotencyKey:randomUUID(),documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",fxRate:"1",lines:[{accountId:accounts.get(owned.companyId)!,debitAmount:"0.1000",creditAmount:"0"},{accountId:accounts.get(owned.companyId)!,debitAmount:"0",creditAmount:"0.1000"}]};}
it("valid creation, concurrent posting and identical reversal preserve one balanced financial result and audit",async()=>{await mockPrisma.financeFiscalPeriod.create({data:{legalEntityId:entity().id,fiscalYear:2026,periodNumber:1,name:"Synthetic open",startDate:new Date("2026-01-01"),endDate:new Date("2026-01-31")}});const input=command();const draft:any=await repo.createDraftJournal(input,actor(owned));expect(draft.lines.every((l:any)=>l.legalEntityId===entity().id)).toBe(true);const beforeAudit=await mockPrisma.financeAuditEvent.count();const results:any[]=await Promise.all([repo.postJournal(actor(owned),draft.id),repo.postJournal(actor(owned),draft.id)]);expect(results.every(r=>r.status==="posted")).toBe(true);expect(await mockPrisma.financeAuditEvent.count()).toBe(beforeAudit+1);const reverse={companyId:owned.companyId,actorUserId:owned.userId,journalId:draft.id,postingDate:new Date("2026-01-01"),reason:"Synthetic reversal",idempotencyKey:randomUUID()};const reversals:any[]=await Promise.all([repo.reverseJournal(reverse,actor(owned)),repo.reverseJournal(reverse,actor(owned))]);expect(new Set(reversals.map(r=>r.id)).size).toBe(1);expect(reversals[0].totalDebitBase.eq(reversals[0].totalCreditBase)).toBe(true);expect(reversals[0].document.reversalOfId).toBe(draft.documentId);expect(reversals[0].lines.every((l:any)=>l.legalEntityId===entity().id)).toBe(true);expect(await mockPrisma.financeJournalEntry.count({where:{reversalOfId:draft.id}})).toBe(1);expect(await mockPrisma.financeAuditEvent.count({where:{journalEntryId:reversals[0].id,action:"finance.journal.reversed"}})).toBe(1);});
it("late outbox failure rolls back draft, lines, sequence and audit",async()=>{const before=await records(),numbers=await mockPrisma.financeNumberSequence.findMany();await pool.query(`CREATE FUNCTION public.cp_journal_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'synthetic journal outbox failure'; END $$;CREATE TRIGGER cp_journal_fail BEFORE INSERT ON "FinanceDomainEventOutbox" FOR EACH ROW EXECUTE FUNCTION public.cp_journal_fail();`);try{await expect(repo.createDraftJournal(command(),actor(owned))).rejects.toThrow("synthetic journal outbox failure");}finally{await pool.query('DROP TRIGGER cp_journal_fail ON "FinanceDomainEventOutbox"; DROP FUNCTION public.cp_journal_fail();');}expect(await records()).toEqual(before);expect(await mockPrisma.financeNumberSequence.findMany()).toEqual(numbers);});
it("compound catalog matches target columns and keeps historical certification unresolved",async()=>{const names=["FinanceDocument_reversal_entity_fkey","FinanceJournalEntry_document_entity_fkey","FinanceJournalEntry_reversal_entity_fkey","FinanceJournalLine_journal_entity_fkey","FinanceJournalLine_account_entity_fkey","FinanceJournalLine_entity_required_check"];const result=await pool.query('SELECT conname,convalidated,pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conname = ANY($1) ORDER BY conname',[names]);expect(result.rows).toHaveLength(6);for(const r of result.rows){expect(r.convalidated).toBe(false);expect(r.definition).toContain('"legalEntityId"');}expect(result.rows.find(r=>r.conname==="FinanceJournalLine_account_entity_fkey").definition).toContain('FOREIGN KEY ("accountId", "legalEntityId") REFERENCES "FinanceAccount"(id, "legalEntityId")');});

it("foreign parent-key mutation waits for a valid line insert then rejects without audit/outbox effects",async()=>{const local=journals.get(owned.companyId)![0],foreignDoc=await draftDocument(ids.organizations.transAsiaDe),before=await records();const child=await pool.connect(),parent=await pool.connect();let lineId:string|undefined;try{await child.query("BEGIN");await parent.query("BEGIN");const inserted=await child.query('INSERT INTO "FinanceJournalLine" ("legalEntityId","journalEntryId","lineNumber","accountId",currency,"fxRate") VALUES ($1,$2,98,$3,$4,1) RETURNING id',[entity().id,local,accounts.get(owned.companyId),"UZS"]);lineId=inserted.rows[0].id;await parent.query('INSERT INTO "FinanceAuditEvent" ("legalEntityId",action) VALUES ($1,$2)',[entity().id,"synthetic-competing-parent"]);await parent.query('INSERT INTO "FinanceDomainEventOutbox" ("legalEntityId","aggregateType","aggregateId","eventType","occurredAt","payloadJson","updatedAt") VALUES ($1,$2,$3,$4,NOW(),$5,NOW())',[entity().id,"synthetic-journal",local,"synthetic.competing",{}]);const pid=(await parent.query('SELECT pg_backend_pid() AS pid')).rows[0].pid;const pending=parent.query('UPDATE "FinanceJournalEntry" SET "legalEntityId"=$1,"documentId"=$2,"journalNumber"=$3 WHERE id=$4',[foreignDoc.legalEntityId,foreignDoc.id,randomUUID(),local]).then(()=>({accepted:true}),error=>({error}));let blocked=false;for(let attempt=0;attempt<40;attempt++){const activity:any[]=await mockPrisma.$queryRaw`SELECT wait_event_type FROM pg_stat_activity WHERE pid = ${pid}`;if(activity[0]?.wait_event_type==="Lock"){blocked=true;break;}await new Promise(resolve=>setTimeout(resolve,25));}expect(blocked).toBe(true);await child.query("COMMIT");const result:any=await pending;expect(result.error?.code).toBe("23503");expect(result.error?.constraint).toBe("FinanceJournalLine_journal_entity_fkey");await parent.query("ROLLBACK");const current=await mockPrisma.financeJournalEntry.findUniqueOrThrow({where:{id:local}});expect(current.legalEntityId).toBe(entity().id);expect(current.totalDebitBase.eq(current.totalCreditBase)).toBe(true);}finally{await child.query("ROLLBACK");await parent.query("ROLLBACK");child.release();parent.release();if(lineId)await mockPrisma.financeJournalLine.delete({where:{id:lineId}});}expect(await records()).toEqual(before);await mockPrisma.financeDocument.delete({where:{id:foreignDoc.id}});});

it("reversal retries bind target, actor, date, reason and financial basis without new effects",async()=>{await mockPrisma.financeFiscalPeriod.upsert({where:{legalEntityId_fiscalYear_periodNumber:{legalEntityId:entity().id,fiscalYear:2026,periodNumber:1}},create:{legalEntityId:entity().id,fiscalYear:2026,periodNumber:1,name:"Synthetic open",startDate:new Date("2026-01-01"),endDate:new Date("2026-01-31")},update:{}});const draft:any=await repo.createDraftJournal(command(),actor(owned));await repo.postJournal(actor(owned),draft.id);const intent={companyId:owned.companyId,actorUserId:owned.userId,journalId:draft.id,postingDate:new Date("2026-01-01"),reason:"Synthetic bound reversal",idempotencyKey:randomUUID()};const confirmed:any=await repo.reverseJournal(intent,actor(owned));const before=await records();expect((await repo.reverseJournal(intent,actor(owned))as any).id).toBe(confirmed.id);for(const changed of [{journalId:journals.get(owned.companyId)![0]},{postingDate:new Date("2026-01-02")},{reason:"Different intended reason"}])await expect(repo.reverseJournal({...intent,...changed},actor(owned))).rejects.toMatchObject({code:"FINANCE_REVERSAL_IDEMPOTENCY_CONFLICT"});const other=fixture.companyMemberships.find(m=>m.companyId===owned.companyId&&m.userId===ids.users.checker)!;await expect(repo.reverseJournal({...intent,actorUserId:other.userId},actor(other))).rejects.toMatchObject({code:"FINANCE_REVERSAL_IDEMPOTENCY_CONFLICT"});expect(await records()).toEqual(before);});
it("competing distinct reversal operations produce one balanced reversal",async()=>{await mockPrisma.financeFiscalPeriod.upsert({where:{legalEntityId_fiscalYear_periodNumber:{legalEntityId:entity().id,fiscalYear:2026,periodNumber:1}},create:{legalEntityId:entity().id,fiscalYear:2026,periodNumber:1,name:"Synthetic open",startDate:new Date("2026-01-01"),endDate:new Date("2026-01-31")},update:{}});const draft:any=await repo.createDraftJournal(command(),actor(owned));await repo.postJournal(actor(owned),draft.id);const beforeAudit=await mockPrisma.financeAuditEvent.count(),beforeOutbox=await mockPrisma.financeDomainEventOutbox.count();const intent={companyId:owned.companyId,actorUserId:owned.userId,journalId:draft.id,postingDate:new Date("2026-01-01"),reason:"Synthetic competing reversal"};const results=await Promise.allSettled([repo.reverseJournal({...intent,idempotencyKey:randomUUID()},actor(owned)),repo.reverseJournal({...intent,idempotencyKey:randomUUID()},actor(owned))]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);const rejected:any=results.find(r=>r.status==="rejected");expect(rejected.reason.code).toBe("FINANCE_JOURNAL_NOT_POSTED");const reversal=await mockPrisma.financeJournalEntry.findFirstOrThrow({where:{reversalOfId:draft.id}});expect(reversal.totalDebitBase.eq(reversal.totalCreditBase)).toBe(true);expect(await mockPrisma.financeJournalEntry.count({where:{reversalOfId:draft.id}})).toBe(1);expect(await mockPrisma.financeAuditEvent.count()).toBe(beforeAudit+1);expect(await mockPrisma.financeDomainEventOutbox.count()).toBe(beforeOutbox+1);});
