jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"test",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents",()=>({buildCargoPilotDomainEvent:jest.fn()}));
jest.mock("../../src/modules/identity-access/access-control",()=>({loadAccessSnapshot:jest.fn(),hasAnyPermissionSync:jest.fn(()=>true)}));
jest.mock("../../src/modules/identity-access/transport/fastify-auth",()=>({fastifyAuth:()=>async(request:any)=>{request.user=actor;}}));
import Fastify from "fastify";
import { database } from "./fixtures";
import { loadAccessSnapshot } from "../../src/modules/identity-access/access-control";
import { prismaFinanceDocumentsRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance-documents.repository";
import { FinanceDocumentsService } from "../../src/modules/finance-core/application/finance-documents.service";
import routes from "../../src/modules/finance-core/transport/fastify-routes";


const actor:any={id:"u",tenantId:"t",tenantMembershipId:"tm",companyId:"c",companyMembershipId:"cm",membershipId:"cm"};
const snapshot:any={...actor,userId:"u",permissionCodes:["finance.payables.manage","finance.payables.approve","policy.override"],scopes:[{scopeType:"company",scopeRefId:"c"}]};
const refs:any={resolveProviderSettlement:jest.fn(),resolveCarrierProvider:jest.fn(),validateCarrierBillLegs:jest.fn()};const service=new FinanceDocumentsService(repo,refs),id="11111111-1111-4111-8111-111111111111",intent:any={companyId:"c",actorUserId:"u",billId:id,lineId:id,allowSelfApproval:true,approved:true,fxRate:"999"};
function mutations(target:any,a:any,c=intent){return [()=>target.createCarrierBill(c,a),()=>target.submitCarrierBill(c.companyId,id,c.actorUserId,a),()=>target===service?service.approveCarrierBill(c,a):repo.approveCarrierBill(c.companyId,id,c.actorUserId,a),()=>target.rejectCarrierBill(c.companyId,id,c.actorUserId,"Synthetic",a)];}
beforeEach(()=>{jest.clearAllMocks();jest.mocked(loadAccessSnapshot).mockResolvedValue(snapshot);database.membershipScope.findFirst.mockReset().mockResolvedValue({id:"scope"});});
afterEach(()=>{expect(database.$transaction).not.toHaveBeenCalled();expect(refs.resolveProviderSettlement).not.toHaveBeenCalled();expect(refs.resolveCarrierProvider).not.toHaveBeenCalled();expect(refs.validateCarrierBillLegs).not.toHaveBeenCalled();expect(database.financeCarrierBill.findFirst).not.toHaveBeenCalled();for(const model of ["financeCarrierBill","financeCarrierBillLine","financeAuditEvent","financeSourceEvent","financeDomainEventOutbox","financeNumberSequence"])for(const method of ["create","update","updateMany","upsert","delete"])expect(database[model][method]).not.toHaveBeenCalled();});
it.each(["service","repository"])("%s rejects every mutation despite supplied approval/FX/override before references/effects",async target=>{for(const fn of mutations(target==="service"?service:repo,actor))await expect(fn()).rejects.toMatchObject({code:"FINANCE_CARRIER_BILL_ACCEPTANCE_REQUIRED"});expect(loadAccessSnapshot).toHaveBeenCalledWith(expect.objectContaining({requireFresh:true}));});
it.each([null,{...actor,tenantId:null},{...actor,membershipId:"wrong"}])("missing/partial context rejects",async a=>{for(const fn of mutations(repo,a))await expect(fn()).rejects.toMatchObject({statusCode:403});});
it.each([null,{...snapshot,permissionCodes:[]},{...snapshot,scopes:[]},{...snapshot,tenantId:"foreign"},{...snapshot,companyId:"foreign"}])("revoked or foreign fresh context rejects",async value=>{jest.mocked(loadAccessSnapshot).mockResolvedValue(value);for(const fn of mutations(service,actor))await expect(fn()).rejects.toMatchObject({statusCode:403});});
it.each([{companyId:"foreign"},{actorUserId:"foreign"}])("caller context mismatch rejects",async delta=>{for(const fn of mutations(repo,actor,{...intent,...delta}))await expect(fn()).rejects.toMatchObject({code:"FINANCE_CARRIER_BILL_CONTEXT_REJECTED"});});
it("synthesized scope cannot replace stored company grant",async()=>{database.membershipScope.findFirst.mockResolvedValue(null);for(const fn of mutations(repo,actor))await expect(fn()).rejects.toMatchObject({code:"FINANCE_COMPANY_SCOPE_REQUIRED"});});
it("HTTP propagates selected context across four denied mutations",async()=>{const app=Fastify();await app.register(routes);try{const body={carrierProviderId:id,supplierInvoiceNumber:"Synthetic",idempotencyKey:"synthetic-key",invoiceDate:"2026-01-01",currency:"UZS",fxRate:"999",lines:[{orderId:id,orderLegId:id,description:"Synthetic",quantity:"1",unitPrice:"1",taxAmount:"0"}]};expect((await app.inject({method:"POST",url:"/carrier-bills",payload:body})).json().code).toBe("FINANCE_CARRIER_BILL_ACCEPTANCE_REQUIRED");for(const op of ["submit","approve","reject"]){const payload=op==="reject"?{reason:"Synthetic"}:op.endsWith("reconcile")?{paymentIntentId:id}:undefined;expect((await app.inject({method:"POST",url:"/carrier-bills/"+id+"/"+op,payload})).json().code).toBe("FINANCE_CARRIER_BILL_ACCEPTANCE_REQUIRED");}}finally{await app.close();}},15000);
