jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"test",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
jest.mock("../../src/modules/identity-access/access-control",()=>({loadAccessSnapshot:jest.fn(),hasAnyPermissionSync:jest.fn()}));
jest.mock("../../src/modules/identity-access/transport/fastify-auth",()=>({fastifyAuth:()=>async(request:any)=>{request.user=mockActor;}}));
import Fastify from "fastify";
import { database } from "./fixtures";
import { loadAccessSnapshot } from "../../src/modules/identity-access/access-control";
import { prismaFinanceRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance.repository";
import { FinanceService } from "../../src/modules/finance-core/application/finance.service";
import routes from "../../src/modules/finance-core/transport/fastify-routes";
const mockActor:any={id:"u",tenantId:"t",tenantMembershipId:"tm",companyId:"c",companyMembershipId:"cm",membershipId:"cm"};
const snapshot:any={...mockActor,userId:"u",permissionCodes:["finance.journals.read"],scopes:[{scopeType:"company",scopeRefId:"c"}]};
const service=new FinanceService(repo);


import { assertJournalBindings, requireJournalEntity } from "../../src/modules/finance-core/infrastructure/journal-integrity";
const entity={id:"entity-a",companyId:"c",tenantId:"t",isActive:true,tenant:{status:"active"},company:{isActive:true,tenantId:"t"}};
const graph=()=>({id:"j",legalEntityId:"entity-a",documentId:"d",document:{id:"d",legalEntityId:"entity-a"},lines:[{journalEntryId:"j",legalEntityId:"entity-a",accountId:"a",account:{id:"a",legalEntityId:"entity-a"}}]});
beforeEach(()=>{jest.clearAllMocks();jest.mocked(loadAccessSnapshot).mockResolvedValue({...snapshot,permissionCodes:["finance.journals.create","finance.journals.post","finance.journals.reverse"]});database.membershipScope.findFirst.mockReset().mockResolvedValue({id:"scope"});database.financeLegalEntity.findUnique.mockReset().mockResolvedValue(entity);});
afterEach(()=>{for(const model of ["financeJournalEntry","financeJournalLine","financeDocument","financeAuditEvent","financeDomainEventOutbox"])for(const operation of ["create","update","updateMany","upsert","delete"])expect(database[model][operation]).not.toHaveBeenCalled();});
test("authoritative active company/tenant entity and matching graph validate without mutation",async()=>{expect(await requireJournalEntity(database,"c")).toEqual(entity);await expect(assertJournalBindings(database,graph(),entity.id)).resolves.toBeUndefined();});
test.each([null,{...entity,tenantId:null},{...entity,isActive:false},{...entity,tenant:{status:"suspended"}},{...entity,company:{isActive:true,tenantId:"foreign"}},{...entity,company:{isActive:false,tenantId:"t"}}])("missing/null/inactive/conflicting entity rejects",async value=>{database.financeLegalEntity.findUnique.mockResolvedValue(value);await expect(requireJournalEntity(database,"c")).rejects.toMatchObject({code:"FINANCE_ENTITY_NOT_CONFIGURED"});});
test.each(["document-entity","document-id","line-entity","line-parent","account-id","account-entity","legacy-null"])("conflicting %s graph is not repaired or accepted",async kind=>{const g:any=graph();if(kind==="document-entity")g.document.legalEntityId="foreign";if(kind==="document-id")g.document.id="foreign";if(kind==="line-entity")g.lines[0].legalEntityId="foreign";if(kind==="line-parent")g.lines[0].journalEntryId="foreign";if(kind==="account-id")g.lines[0].account.id="foreign";if(kind==="account-entity")g.lines[0].account.legalEntityId="foreign";if(kind==="legacy-null")g.lines[0].legalEntityId=null;await expect(assertJournalBindings(database,g,entity.id)).rejects.toMatchObject({code:"FINANCE_JOURNAL_OWNERSHIP_REJECTED"});});
test.each(["document","journal"])("foreign %s reversal target rejects before effects",async kind=>{const g:any=graph();database.financeJournalEntry.findFirst.mockReset().mockResolvedValue(null);database.financeDocument.findFirst.mockReset().mockResolvedValue(null);if(kind==="document")g.document.reversalOfId="foreign";else g.reversalOfId="foreign";await expect(assertJournalBindings(database,g,entity.id)).rejects.toMatchObject({code:"FINANCE_JOURNAL_OWNERSHIP_REJECTED"});});
test.each([null,{...mockActor,tenantId:null},{...mockActor,membershipId:"other"}])("alternate mutation callers cannot use missing context",async actor=>{await expect(repo.createDraftJournal({}as any,actor)).rejects.toMatchObject({statusCode:403});await expect(repo.postJournal(actor,"j")).rejects.toMatchObject({statusCode:403});await expect(repo.reverseJournal({}as any,actor)).rejects.toMatchObject({statusCode:403});expect(database.$transaction).not.toHaveBeenCalled();});
test("forged command company/actor cannot become authority",async()=>{await expect(repo.createDraftJournal({companyId:"foreign",actorUserId:"u"}as any,mockActor)).rejects.toMatchObject({code:"FINANCE_JOURNAL_CONTEXT_REJECTED"});await expect(repo.reverseJournal({companyId:"c",actorUserId:"foreign"}as any,mockActor)).rejects.toMatchObject({code:"FINANCE_JOURNAL_CONTEXT_REJECTED"});expect(database.$transaction).not.toHaveBeenCalled();});
test("current permission removal denies all mutations before a transaction",async()=>{jest.mocked(loadAccessSnapshot).mockResolvedValue({...snapshot,permissionCodes:[]});await expect(repo.createDraftJournal({}as any,mockActor)).rejects.toMatchObject({statusCode:403});await expect(repo.postJournal(mockActor,"j")).rejects.toMatchObject({statusCode:403});await expect(repo.reverseJournal({}as any,mockActor)).rejects.toMatchObject({statusCode:403});expect(database.$transaction).not.toHaveBeenCalled();});
test.each(["branchId","costCenterCode","profitCenterCode"])("unapproved %s rejects before locking, receipt lookup or business writes",async key=>{
  database.$transaction.mockImplementation(async(work:any)=>work(database));
  database.$queryRaw.mockClear();database.$queryRawUnsafe.mockClear();database.financeDocument.findUnique.mockClear();database.financeNumberSequence.upsert.mockClear();database.financeNumberSequence.update.mockClear();
  const command:any={companyId:"c",actorUserId:"u",idempotencyKey:"synthetic-dimension",documentDate:new Date("2026-01-01"),postingDate:new Date("2026-01-01"),currency:"UZS",fxRate:"1",lines:[{accountId:"a",debitAmount:"1",creditAmount:"0",[key]:"foreign"},{accountId:"b",debitAmount:"0",creditAmount:"1"}]};
  await expect(repo.createDraftJournal(command,mockActor)).rejects.toMatchObject({statusCode:409,code:"FINANCE_DIMENSION_CONFIGURATION_REQUIRED"});
  expect(database.$queryRaw).not.toHaveBeenCalled();expect(database.$queryRawUnsafe).not.toHaveBeenCalled();expect(database.financeDocument.findUnique).not.toHaveBeenCalled();expect(database.financeNumberSequence.upsert).not.toHaveBeenCalled();expect(database.financeNumberSequence.update).not.toHaveBeenCalled();
});
