jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"test",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
jest.mock("../../src/modules/identity-access/access-control",()=>({loadAccessSnapshot:jest.fn(),hasAnyPermissionSync:jest.fn()}));
jest.mock("../../src/modules/identity-access/transport/fastify-auth",()=>({fastifyAuth:()=>async(request:any)=>{request.user=mockActor;}}));
import Fastify from "fastify";
import { database } from "./fixtures";
import { loadAccessSnapshot } from "../../src/modules/identity-access/access-control";
import { prismaFinanceRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance.repository";
import { FinanceService } from "../../src/modules/finance-core/application/finance.service";
import routes from "../../src/modules/finance-core/transport/fastify-routes";
const mockActor:any={id:"u",tenantId:"t",tenantMembershipId:"tm",companyId:"c",companyMembershipId:"cm",membershipId:"cm"};
const snapshot:any={...mockActor,userId:"u",permissionCodes:["finance.journals.read"],scopes:[{scopeType:"company",scopeRefId:"c"}]};
const service=new FinanceService(repo);

const id="11111111-1111-4111-8111-111111111111";
const row={id,legalEntityId:"entity-a",createdAt:new Date("2026-01-01"),document:{totalAmount:"0.1000",fxRate:"1.0000000001"},lines:[],_count:{lines:0}};
beforeEach(()=>{jest.clearAllMocks();jest.mocked(loadAccessSnapshot).mockResolvedValue(snapshot);database.membershipScope.findFirst.mockReset().mockResolvedValue({id:"scope"});database.financeLegalEntity.findFirst.mockReset().mockResolvedValue({id:"entity-a"});database.financeJournalEntry.findFirst.mockReset().mockResolvedValue(row);database.financeJournalEntry.findMany.mockReset().mockResolvedValue([row]);});
afterEach(()=>{expect(database.$transaction).not.toHaveBeenCalled();for(const model of ["financeJournalEntry","financeJournalLine","financeDocument","financeLegalEntity","financeAuditEvent","financeDomainEventOutbox"])for(const operation of ["create","update","updateMany","upsert","delete"])expect(database[model][operation]).not.toHaveBeenCalled();});
const list=(actor:any=mockActor,page:any={limit:10})=>service.listJournals(actor,page);
function owned(q:any){const where=q.where.AND[0];expect(where).toMatchObject({legalEntityId:"entity-a",legalEntity:{is:{tenantId:"t",companyId:"c",isActive:true}},document:{is:{legalEntityId:"entity-a"}},lines:{every:{account:{is:{legalEntityId:"entity-a"}}}}});expect(where.lines.every.account.is.OR).toContainEqual({parent:{is:{legalEntityId:"entity-a"}}});expect(where.OR).toContainEqual({reversalOf:{is:{legalEntityId:"entity-a"}}});}
test("authorized list uses fresh context and nested ownership with exact decimal contract",async()=>{expect(await list()).toMatchObject({items:[{id,document:{totalAmount:"0.1000",fxRate:"1.0000000001"}}]});expect(loadAccessSnapshot).toHaveBeenCalledWith(expect.objectContaining({requireFresh:true}));const q=database.financeJournalEntry.findMany.mock.calls[0][0];owned(q);expect(q.select.document.select).not.toHaveProperty("metadataJson");expect(q.select).not.toHaveProperty("postedByUserId");expect(q.include).toBeUndefined();expect(q.select._count).toEqual({select:{lines:true}});});
test("detail safely projects accounts and bounds complete line content",async()=>{expect(await service.getJournal(mockActor,id)).toMatchObject({id,lines:[]});const q=database.financeJournalEntry.findFirst.mock.calls[0][0];owned(q);expect(q.select.lines.take).toBe(501);expect(q.select.lines.select).not.toHaveProperty("metadataJson");expect(q.select.lines.select.account.select).not.toHaveProperty("metadataJson");expect(q.select.lines.select).not.toHaveProperty("customerEntityId");});
test.each([null,{...snapshot,permissionCodes:[]},{...snapshot,tenantId:"foreign"},{...snapshot,companyId:"foreign"},{...snapshot,userId:"foreign"},{...snapshot,scopes:[]}])("ineligible fresh context denies list and detail before protected queries",async value=>{jest.mocked(loadAccessSnapshot).mockResolvedValue(value);await expect(list()).rejects.toMatchObject({statusCode:403});await expect(service.getJournal(mockActor,id)).rejects.toMatchObject({statusCode:403});expect(database.financeLegalEntity.findFirst).not.toHaveBeenCalled();expect(database.financeJournalEntry.findMany).not.toHaveBeenCalled();expect(database.financeJournalEntry.findFirst).not.toHaveBeenCalled();});
test.each([null,{...mockActor,tenantId:null},{...mockActor,membershipId:"wrong"}])("direct entry rejects missing or conflicting selected context",async actor=>{await expect(repo.listJournals(actor,{limit:10})).rejects.toMatchObject({statusCode:403});await expect(repo.getJournal(actor,id)).rejects.toMatchObject({statusCode:403});});
test("removed stored scope denies despite synthesized snapshot grant",async()=>{database.membershipScope.findFirst.mockResolvedValue(null);await expect(list()).rejects.toMatchObject({code:"FINANCE_COMPANY_SCOPE_REQUIRED"});expect(database.financeLegalEntity.findFirst).not.toHaveBeenCalled();});
test("null/foreign/inactive legal entity hides results without creating configuration",async()=>{database.financeLegalEntity.findFirst.mockResolvedValue(null);expect(await list()).toEqual({items:[],pageInfo:{hasMore:false,nextCursor:null}});await expect(repo.getJournal(mockActor,id)).rejects.toMatchObject({statusCode:404});expect(database.financeJournalEntry.findMany).not.toHaveBeenCalled();});
test("foreign cursor is hidden before listing; owned cursor uses date/id keyset",async()=>{database.financeJournalEntry.findFirst.mockResolvedValueOnce(null);await expect(list(mockActor,{limit:1,cursor:id})).rejects.toMatchObject({statusCode:404});expect(database.financeJournalEntry.findMany).not.toHaveBeenCalled();await list(mockActor,{limit:1,cursor:id});const q=database.financeJournalEntry.findMany.mock.calls[0][0];owned(q);expect(q.cursor).toBeUndefined();expect(q.where.AND[1]).toEqual({OR:[{createdAt:{lt:row.createdAt}},{createdAt:row.createdAt,id:{lt:id}}]});});
test.each([{limit:0},{limit:101},{limit:1.5},{limit:10,cursor:"bad"},{limit:10,cursor:null},{limit:10,status:"posted"},{limit:10,companyId:"foreign"},null])("invalid direct page rejects",async page=>{await expect(list(mockActor,page)).rejects.toMatchObject({statusCode:400});expect(database.financeJournalEntry.findMany).not.toHaveBeenCalled();});
test("hidden foreign document/account/reversal detail produces no response",async()=>{database.financeJournalEntry.findFirst.mockResolvedValue(null);await expect(service.getJournal(mockActor,id)).rejects.toMatchObject({code:"FINANCE_JOURNAL_NOT_FOUND"});owned(database.financeJournalEntry.findFirst.mock.calls[0][0]);});
test("every final read and related count requires whole-journal operational dimension integrity",async()=>{
  await list();const line=database.financeJournalEntry.findMany.mock.calls[0][0].where.AND[0].lines.every;
  expect(line).toMatchObject({branchId:null,costCenterCode:null,profitCenterCode:null});
  expect(line.AND).toContainEqual({OR:[{orderId:null},{dimensionOrder:{is:{tenantId:"t",ownerOrgId:"c"}}}]});
  expect(line.AND).toContainEqual({OR:[{warehouseId:null},{dimensionWarehouse:{is:{tenantId:"t"}}}]});
  expect(line.AND[0].OR[0]).toMatchObject({tenantId:null,companyId:null,orderId:null,orderLegId:null,customerEntityId:null,warehouseId:null,carrierProviderId:null});
  expect(line.AND[0].OR[1]).toMatchObject({tenantId:"t",companyId:"c",dimensionEntity:{is:{id:"entity-a",tenantId:"t",companyId:"c"}}});
});
test("oversized historical detail rejects instead of returning truncated financial lines",async()=>{database.financeJournalEntry.findFirst.mockResolvedValue({...row,lines:Array.from({length:501},()=>({}))});await expect(service.getJournal(mockActor,id)).rejects.toMatchObject({code:"FINANCE_JOURNAL_DETAIL_LIMIT",statusCode:409});});
test("HTTP preserves read contracts, strict filters and sanitized failures",async()=>{const app=Fastify();await app.register(routes);try{expect((await app.inject({method:"GET",url:"/journals?limit=10"})).statusCode).toBe(200);expect((await app.inject({method:"GET",url:"/journals/"+id})).statusCode).toBe(200);expect((await app.inject({method:"GET",url:"/journals?companyId=foreign"})).statusCode).toBe(400);database.financeJournalEntry.findFirst.mockRejectedValue(new Error("CANARY private metadata"));const failure=await app.inject({method:"GET",url:"/journals/"+id});expect(failure.statusCode).toBe(500);expect(failure.body).not.toContain("CANARY");}finally{await app.close();}});
