jest.mock("../../src/modules/identity-access/application/company-delegation",()=>({companyMembershipPrimitives:{context:(a:any)=>{if(!a?.tenantId)throw Error("Missing context");return a;},member:jest.fn(async()=>mockMember),agrees:(m:any,c:any)=>{if(m.id!==c.companyMembershipId)throw Error("Mismatch");},keys:(m:any)=>m.keys}}));
import {readFinancialAccess} from "../../src/modules/identity-access/application/financial-discovery";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,"0")}`;
const actor:any={id:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),companyMembershipId:id(5)};
let mockMember:any;
function setup(){mockMember={id:id(5),keys:["membership.proposeFinancial"],scopes:[{scopeType:"company",scopeRefId:id(3)}]};const a:any={enabled:true,kind:"proposer",userId:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),legalEntityId:id(6),profileRevisions:["pricing-maker.v1"],action:"operator-authorize",result:{companyMembershipId:id(5),kind:"proposer",legalEntityId:id(6),profileRevisions:["pricing-maker.v1"]}};
 const tx:any={$queryRaw:jest.fn(async()=>[a]),$executeRaw:jest.fn(()=>{throw Error("Read wrote");}),financeLegalEntity:{findFirst:jest.fn(async()=>({id:id(6),baseCurrency:"UZS",company:{name:"Synthetic company"},secret:"not projected"}))},companyMembership:{findMany:jest.fn(async()=>[])}};return{a,tx,db:{$transaction:jest.fn((f:any)=>f(tx))}as any};}
test("context denied before queries",async()=>{const h=setup();await expect(readFinancialAccess(h.db,{}as any,{view:"ceiling"})).rejects.toBeTruthy();expect(h.db.$transaction).not.toHaveBeenCalled();});
test("minimal accepted ceiling is read only and owned",async()=>{const h=setup();const r=await readFinancialAccess(h.db,actor,{view:"ceiling"});expect(JSON.stringify(r)).not.toMatch(/secret|operator|acceptedOperation|fingerprint/);expect(h.tx.$executeRaw).not.toHaveBeenCalled();expect(h.tx.$queryRaw.mock.calls[0][0].join("")).not.toMatch(/FOR (SHARE|UPDATE)/);expect(h.tx.financeLegalEntity.findFirst.mock.calls[0][0].where).toEqual({id:id(6),tenantId:id(2),companyId:id(3),isActive:true});});
test.each(["revoked","foreign","no-acceptance","no-permission","no-scope","missing-entity"])("denies %s authority",async v=>{const h=setup();if(v==="revoked")h.a.enabled=false;if(v==="foreign")h.a.companyId=id(9);if(v==="no-acceptance")h.a.action="operator-revoke";if(v==="no-permission")mockMember.keys=[];if(v==="no-scope")mockMember.scopes=[];if(v==="missing-entity")h.tx.financeLegalEntity.findFirst.mockResolvedValue(null);await expect(readFinancialAccess(h.db,actor,{view:"ceiling"})).rejects.toBeTruthy();expect(h.tx.$executeRaw).not.toHaveBeenCalled();});
test("query bounds and ownership input reject before database",async()=>{const h=setup();for(const q of [{view:"recipients",kind:"proposer",limit:51},{view:"ceiling",tenantId:id(9)},{view:"ceiling",legalEntityId:id(9)}])await expect(readFinancialAccess(h.db,actor,q)).rejects.toBeTruthy();expect(h.db.$transaction).not.toHaveBeenCalled();});
test("foreign cursor denies before candidate reads",async()=>{const h=setup();const cursor=Buffer.from(JSON.stringify({tenantId:id(9),companyId:id(3),membershipId:id(5),legalEntityId:id(6),kind:"proposer",view:"recipients",after:id(8)})).toString("base64url");await expect(readFinancialAccess(h.db,actor,{view:"recipients",kind:"proposer",cursor})).rejects.toMatchObject({code:"FINANCIAL_CURSOR_REJECTED"});expect(h.tx.companyMembership.findMany).not.toHaveBeenCalled();});
