jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
import {database as db} from "./fixtures";
import {createCarrierRoutingRuleForActor as create,updateCarrierRoutingRuleForActor as update,deleteCarrierRoutingRuleForActor as remove} from "../../src/modules/integrations-core/application/carrier-routing.service";
const actor=(companyId="ca",tenantId="ta",id="ma"):any=>({id:"same-user",companyId,tenantId,companyMembershipId:id,membershipId:id,tenantMembershipId:"tm-"+tenantId,permissions:["policy.override"]});
const operations=[(user:any)=>create({user,input:{companyId:user?.companyId,name:"synthetic",providerId:"untrusted",autoBook:true} as any}),(user:any)=>update({user,ruleId:"rule-a",input:{providerId:"untrusted",conditionsJson:{tenantId:"foreign"}}}),(user:any)=>remove({user,ruleId:"rule-a"})];
beforeEach(()=>{jest.clearAllMocks();db.companyMembership.findFirst.mockReset().mockImplementation(async({where}:any)=>({companyId:where.companyId,tenantId:where.tenantId,scopes:[{scopeType:"company",scopeRefId:where.companyId}],roles:[{role:{companyId:where.companyId,isSystem:false,rolePermissions:[{permission:{key:"integration.routing.manage"}}]}}]}));db.carrierRoutingRule.findFirst.mockReset().mockResolvedValue({id:"rule-a"});});
afterEach(()=>{expect(db.companyMembership.findMany).not.toHaveBeenCalled();expect(db.$transaction).not.toHaveBeenCalled();for(const m of ["carrierRoutingRule","routeTemplate","routeTemplateLeg","integrationProvider","integrationProviderSecret","integrationOutbox","integrationCanonicalEvent","orderLeg"])for(const op of ["create","update","updateMany","upsert","delete","deleteMany"])expect(db[m][op]).not.toHaveBeenCalled();});
it.each(operations)("selected authorized operation remains unavailable before configuration or business effects",async op=>{
 for(const user of [actor(),actor("cb","tb","mb"),actor("cc","ta","mc")])await expect(op(user)).rejects.toMatchObject({statusCode:409,code:"INTEGRATION_ROUTING_CONFIGURATION_WORKFLOW_REQUIRED"});
 expect(db.integrationProvider.findFirst).not.toHaveBeenCalled();expect(db.routeTemplate.findFirst).not.toHaveBeenCalled();
});
it.each(operations)("missing context fails before any protected rule lookup",async op=>{for(const user of [null,{...actor(),tenantId:null},{...actor(),tenantMembershipId:null},{...actor(),membershipId:"other"}])await expect(op(user)).rejects.toMatchObject({statusCode:403});expect(db.carrierRoutingRule.findFirst).not.toHaveBeenCalled();});
it.each(operations)("revoked membership cannot use override claims",async op=>{db.companyMembership.findFirst.mockResolvedValue(null);await expect(op(actor())).rejects.toMatchObject({statusCode:403});expect(db.carrierRoutingRule.findFirst).not.toHaveBeenCalled();});
it.each(operations)("scope and permission are mandatory",async op=>{db.companyMembership.findFirst.mockResolvedValue({companyId:"ca",tenantId:"ta",scopes:[],roles:[]});await expect(op(actor())).rejects.toMatchObject({statusCode:403});expect(db.carrierRoutingRule.findFirst).not.toHaveBeenCalled();});
it("creation company is an assertion not an ownership selector",async()=>{await expect(create({user:actor(),input:{companyId:"cb",name:"synthetic",providerId:"foreign"}})).rejects.toMatchObject({statusCode:403});expect(db.carrierRoutingRule.findFirst).not.toHaveBeenCalled();});
it.each([update,remove])("foreign and null-owned rules cannot be retrieved even by the same multi-company user",async op=>{db.carrierRoutingRule.findFirst.mockResolvedValue(null);await expect(op({user:actor(),ruleId:"foreign",input:{}} as any)).rejects.toMatchObject({statusCode:404});const query=db.carrierRoutingRule.findFirst.mock.calls[0][0];expect(query).toMatchObject({where:{id:"foreign",companyId:"ca",company:{is:{tenantId:"ta",isActive:true,tenant:{is:{status:"active"}}}}},select:{id:true}});});
