jest.mock("../../src/config/prismaClient", () => ({ __esModule: true, default: new Proxy({}, { get: (_target, name) => { const value = (mockPrisma as any)[name]; return typeof value === "function" ? value.bind(mockPrisma) : value; } }) }));
// Domain envelope only is mocked to guarantee no Redis/logger import; actual transactional outbox writes run.
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents", () => ({ buildCargoPilotDomainEvent: (input: any) => ({ ...input, id: require("crypto").randomUUID(), occurredAt: new Date().toISOString(), schemaVersion: 1 }) }));
import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { randomUUID } from "crypto";
import { createTenantDemoFixture, TENANT_DEMO_IDS as ids } from "../../src/modules/tenancy/demo-fixtures";
import { persistTenantDemoFixture } from "../tenancy/postgres-fixture.persistence";
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"disposable-finance",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
import { prismaFinanceRepository as repo } from "../../src/modules/finance-core/infrastructure/prisma-finance.repository";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable legal entity identity required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing PostgreSQL target");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});let mockPrisma:PrismaClient;const fixture=createTenantDemoFixture();
function actor(m:any){return {id:m.userId,tenantId:m.tenantId,tenantMembershipId:m.tenantMembershipId,companyId:m.companyId,companyMembershipId:m.id,membershipId:m.id} as any;}
const owned=fixture.companyMemberships.find(m=>m.id===ids.companyMemberships.makerTransAsiaUz)!;
async function business(){return {entities:await mockPrisma.financeLegalEntity.findMany({orderBy:{id:"asc"}}),audit:await mockPrisma.financeAuditEvent.count(),outbox:await mockPrisma.financeDomainEventOutbox.count()};}
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{client.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});for(const key of ["finance.settings.read","finance.settings.manage"])await mockPrisma.permission.create({data:{key,resource:"synthetic-finance",action:key}});for(const m of fixture.companyMemberships){const role=await mockPrisma.role.create({data:{companyId:m.companyId,code:randomUUID(),name:"Synthetic Finance"}});for(const key of ["finance.settings.read","finance.settings.manage"]){const permission=await mockPrisma.permission.findUniqueOrThrow({where:{key}});await mockPrisma.rolePermission.create({data:{roleId:role.id,permissionId:permission.id}});}await mockPrisma.membershipRole.create({data:{membershipId:m.id,roleId:role.id}});await mockPrisma.membershipScope.create({data:{membershipId:m.id,scopeType:"company",scopeRefId:m.companyId}});}});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();});
it("same user in both tenants and two same-tenant companies sees only exact selected entity",async()=>{const memberships=fixture.companyMemberships.filter(m=>m.userId===ids.users.multiTenant);const seen=[];for(const m of memberships){const entity:any=await repo.getLegalEntity(actor(m));expect(entity.companyId).toBe(m.companyId);expect(entity).not.toHaveProperty("createdByUserId");expect(entity).not.toHaveProperty("tenantId");seen.push(entity.id);}expect(new Set(seen).size).toBe(3);});
it("legacy null ownership stays hidden without backfill",async()=>{const row=await mockPrisma.financeLegalEntity.findUniqueOrThrow({where:{companyId:owned.companyId}});await mockPrisma.financeLegalEntity.update({where:{id:row.id},data:{tenantId:null}});const before=await business();try{expect(await repo.getLegalEntity(actor(owned))).toBeNull();expect(await business()).toEqual(before);}finally{await mockPrisma.financeLegalEntity.update({where:{id:row.id},data:{tenantId:owned.tenantId}});}});
it("inactive owned entity stays hidden",async()=>{await mockPrisma.financeLegalEntity.update({where:{companyId:owned.companyId},data:{isActive:false}});try{expect(await repo.getLegalEntity(actor(owned))).toBeNull();}finally{await mockPrisma.financeLegalEntity.update({where:{companyId:owned.companyId},data:{isActive:true}});}});
it("forged company tuple and suspended membership reject without business effects",async()=>{const before=await business();await expect(repo.getLegalEntity({...actor(owned),companyId:ids.organizations.transAsiaDe})).rejects.toMatchObject({statusCode:403});await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"suspended"}});try{await expect(repo.getLegalEntity(actor(owned))).rejects.toMatchObject({statusCode:403});expect(await business()).toEqual(before);}finally{await mockPrisma.companyMembership.update({where:{id:owned.id},data:{status:"active"}});}});
it("configuration remains unchanged even with settings permission and fabricated approval",async()=>{const before=await business();await expect(repo.configureLegalEntity({companyId:owned.companyId,actorUserId:owned.userId,baseCurrency:"USD",fiscalYearStartMonth:2,timezone:"UTC",approved:true} as any)).rejects.toMatchObject({code:"FINANCE_CONFIGURATION_APPROVAL_REQUIRED"});expect(await business()).toEqual(before);});
