jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:{}}));
jest.mock("../../src/config/redis",()=>({getRedisClient:async()=>null,getRedisPrefix:()=>"test",withRedisTimeout:(_n:any,w:any)=>w()}));
jest.mock("../../src/modules/identity-access/access-control",()=>({clearIdentityAccessCacheForUser:jest.fn()}));
import {readOperationalDelegation,listOperationalWarehouses,listCompanyInvitations,listOperationalGrants} from "../../src/modules/identity-access/application/company-delegation";
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor:any={id:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),companyMembershipId:id(5),membershipId:id(5)};
function harness(){
 const authority:any={membershipId:id(5),userId:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),ceilingRevision:'operational-delegation.v1',warehouseIds:[id(8)],enabled:true};
 const m:any={id:id(5),userId:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),status:'active',user:{id:id(1),email:'synthetic@example.invalid',name:'Synthetic'},company:{id:id(3),tenantId:id(2),type:'company',isActive:true},tenant:{id:id(2),status:'active'},tenantMembership:{id:id(4),tenantId:id(2),userId:id(1),status:'active'},roles:[{roleId:id(9),role:{companyId:id(3),isSystem:false,rolePermissions:['membership.delegateOperational','membership.invite'].map(key=>({permission:{key}}))}}],scopes:[{scopeType:'company',scopeRefId:id(3)}]};
 const tx:any={$queryRaw:jest.fn(async(strings:any)=>strings.join('').includes('CompanyDelegationAuthority')?[authority]:[]),companyMembership:{findUnique:jest.fn(async()=>m)},companyDelegationAuthority:{findUnique:jest.fn(async()=>null)},warehouse:{findMany:jest.fn(async()=>[])},companyInvitation:{findMany:jest.fn(async()=>[])},companyOperationalGrant:{findMany:jest.fn(async()=>[])},$executeRaw:jest.fn(()=>{throw Error('Read wrote state')})};
 const db:any={$transaction:jest.fn((work:any)=>work(tx))};return{authority,m,tx,db};
}
test('missing selected context rejects before reading',async()=>{const h=harness();await expect(readOperationalDelegation(h.db,{} as any)).rejects.toMatchObject({code:'DELEGATION_CONTEXT_REQUIRED'});expect(h.db.$transaction).not.toHaveBeenCalled()});
test.each(['disabled','ordinary-permission','foreign-bridge'])('accepted authority required: %s',async(which)=>{const h=harness();if(which==='disabled')h.authority.enabled=false;if(which==='ordinary-permission')h.m.roles=[];if(which==='foreign-bridge')h.authority.tenantId=id(33);await expect(readOperationalDelegation(h.db,actor)).rejects.toMatchObject({code:'DELEGATION_AUTHORITY_REQUIRED'});expect(h.tx.$executeRaw).not.toHaveBeenCalled()});
test('ceiling exposes only fixed revisions and no secret/registry',async()=>{const h=harness();h.authority.tokenHash='hidden';const r=await readOperationalDelegation(h.db,actor);expect(r.profiles.map(p=>p.revision)).toHaveLength(3);expect(JSON.stringify(r)).not.toMatch(/tokenHash|hidden|operator|keyFingerprint/);expect(h.tx.$executeRaw).not.toHaveBeenCalled()});
test('warehouse query binds tenant and explicit ceiling and caps work',async()=>{const h=harness();await listOperationalWarehouses(h.db,actor,{limit:2});expect(h.tx.warehouse.findMany).toHaveBeenCalledWith(expect.objectContaining({where:{tenantId:id(2),id:{in:[id(8)]}},take:3}));await expect(listOperationalWarehouses(h.db,actor,{limit:51})).rejects.toBeTruthy();await expect(listOperationalWarehouses(h.db,actor,{tenantId:id(33)})).rejects.toBeTruthy()});
test('invitation projection excludes secrets and derives expiry without writes',async()=>{const h=harness();h.tx.companyInvitation.findMany.mockResolvedValue([{id:id(10),operationId:id(11),email:'synthetic@example.invalid',profileRevision:'operational-clerk.v1',warehouseIds:[],state:'pending',expiresAt:new Date(0),createdAt:new Date(0),acceptedMembershipId:null,tokenHash:'never-return',fingerprint:'private'}]);const r=await listCompanyInvitations(h.db,actor,{});expect(r.items[0].state).toBe('expired');expect(JSON.stringify(r)).not.toMatch(/tokenHash|fingerprint|never-return/);expect(h.tx.companyInvitation.findMany.mock.calls[0][0].where).toMatchObject({tenantId:id(2),companyId:id(3),inviterMembershipId:id(5)});expect(h.tx.$executeRaw).not.toHaveBeenCalled()});
test('cursor cannot transfer across selected memberships or collections',async()=>{const h=harness();h.tx.warehouse.findMany.mockResolvedValue([{id:id(8),name:'Owned',location:'Synthetic',type:'warehouse'},{id:id(12),name:'Owned',location:'Synthetic',type:'warehouse'}]);const r=await listOperationalWarehouses(h.db,actor,{limit:1});await expect(listOperationalWarehouses(h.db,{...actor,membershipId:id(55),companyMembershipId:id(55)},{cursor:r.nextCursor})).rejects.toMatchObject({code:'DELEGATION_CURSOR_REJECTED'});await expect(listCompanyInvitations(h.db,actor,{cursor:r.nextCursor})).rejects.toMatchObject({code:'DELEGATION_CURSOR_REJECTED'})});
test('grants with unrelated roles, foreign bridges or out-of-ceiling scopes are excluded',async()=>{const h=harness();const g={membershipId:id(20),userId:id(21),tenantId:id(2),companyId:id(3),tenantMembershipId:id(22),profileRevision:'operational-warehouse.v1',warehouseIds:[id(99)],roleId:id(9),enabled:true,member:{user:{name:'Synthetic target'}}};h.tx.companyOperationalGrant.findMany.mockResolvedValue([g]);const target={...h.m,id:g.membershipId,userId:g.userId,tenantMembershipId:g.tenantMembershipId,tenantMembership:{id:id(22),tenantId:id(2),userId:id(21),status:'active'},scopes:[{scopeType:'warehouse',scopeRefId:id(99)}]};h.tx.companyMembership.findUnique.mockImplementation(async({where}:any)=>where.id===id(5)?h.m:target);expect((await listOperationalGrants(h.db,actor,{})).items).toEqual([]);g.warehouseIds=[id(8)];target.scopes=[{scopeType:'warehouse',scopeRefId:id(8)}];h.tx.warehouse.findMany.mockResolvedValue([{id:id(8)}]);expect((await listOperationalGrants(h.db,actor,{})).items[0]).toMatchObject({membershipId:id(20),managed:true});target.roles=[{...h.m.roles[0],roleId:id(88)}];expect((await listOperationalGrants(h.db,actor,{})).items).toEqual([]);expect(h.tx.$executeRaw).not.toHaveBeenCalled()});
