jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/modules/orders-core/domain/order-access",()=>({requireAuthorizedOrder:jest.fn()}));
jest.mock("../../src/modules/analytics-core/infrastructure/analyticsOutbox",()=>({enqueueCargoPilotDomainEventsTx:jest.fn(async()=>undefined)}));
import {database as db} from "./fixtures";
import {requireAuthorizedOrder} from "../../src/modules/orders-core/domain/order-access";
import {enqueueCargoPilotDomainEventsTx} from "../../src/modules/analytics-core/infrastructure/analyticsOutbox";
import {seedInitialServiceChargePricing as seed,createPricingComponent as manual,resolvePayableTotalFromPricing as payable,listPricingComponents as list} from "../../src/modules/orders-legs/pricing";
const actor:any={id:"user",companyId:"ca",tenantId:"ta",membershipId:"ma",companyMembershipId:"ma",tenantMembershipId:"tm"};
const input={serviceCharge:10,currency:"USD",routeTemplateId:"template"};
const leg:any={id:"tl",routeTemplateId:"template",sequence:1,legCode:"synthetic",mode:"road"};
beforeEach(()=>{jest.clearAllMocks();jest.mocked(requireAuthorizedOrder).mockResolvedValue({id:"order",tenantId:"ta",ownerOrgId:"ca"} as any);db.$transaction.mockImplementation(async(work:any)=>work(db));db.$executeRaw.mockResolvedValue(0);db.$queryRaw.mockResolvedValue([{id:"order"}]);db.order.findFirst.mockReset().mockResolvedValue({id:"order"});db.orderLeg.findMany.mockReset().mockResolvedValue([]);db.routeTemplate.findFirst.mockReset().mockResolvedValue({id:"template",companyId:"ca",legs:[leg]});db.orderLeg.create.mockReset().mockResolvedValue({id:"leg",sequence:1,metadata:{}});db.pricingComponent.findFirst.mockReset().mockResolvedValue(null);db.pricingComponent.create.mockReset().mockResolvedValue({id:"component"});});
function noWrites(){expect(db.orderLeg.create).not.toHaveBeenCalled();expect(db.pricingComponent.create).not.toHaveBeenCalled();expect(db.pricingComponent.update).not.toHaveBeenCalled();expect(enqueueCargoPilotDomainEventsTx).not.toHaveBeenCalled();}
it("authorized seed resolves selected-company template before transactional leg/component/event creation",async()=>{
 await expect(seed("order",input,actor)).resolves.toEqual([{id:"component"}]);expect(db.routeTemplate.findFirst.mock.calls[0][0]).toMatchObject({where:{id:"template",companyId:"ca",company:{is:{tenantId:"ta",isActive:true,tenant:{is:{status:"active"}}}}},select:{legs:{take:101}}});
 expect(db.order.findFirst.mock.calls[0][0].where).toMatchObject({tenantId:"ta",ownerOrgId:"ca"});expect(db.$queryRaw.mock.calls[0][0].join("")).toContain("FOR UPDATE");expect(enqueueCargoPilotDomainEventsTx).toHaveBeenCalledTimes(1);
});
it("covered reseed repeats order identity at the actual component update",async()=>{
 db.pricingComponent.findFirst.mockResolvedValueOnce({id:"component"});db.pricingComponent.update.mockReset().mockResolvedValueOnce({id:"component"});
 await expect(seed("order",input,actor)).resolves.toEqual([{id:"component"}]);expect(db.pricingComponent.update.mock.calls[0][0].where).toEqual({id:"component",orderId:"order"});expect(db.pricingComponent.create).not.toHaveBeenCalled();
});
it.each([403,404])("parent denial %s precedes all seed business work",async statusCode=>{jest.mocked(requireAuthorizedOrder).mockRejectedValue(Object.assign(Error("denied"),{statusCode}));await expect(seed("order",input,actor)).rejects.toMatchObject({statusCode});expect(db.$transaction).not.toHaveBeenCalled();noWrites();});
it("selected but non-owning company cannot seed",async()=>{jest.mocked(requireAuthorizedOrder).mockResolvedValue({id:"order",tenantId:"ta",ownerOrgId:"cb"} as any);await expect(seed("order",input,actor)).rejects.toMatchObject({statusCode:403});expect(db.$transaction).not.toHaveBeenCalled();noWrites();});
it("changed or suspended authoritative ownership fails before child reads",async()=>{db.order.findFirst.mockResolvedValue(null);await expect(seed("order",input,actor)).rejects.toMatchObject({statusCode:403});expect(db.orderLeg.findMany).not.toHaveBeenCalled();noWrites();});
it.each([null,{id:"template",companyId:"cb",legs:[leg]},{id:"template",companyId:"ca",legs:[{...leg,routeTemplateId:"foreign"}]},{id:"template",companyId:"ca",legs:Array.from({length:101},()=>leg)}])("foreign/unbound/oversized template cannot create pricing",async template=>{db.routeTemplate.findFirst.mockResolvedValue(template);await expect(seed("order",input,actor)).rejects.toThrow();noWrites();});
it.each([{templateCompanyId:"ca",routeTemplateId:"other",routeTemplate:{companyId:"cb",company:{tenantId:"tb",isActive:true}}},{routeTemplateLegId:"tl",routeTemplateId:null},{templateCompanyId:"ca",routeTemplateLegId:"tl",routeTemplateId:"template",routeTemplate:{companyId:"ca",company:{tenantId:"ta",isActive:true}},routeTemplateLeg:{routeTemplateId:"other"}}])("existing mismatched leg cannot be repriced",async refs=>{db.orderLeg.findMany.mockResolvedValue([{id:"leg",sequence:1,...refs}]);await expect(seed("order",input,actor)).rejects.toMatchObject({statusCode:409});noWrites();});
it("manual money/source and legacy payable remain unavailable before data or effects",async()=>{await expect(manual("order",{amount:999,source:"rule",fxRateSnapshot:1} as any,actor)).rejects.toMatchObject({statusCode:409,code:"ORDER_PRICING_ACCEPTANCE_REQUIRED"});await expect(payable("order",actor)).rejects.toMatchObject({statusCode:409});expect(db.$transaction).not.toHaveBeenCalled();noWrites();});
it("component list preserves decimal strings and excludes foreign children under parent tenant",async()=>{db.pricingComponent.findMany.mockReset().mockResolvedValue([{id:"component",amount:{toString:()=>"999999999999.99"},fxRateSnapshot:{toString:()=>"1.000001"},baseAmount:null}]);const result=await list("order",actor);expect(result[0]).toMatchObject({amount:"999999999999.99",fxRateSnapshot:"1.000001",baseAmount:null});expect(db.pricingComponent.findMany.mock.calls[0][0]).toMatchObject({take:101,where:{orderId:"order",order:{is:{tenantId:"ta"}},OR:[{orderLegId:null},{orderLeg:{is:{orderId:"order"}}}]}});noWrites();});
it("component capacity returns no truncated financial read",async()=>{db.pricingComponent.findMany.mockReset().mockResolvedValue(Array.from({length:101},()=>({amount:10})));await expect(list("order",actor)).rejects.toMatchObject({statusCode:409,code:"ORDER_PRICING_READ_CAPACITY"});noWrites();});

it("new template bridge derives only from selected owning company",async()=>{await seed("order",{...input,templateCompanyId:"FORGED"} as any,actor);expect(db.orderLeg.create.mock.calls[0][0].data).toMatchObject({templateCompanyId:"ca",routeTemplateId:"template",routeTemplateLegId:"tl"});});
it.each([null,"cb"])("existing unbound or foreign template bridge prevents all seed effects",async templateCompanyId=>{db.orderLeg.findMany.mockResolvedValue([{id:"leg",sequence:1,templateCompanyId,routeTemplateId:"template",routeTemplate:{companyId:"ca",company:{tenantId:"ta",isActive:true}},routeTemplateLegId:"tl",routeTemplateLeg:{routeTemplateId:"template"}}]);await expect(seed("order",input,actor)).rejects.toMatchObject({statusCode:409});noWrites();});
