import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import Stripe from "stripe";
import { randomUUID } from "crypto";
import { createTenantDemoFixture } from "../../src/modules/tenancy/demo-fixtures";
import { persistTenantDemoFixture } from "../tenancy/postgres-fixture.persistence";
import { acceptPaymentWebhook } from "../../src/modules/payments-core/application/payment-webhook";
import { invoicePaymentAuthorityDigest } from "../../src/modules/payments-core/application/payment-creation";
import { StripeProviderAdapter } from "../../src/modules/payments-core/infrastructure/providers/stripeAdapter";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,run=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!run||!/^[a-f0-9]{12}$/.test(run))throw Error("Disposable run required");
const target=new URL(url);if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${run}`)throw Error("Refusing existing database");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});
const db=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:4,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});
const fixture=createTenantDemoFixture(),sdk=new Stripe("sk_test_synthetic_not_real"),adapter=new StripeProviderAdapter();
beforeAll(async()=>{const marker=(await pool.query('SELECT "runId" FROM "_CPDisposableRun"')).rows;if(marker.length!==1||marker[0].runId!==run)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{await client.query("ROLLBACK");client.release();}for(const company of fixture.financeLegalEntities)await db.paymentProviderConfig.create({data:{companyId:company.companyId,provider:"STRIPE",environment:"TEST",serviceId:"whsec_synthetic",secretEncrypted:"synthetic",secretMasked:"synthetic",callbackPath:"/synthetic"}});});
afterAll(async()=>{await db.$disconnect();await pool.end();});
async function accepted(company=fixture.financeLegalEntities[0]){
  const order=await db.order.create({data:{tenantId:company.tenantId,ownerOrgId:company.companyId,orderNumber:randomUUID(),customerId:fixture.users[0].id,pickupAddress:"Synthetic",dropoffAddress:"Synthetic",paymentType:"CARD",paymentState:"PENDING",serviceCharge:0}});
  const invoice=await db.invoice.create({data:{tenantId:company.tenantId,companyId:company.companyId,orderId:order.id,customerId:order.customerId,invoiceNumber:randomUUID(),amount:"1200.25",currency:"USD",status:"issued",issuedAt:new Date("2026-01-01"),issuedByUserId:fixture.users[0].id}});
  const config=await db.paymentProviderConfig.findFirstOrThrow({where:{companyId:company.companyId}});
  const intent=await db.paymentIntent.create({data:{companyId:company.companyId,orderId:order.id,providerConfigId:config.id,provider:"STRIPE",environment:"TEST",amountMinor:120025n,currency:"USD",idempotencyKey:randomUUID(),status:"REQUIRES_ACTION",providerInvoiceId:"cs_"+randomUUID().replace(/-/g,""),metadataJson:{invoiceId:invoice.id,legalEntityId:company.id,phase0bAuthorityDigest:invoicePaymentAuthorityDigest({companyId:company.companyId,orderId:order.id,invoiceId:invoice.id,legalEntityId:company.id,amountMinor:120025n,currency:"USD",issuedAt:invoice.issuedAt!})}}});
  const event:any={id:"evt_"+randomUUID().replace(/-/g,""),object:"event",type:"checkout.session.completed",livemode:false,data:{object:{id:intent.providerInvoiceId,object:"checkout.session",status:"complete",payment_status:"paid",payment_intent:"pi_"+randomUUID().replace(/-/g,""),amount_total:120025,currency:"usd",metadata:{paymentIntentId:intent.id,companyId:company.companyId,orderId:order.id}}}};
  return {company,order,invoice,intent,config,event};
}
function request(event:any){const rawBody=Buffer.from(JSON.stringify(event));return{provider:"STRIPE"as const,body:{companyId:"forged-unused"},rawBody,headers:{"stripe-signature":sdk.webhooks.generateTestHeaderString({payload:rawBody.toString(),secret:"whsec_synthetic"})}};}
const deps=(database:any=db)=>({db:database,adapter:()=>adapter,resolve:(config:any)=>({...config,secretPlain:"sk_test_synthetic_not_real"})});
async function snapshot(){return{orders:await db.order.findMany({orderBy:{id:"asc"}}),intents:await db.paymentIntent.findMany({orderBy:{id:"asc"}}),receipts:await db.paymentWebhookEvent.findMany({orderBy:{id:"asc"}}),attempts:await db.paymentAttempt.findMany({orderBy:{id:"asc"}}),ledger:await db.paymentLedgerEntry.findMany({orderBy:{id:"asc"}}),cash:await db.cashCollection.findMany({orderBy:{id:"asc"}}),cashEvents:await db.cashCollectionEvent.count(),audit:await db.financeAuditEvent.count(),outbox:await db.analyticsDomainEventOutbox.count(),financeOutbox:await db.financeDomainEventOutbox.count()};}
it("valid actual offline Stripe signatures confirm each tenant/company separately with exact ledger money",async()=>{for(const company of fixture.financeLegalEntities){const f=await accepted(company);await expect(acceptPaymentWebhook(request(f.event),deps())).resolves.toMatchObject({ok:true,duplicate:false});expect((await db.order.findUniqueOrThrow({where:{id:f.order.id}})).paymentState).toBe("PAID");const ledger=await db.paymentLedgerEntry.findMany({where:{paymentIntentId:f.intent.id}});expect(ledger).toHaveLength(1);expect(ledger[0]).toMatchObject({companyId:company.companyId,orderId:f.order.id,currency:"USD",amountMinor:120025n});}expect(await db.cashCollection.count()).toBe(0);expect(await db.analyticsDomainEventOutbox.count()).toBe(0);expect(await db.financeDomainEventOutbox.count()).toBe(0);});
it("concurrent identical delivery commits one receipt/attempt/ledger and returns one duplicate",async()=>{const f=await accepted(),r=request(f.event);const result=await Promise.all([acceptPaymentWebhook(r,deps()),acceptPaymentWebhook(r,deps())]);expect(result.filter(v=>v.duplicate)).toHaveLength(1);for(const model of [db.paymentWebhookEvent,db.paymentAttempt,db.paymentLedgerEntry])expect(await (model as any).count({where:{paymentIntentId:f.intent.id}})).toBe(1);expect((await db.paymentIntent.findUniqueOrThrow({where:{id:f.intent.id}})).status).toBe("SUCCEEDED");});
it("concurrent conflicting reuse across two bookings rolls the loser back",async()=>{const a=await accepted(),b=await accepted();b.event.id=a.event.id;const results=await Promise.allSettled([acceptPaymentWebhook(request(a.event),deps()),acceptPaymentWebhook(request(b.event),deps())]);expect(results.filter(r=>r.status==="fulfilled")).toHaveLength(1);expect((results.find(r=>r.status==="rejected")as PromiseRejectedResult).reason).toMatchObject({statusCode:409,code:"PAYMENT_EVENT_ID_CONFLICT"});const intents=[a.intent.id,b.intent.id];expect(await db.paymentWebhookEvent.count({where:{paymentIntentId:{in:intents}}})).toBe(1);expect(await db.paymentLedgerEntry.count({where:{paymentIntentId:{in:intents}}})).toBe(1);expect(await db.paymentAttempt.count({where:{paymentIntentId:{in:intents}}})).toBe(1);expect(await db.order.count({where:{id:{in:[a.order.id,b.order.id]},paymentState:"PAID"}})).toBe(1);});
it("different verified events for the same payment do not duplicate financial effects",async()=>{const f=await accepted();await acceptPaymentWebhook(request(f.event),deps());f.event.id="evt_"+randomUUID().replace(/-/g,"");await acceptPaymentWebhook(request(f.event),deps());expect(await db.paymentWebhookEvent.count({where:{paymentIntentId:f.intent.id}})).toBe(2);expect(await db.paymentAttempt.count({where:{paymentIntentId:f.intent.id}})).toBe(1);expect(await db.paymentLedgerEntry.count({where:{paymentIntentId:f.intent.id}})).toBe(1);});
it("forged authentication, money, currency and foreign metadata reject without any durable/business effects",async()=>{const f=await accepted();const before=await snapshot();await expect(acceptPaymentWebhook({...request(f.event),headers:{"stripe-signature":"invalid"}},deps())).rejects.toMatchObject({statusCode:403});for(const change of [{amount_total:1},{currency:"uzs"},{payment_status:"unpaid"},{metadata:{companyId:fixture.financeLegalEntities[1].companyId}},{metadata:{orderId:fixture.orders[2].id}},{metadata:{paymentIntentId:randomUUID()}}]){const event={...f.event,data:{object:{...f.event.data.object,...change}}};await expect(acceptPaymentWebhook(request(event),deps())).rejects.toMatchObject({statusCode:409});expect(await snapshot()).toEqual(before);}expect(await snapshot()).toEqual(before);});
it("conflicting duplicate event cannot overwrite confirmation or change business state",async()=>{const f=await accepted();await acceptPaymentWebhook(request(f.event),deps());const before=await snapshot();const event={...f.event,data:{object:{...f.event.data.object,payment_intent:"pi_conflict"}}};await expect(acceptPaymentWebhook(request(event),deps())).rejects.toMatchObject({statusCode:409});expect(await snapshot()).toEqual(before);});
it("current suspended tenant or owner denies a matching retry without mutations",async()=>{const f=await accepted();await acceptPaymentWebhook(request(f.event),deps());await db.tenant.update({where:{id:f.company.tenantId!},data:{status:"suspended"}});const before=await snapshot();try{await expect(acceptPaymentWebhook(request(f.event),deps())).rejects.toMatchObject({statusCode:409});expect(await snapshot()).toEqual(before);}finally{await db.tenant.update({where:{id:f.company.tenantId!},data:{status:"active"}});}});
it("unsupported cash allocation and failed terminal state remain contained",async()=>{const f=await accepted();for(const data of [{serviceCharge:1},{serviceCharge:null},{serviceCharge:0,paymentState:"FAILED" as const}]){await db.order.update({where:{id:f.order.id},data});const before=await snapshot();await expect(acceptPaymentWebhook(request(f.event),deps())).rejects.toMatchObject({statusCode:409});expect(await snapshot()).toEqual(before);}});
it("injected failure after receipt and financial work rolls back every durable result",async()=>{const f=await accepted(),before=await snapshot();const failing=new Proxy(db,{get(target,property){if(property==="$transaction")return(work:any,options:any)=>target.$transaction(async tx=>{await work(tx);throw Error("synthetic-post-work-failure");},options);const value=(target as any)[property];return typeof value==="function"?value.bind(target):value;}});await expect(acceptPaymentWebhook(request(f.event),deps(failing))).rejects.toThrow("synthetic-post-work-failure");expect(await snapshot()).toEqual(before);await expect(acceptPaymentWebhook(request(f.event),deps())).resolves.toMatchObject({ok:true});});
