jest.mock("../../src/config/prismaClient",()=>({__esModule:true,default:require("./fixtures").database}));
jest.mock("../../src/modules/orders-core/domain/company-authority",()=>({requireTenantBoundOrderCompanyAuthority:jest.fn(),hasCompanyScope:jest.fn(()=>true)}));
import {database as db} from "./fixtures";
import {requireTenantBoundOrderCompanyAuthority,hasCompanyScope} from "../../src/modules/orders-core/domain/company-authority";
import {publishIntegrationProviderConfigurationForActor as publish} from "../../src/modules/integrations-core/application/provider-configuration-publication";
const providerId="019b3000-0000-7000-8b00-000000000001",operationId="019b3000-0000-7000-8b00-000000000002",secretId="019b3000-0000-7000-8b00-000000000003";
const user:any={id:"user",tenantId:"tenant",companyId:"company",membershipId:"cm",companyMembershipId:"cm",tenantMembershipId:"tm"};
let provider:any,version:any;
beforeEach(()=>{jest.clearAllMocks();jest.mocked(requireTenantBoundOrderCompanyAuthority).mockResolvedValue({companyId:"company",tenantId:"tenant",tenantMembershipId:"tm"} as any);jest.mocked(hasCompanyScope).mockReturnValue(true);provider={id:providerId,companyId:"company",domain:"carrier",providerCode:"sandbox",environment:"sandbox",status:"active",timeoutMs:10000,rateLimitRps:null,capabilities:[],retryPolicyId:null,configurationRevision:0,currentConfigurationId:null,secretRef:null,activeSecretId:null};version={id:"receipt",providerId,operationId,revision:1,acceptedAt:new Date()};db.$transaction.mockImplementation(async(work:any)=>work(db));db.$executeRaw.mockResolvedValue(0);db.$queryRaw.mockResolvedValue([{locked:1}]);db.integrationProvider.findFirst.mockReset().mockImplementation(async()=>provider);db.integrationProviderConfigurationVersion.findUnique.mockReset().mockResolvedValue(null);db.integrationProviderConfigurationVersion.create.mockReset().mockImplementation(async({data}:any)=>({...version,...data}));db.integrationProvider.updateMany.mockReset().mockResolvedValue({count:1});db.integrationProviderSecret.findFirst.mockReset().mockResolvedValue({id:secretId});});
function noWrites(){expect(db.integrationProviderConfigurationVersion.create).not.toHaveBeenCalled();expect(db.integrationProvider.updateMany).not.toHaveBeenCalled();expect(db.integrationOutbox.create).not.toHaveBeenCalled();expect(db.integrationProviderSecret.create).not.toHaveBeenCalled();}
it("publishes server snapshot and owned secret atomically with minimal receipt",async()=>{const result=await publish({user,providerId,operationId,expectedRevision:0,secretId});expect(Object.keys(result).sort()).toEqual(["acceptedAt","id","operationId","providerId","revision"]);expect(jest.mocked(requireTenantBoundOrderCompanyAuthority).mock.calls.map(c=>c[2])).toContain("integration.provider.rotateSecret");expect(db.integrationProviderSecret.findFirst).toHaveBeenCalledWith({where:{id:secretId,providerId},select:{id:true}});expect(db.integrationProvider.updateMany.mock.calls[0][0]).toMatchObject({where:{id:providerId,companyId:"company",configurationRevision:0,currentConfigurationId:null},data:{activeSecretId:secretId,secretRef:secretId,configurationRevision:1,currentConfigurationId:"receipt"}});expect(db.integrationProviderConfigurationVersion.create.mock.calls[0][0].data).toMatchObject({actorUserId:"user",companyMembershipId:"cm",tenantMembershipId:"tm",tenantId:"tenant",companyId:"company"});});
it.each(["permission","scope","foreign","financial","stale","legacy","foreign-secret"])("rejects %s before business writes",async kind=>{if(kind==="permission")jest.mocked(requireTenantBoundOrderCompanyAuthority).mockRejectedValue(Object.assign(Error("denied"),{statusCode:403}));if(kind==="scope")jest.mocked(hasCompanyScope).mockReturnValue(false);if(kind==="foreign")db.integrationProvider.findFirst.mockResolvedValue(null);if(kind==="financial")provider.domain="payment";if(kind==="stale")provider.configurationRevision=1;if(kind==="legacy")provider.secretRef=secretId;if(kind==="foreign-secret")db.integrationProviderSecret.findFirst.mockResolvedValue(null);await expect(publish({user,providerId,operationId,expectedRevision:0,...(kind==="foreign-secret"?{secretId}:{})})).rejects.toThrow();noWrites();});
it("request ownership fields are not authority",async()=>{await expect(publish({user,providerId,operationId,expectedRevision:0,tenantId:"foreign"} as any)).rejects.toMatchObject({statusCode:400});expect(db.$transaction).not.toHaveBeenCalled();noWrites();});
it("conditional publication loss rejects instead of acknowledging receipt",async()=>{db.integrationProvider.updateMany.mockResolvedValue({count:0});await expect(publish({user,providerId,operationId,expectedRevision:0})).rejects.toMatchObject({statusCode:409});});
