import { revokeRecordedSuccessors, MAX_REFRESH_ROTATION_DEPTH } from "../../src/modules/identity-access/application/refresh-lineage";
const id = (n: number) => `00000000-0000-4000-8000-${String(n).padStart(12, "0")}`;
const claims: any = { id: id(1), tenantId: id(2), tenantMembershipId: id(3), companyMembershipId: id(4), companyId: id(5), sid: id(100), tokenType: "refresh" };
const node = (depth = 0, patch = {}) => ({ id: id(100 + depth), userId: claims.id, tenantId: claims.tenantId, tenantMembershipId: claims.tenantMembershipId, companyMembershipId: claims.companyMembershipId,
  rotationDepth: depth, replacementDepth: null as number | null, replacedBySessionId: null as string | null, revokedAt: null as Date | null, companyMembership:{companyId:claims.companyId}, ...patch });
let tx: any, nodes: Map<string, any>;
beforeEach(() => { nodes = new Map([[claims.sid, node()]]); tx = { credentialSecurityEvent:{create:jest.fn(async()=>({}))}, $executeRaw: jest.fn(), $queryRaw: jest.fn(async (sql: any) => sql.text.includes("pg_advisory") ? [] : nodes.has(sql.values[0]) ? [nodes.get(sql.values[0])] : []), userRefreshSession: { findFirst: jest.fn(async () => node()), updateMany: jest.fn(async () => ({ count: 1 })) } }; });
it("complete locked recorded chain is authorized from exact possession; pointers never rewritten", async () => {
  nodes.set(claims.sid, node(0, { revokedAt: new Date(), replacementDepth: 1, replacedBySessionId: id(101) })); nodes.set(id(101), node(1, { revokedAt: new Date(), replacementDepth: 2, replacedBySessionId: id(102) })); nodes.set(id(102), node(2));
  await revokeRecordedSuccessors(tx, claims, "synthetic-hash"); expect(tx.userRefreshSession.updateMany).toHaveBeenCalledTimes(1); expect(tx.userRefreshSession.updateMany.mock.calls[0][0]).toMatchObject({ where: { id: { in: [id(100), id(101), id(102)] }, tenantId: claims.tenantId, userId: claims.id, companyMembershipId: claims.companyMembershipId, revokedAt: null }, data: { revokedAt: expect.any(Date) } });
  expect(tx.userRefreshSession.findFirst.mock.calls[0][0].where).toHaveProperty("tokenHash", "synthetic-hash");
  for (const [sql] of tx.$queryRaw.mock.calls.slice(1)) { expect(sql.text).toContain("FOR UPDATE OF s"); expect(sql.values).toContain(claims.tenantId); expect(sql.values).toContain(claims.companyId); expect(sql.text).not.toContain("synthetic-hash"); }
  expect(tx.$executeRaw.mock.calls.map(([sql]: any) => sql.join())).toEqual(["SET LOCAL lock_timeout = '2s'", "SET LOCAL statement_timeout = '5s'"]);
});
it("missing/mismatched original receipt cannot obtain lineage lock or mutate", async () => { tx.userRefreshSession.findFirst.mockResolvedValueOnce(null); await revokeRecordedSuccessors(tx, claims, "hash"); expect(tx.$queryRaw).not.toHaveBeenCalled(); tx.userRefreshSession.findFirst.mockResolvedValueOnce(node(0, { tenantId: id(7) })); await expect(revokeRecordedSuccessors(tx, claims, "hash")).rejects.toThrow("unavailable"); expect(tx.userRefreshSession.updateMany).not.toHaveBeenCalled(); });
it("root disappearing after lock produces no mutation", async () => { nodes.clear(); await revokeRecordedSuccessors(tx, claims, "hash"); expect(tx.userRefreshSession.updateMany).not.toHaveBeenCalled(); });
it.each([{ tenantId: id(8) }, { userId: id(8) }, { tenantMembershipId: id(8) }, { companyMembershipId: id(8) }, { rotationDepth: 2 }])("foreign/conflicting successor %j denies entire mutation", async patch => { nodes.set(claims.sid, node(0, { revokedAt: new Date(), replacementDepth: 1, replacedBySessionId: id(101) })); nodes.set(id(101), node(1, patch)); await expect(revokeRecordedSuccessors(tx, claims, "hash")).rejects.toThrow("unavailable"); expect(tx.userRefreshSession.updateMany).not.toHaveBeenCalled(); });
it.each([{ replacementDepth: 1 }, { rotationDepth: -1 }, { rotationDepth: 257 }, { rotationDepth: 0.5 }, { replacedBySessionId: id(101), replacementDepth: null, revokedAt: new Date() }, { replacedBySessionId: id(101), replacementDepth: 1 }, { replacedBySessionId: claims.sid, replacementDepth: 1, revokedAt: new Date() }])("malformed/cyclic/unaccepted node %j never partially revokes", async patch => { nodes.set(claims.sid, node(0, patch)); await expect(revokeRecordedSuccessors(tx, claims, "hash")).rejects.toThrow("unavailable"); expect(tx.userRefreshSession.updateMany).not.toHaveBeenCalled(); });
it("missing referenced successor leaves even original untouched", async () => { nodes.set(claims.sid, node(0, { revokedAt: new Date(), replacementDepth: 1, replacedBySessionId: id(101) })); await expect(revokeRecordedSuccessors(tx, claims, "hash")).rejects.toThrow("unavailable"); expect(tx.userRefreshSession.updateMany).not.toHaveBeenCalled(); });
it("resource maximum permits exactly257nodes and denies an additional successor", async () => {
  for (let depth = 0; depth <= MAX_REFRESH_ROTATION_DEPTH; depth++) nodes.set(id(100 + depth), node(depth, depth < MAX_REFRESH_ROTATION_DEPTH ? { revokedAt: new Date(), replacementDepth: depth + 1, replacedBySessionId: id(101 + depth) } : {}));
  await revokeRecordedSuccessors(tx, claims, "hash"); expect(tx.userRefreshSession.updateMany.mock.calls[0][0].where.id.in).toHaveLength(257);
  tx.userRefreshSession.updateMany.mockClear(); nodes.set(id(356), node(256, { revokedAt: new Date(), replacementDepth: 257, replacedBySessionId: id(357) }));
  await expect(revokeRecordedSuccessors(tx, claims, "hash")).rejects.toThrow("unavailable"); expect(tx.userRefreshSession.updateMany).not.toHaveBeenCalled();
});
it("lock or final-write failure propagates, never acknowledges partial success", async () => { tx.$executeRaw.mockRejectedValueOnce(new Error("Synthetic lock deadline")); await expect(revokeRecordedSuccessors(tx, claims, "hash")).rejects.toThrow("deadline"); expect(tx.userRefreshSession.updateMany).not.toHaveBeenCalled(); tx.userRefreshSession.updateMany.mockRejectedValueOnce(new Error("Synthetic final failure")); await expect(revokeRecordedSuccessors(tx, claims, "hash")).rejects.toThrow("final failure"); });
