jest.mock("../../src/config/prismaClient", () => ({ __esModule: true, default: new Proxy({}, { get: (_target, name) => { const value = (mockPrisma as any)[name]; return typeof value === "function" ? value.bind(mockPrisma) : value; } }) }));
// Domain envelope only is mocked to guarantee no Redis/logger import; actual transactional outbox writes run.
jest.mock("../../src/modules/analytics-core/realtime/analyticsEvents", () => ({ buildCargoPilotDomainEvent: (input: any) => ({ ...input, id: require("crypto").randomUUID(), occurredAt: new Date().toISOString(), schemaVersion: 1 }) }));
import { Pool } from "pg";
import { PrismaClient } from "@prisma/client";
import { PrismaPg } from "@prisma/adapter-pg";
import { randomUUID } from "crypto";
import { createTenantDemoFixture, TENANT_DEMO_IDS as ids } from "../../src/modules/tenancy/demo-fixtures";
import { persistTenantDemoFixture } from "../tenancy/postgres-fixture.persistence";
jest.mock("../../src/config/redis",()=>({getRedisClient:jest.fn(async()=>null),getRedisPrefix:()=>"disposable-refresh",withRedisTimeout:async(_name:string,work:()=>Promise<unknown>)=>work()}));
import jwt from "jsonwebtoken";
import { createHash } from "crypto";
import { refreshUserSession } from "../../src/modules/identity-access/application/auth.service";
const url=process.env.CARGOPILOT_WORKER_TEST_DATABASE_URL,runId=process.env.CARGOPILOT_WORKER_RUN_ID;
if(!url||!runId||!/^[a-f0-9]{12}$/.test(runId))throw Error("Disposable refresh identity required");
const target=new URL(url);
if(target.hostname!=="127.0.0.1"||target.username!=="cp_worker_it"||target.pathname!==`/cp_worker_${runId}`)throw Error("Refusing existing PostgreSQL target");
const pool=new Pool({connectionString:url,max:2,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"});
let mockPrisma:PrismaClient;
const fixture=createTenantDemoFixture();
const context={id:ids.users.maker,tenantId:ids.tenants.transAsia,tenantMembershipId:ids.tenantMemberships.makerTransAsia,companyId:ids.organizations.transAsiaUz,companyMembershipId:ids.companyMemberships.makerTransAsiaUz};
const secret="synthetic-disposable-refresh-only-signing";
async function accepted(){const sid=randomUUID();const token=jwt.sign({...context,sid,tokenType:"refresh"},secret,{expiresIn:"1h"});await mockPrisma.userRefreshSession.create({data:{id:sid,userId:context.id,tenantId:context.tenantId,tenantMembershipId:context.tenantMembershipId,companyMembershipId:context.companyMembershipId,tokenHash:createHash("sha256").update(token).digest("hex"),expiresAt:new Date(Date.now()+3600000)}});return {sid,token};}
const rows=()=>mockPrisma.userRefreshSession.findMany({where:{userId:context.id},orderBy:{id:"asc"}});
beforeAll(async()=>{const marker=await pool.query('SELECT "runId" FROM "_CPDisposableRun"');if(marker.rows.length!==1||marker.rows[0].runId!==runId)throw Error("Disposable ownership mismatch");const client=await pool.connect();try{await client.query("BEGIN");await persistTenantDemoFixture(client,fixture);await client.query("COMMIT");}finally{client.release();}mockPrisma=new PrismaClient({adapter:new PrismaPg({connectionString:url,max:6,connectionTimeoutMillis:3000,options:"-c statement_timeout=5000"})});process.env.JWT_SECRET=secret;process.env.REFRESH_TOKEN_SECRET=secret;});
afterAll(async()=>{await mockPrisma?.$disconnect();await pool.end();delete process.env.JWT_SECRET;delete process.env.REFRESH_TOKEN_SECRET;});
it("three simultaneous actual refresh requests consume one token and create one exact-context replacement",async()=>{const original=await accepted();const before=await rows();const originalTransaction=mockPrisma.$transaction.bind(mockPrisma);let arrivals=0;let release!:()=>void;let fail!:(e:Error)=>void;const gate=new Promise<void>((resolve,reject)=>{release=resolve;fail=reject;});const deadline=setTimeout(()=>fail(Error("synthetic refresh barrier deadline")),5000);const spy=jest.spyOn(mockPrisma,"$transaction").mockImplementation(async(fn:any,opts:any)=>{arrivals++;if(arrivals===3)release();await gate;return originalTransaction(fn,opts);});let outcomes:PromiseSettledResult<any>[];try{outcomes=await Promise.allSettled([1,2,3].map(()=>refreshUserSession({refreshToken:original.token})));expect(arrivals).toBe(3);}finally{clearTimeout(deadline);spy.mockRestore();}const success=outcomes.filter((r):r is PromiseFulfilledResult<any>=>r.status==="fulfilled");expect(success).toHaveLength(1);expect(outcomes.filter(r=>r.status==="rejected")).toHaveLength(2);const after=await rows();expect(after.length-before.length).toBe(1);expect(after.find(r=>r.id===original.sid)!.revokedAt).not.toBeNull();const payload=jwt.verify(success[0].value.refreshToken,secret) as any;expect(payload).toMatchObject(context);const replacement=after.find(r=>r.id===payload.sid)!;expect(replacement).toMatchObject({userId:context.id,tenantId:context.tenantId,tenantMembershipId:context.tenantMembershipId,companyMembershipId:context.companyMembershipId,revokedAt:null});await expect(refreshUserSession({refreshToken:original.token})).rejects.toThrow("revoked");expect(await rows()).toEqual(after);});
it("actual replacement INSERT failure rolls back consumption and permits the original token to retry",async()=>{const original=await accepted();const before=await rows();await pool.query(`CREATE FUNCTION cp_refresh_fail() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW."userAgent"='synthetic-insert-failure' THEN RAISE EXCEPTION 'synthetic refresh insert failure'; END IF; RETURN NEW; END $$; CREATE TRIGGER cp_refresh_fail BEFORE INSERT ON "UserRefreshSession" FOR EACH ROW EXECUTE FUNCTION cp_refresh_fail();`);try{await expect(refreshUserSession({refreshToken:original.token,userAgent:"synthetic-insert-failure"})).rejects.toThrow("synthetic refresh insert failure");expect(await rows()).toEqual(before);}finally{await pool.query('DROP TRIGGER cp_refresh_fail ON "UserRefreshSession"; DROP FUNCTION cp_refresh_fail();');}expect(await refreshUserSession({refreshToken:original.token})).toHaveProperty("refreshToken");expect((await rows()).length-before.length).toBe(1);});
it("revoked membership denies actual refresh without creating or consuming sessions",async()=>{const original=await accepted();const before=await rows();await mockPrisma.companyMembership.update({where:{id:context.companyMembershipId},data:{status:"suspended"}});try{await expect(refreshUserSession({refreshToken:original.token})).rejects.toThrow("no longer eligible");expect(await rows()).toEqual(before);}finally{await mockPrisma.companyMembership.update({where:{id:context.companyMembershipId},data:{status:"active"}});}});
