jest.mock('../../src/config/prismaClient',()=>({__esModule:true,default:{}}));
jest.mock('../../src/config/redis',()=>({getRedisClient:async()=>null,getRedisPrefix:()=> 'test',withRedisTimeout:(_n:any,w:any)=>w()}));
jest.mock('../../src/modules/identity-access/access-control',()=>({clearIdentityAccessCacheForUser:jest.fn()}));
jest.mock('../../src/modules/warehouse-core/application/warehouseAccess',()=>({requireWarehouseAccess:jest.fn(async()=>({})),warehouseAccessError:(message:string,statusCode=403)=>Object.assign(new Error(message),{statusCode})}));
import {readWarehouseProvisioningAuthority} from '../../src/modules/warehouse-core/application/warehouseProvisioning';
const id=(n:number)=>`00000000-0000-4000-8000-${String(n).padStart(12,'0')}`;
const actor:any={id:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),companyMembershipId:id(5),membershipId:id(5)};
function harness(){const a:any={userId:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),profileRevision:'warehouse-provisioning.v1',enabled:true,acceptedAction:'operator-authorize',acceptedResult:{companyMembershipId:id(5),enabled:true},secret:'hidden'};
 const m:any={id:id(5),userId:id(1),tenantId:id(2),companyId:id(3),tenantMembershipId:id(4),status:'active',user:{id:id(1)},company:{id:id(3),tenantId:id(2),type:'company',isActive:true},tenant:{status:'active'},tenantMembership:{id:id(4),tenantId:id(2),userId:id(1),status:'active'},roles:[{role:{companyId:id(3),isSystem:false,rolePermissions:[{permission:{key:'warehouse.create'}}]}}],scopes:[{scopeType:'company',scopeRefId:id(3)}]};
 const tx:any={$queryRaw:jest.fn(async()=>[a]),$executeRaw:jest.fn(()=>{throw Error('Read wrote state')}),companyMembership:{findUnique:jest.fn(async()=>m)}};return{a,m,tx,db:{$transaction:jest.fn((f:any)=>f(tx))} as any};}
test('warehouse authority context mandatory before database work',async()=>{const h=harness();await expect(readWarehouseProvisioningAuthority(h.db,{} as any)).rejects.toBeTruthy();expect(h.db.$transaction).not.toHaveBeenCalled()});
test('accepted metadata is minimal and never writes or locks',async()=>{const h=harness();expect(await readWarehouseProvisioningAuthority(h.db,actor)).toEqual({profileRevision:'warehouse-provisioning.v1',companyMembershipId:id(5),companyId:id(3),tenantId:id(2),accepted:true});expect(h.tx.$executeRaw).not.toHaveBeenCalled();expect(h.tx.$queryRaw.mock.calls[0][0].join('')).not.toMatch(/FOR (SHARE|UPDATE)/);});
test.each(['revoked','foreign','missing-acceptance','permission-only','scope','suspended'])('authority read denies %s',async kind=>{const h=harness();if(kind==='revoked')h.a.enabled=false;if(kind==='foreign')h.a.companyId=id(9);if(kind==='missing-acceptance')h.a.acceptedAction='operator-revoke';if(kind==='permission-only')h.tx.$queryRaw.mockResolvedValue([]);if(kind==='scope')h.m.scopes=[];if(kind==='suspended')h.m.status='suspended';await expect(readWarehouseProvisioningAuthority(h.db,actor)).rejects.toBeTruthy();expect(h.tx.$executeRaw).not.toHaveBeenCalled()});
