-- Additive source ownership. No historical ownership inference or edits.
ALTER TABLE "FinanceProviderSettlementLine" ADD COLUMN "legalEntityId" UUID, ADD COLUMN "tenantId" UUID, ADD COLUMN "companyId" UUID, ADD COLUMN "providerConfigId" UUID, ADD COLUMN "currency" VARCHAR(3);
CREATE UNIQUE INDEX "FinanceSettlement_line_owner_key" ON "FinanceProviderSettlement" ("id", "legalEntityId", "companyId", "providerConfigId", "currency");
CREATE UNIQUE INDEX "PaymentIntent_settlement_owner_key" ON "PaymentIntent" ("id", "companyId", "orderId", "providerConfigId", "currency");
CREATE UNIQUE INDEX "PaymentRefund_settlement_owner_key" ON "PaymentRefund" ("id", "companyId", "orderId", "paymentIntentId", "currency");
CREATE INDEX "FinanceSettlementLine_tenant_company_header_idx" ON "FinanceProviderSettlementLine" ("tenantId", "companyId", "settlementId");
ALTER TABLE "FinanceProviderSettlementLine" ADD CONSTRAINT "FinanceSettlementLine_header_owner_fkey" FOREIGN KEY ("settlementId", "legalEntityId", "companyId", "providerConfigId", "currency") REFERENCES "FinanceProviderSettlement" ("id", "legalEntityId", "companyId", "providerConfigId", "currency") ON DELETE RESTRICT ON UPDATE RESTRICT NOT VALID;
ALTER TABLE "FinanceProviderSettlementLine" ADD CONSTRAINT "FinanceSettlementLine_entity_owner_fkey" FOREIGN KEY ("legalEntityId", "tenantId", "companyId") REFERENCES "FinanceLegalEntity" ("id", "tenantId", "companyId") ON DELETE RESTRICT ON UPDATE RESTRICT NOT VALID;
ALTER TABLE "FinanceProviderSettlementLine" ADD CONSTRAINT "FinanceSettlementLine_order_owner_fkey" FOREIGN KEY ("tenantId", "orderId", "companyId") REFERENCES "Order" ("tenantId", "id", "ownerOrgId") ON DELETE RESTRICT ON UPDATE RESTRICT NOT VALID;
ALTER TABLE "FinanceProviderSettlementLine" ADD CONSTRAINT "FinanceSettlementLine_intent_owner_fkey" FOREIGN KEY ("paymentIntentId", "companyId", "orderId", "providerConfigId", "currency") REFERENCES "PaymentIntent" ("id", "companyId", "orderId", "providerConfigId", "currency") ON DELETE RESTRICT ON UPDATE RESTRICT NOT VALID;
ALTER TABLE "FinanceProviderSettlementLine" ADD CONSTRAINT "FinanceSettlementLine_refund_owner_fkey" FOREIGN KEY ("paymentRefundId", "companyId", "orderId", "paymentIntentId", "currency") REFERENCES "PaymentRefund" ("id", "companyId", "orderId", "paymentIntentId", "currency") ON DELETE RESTRICT ON UPDATE RESTRICT NOT VALID;
ALTER TABLE "FinanceProviderSettlementLine" ADD CONSTRAINT "FinanceSettlementLine_owner_required_check" CHECK ("legalEntityId" IS NOT NULL AND "tenantId" IS NOT NULL AND "companyId" IS NOT NULL AND "providerConfigId" IS NOT NULL AND "currency" IS NOT NULL) NOT VALID;
ALTER TABLE "FinanceProviderSettlementLine" ADD CONSTRAINT "FinanceSettlementLine_source_bridge_check" CHECK (("paymentIntentId" IS NULL OR "orderId" IS NOT NULL) AND ("paymentRefundId" IS NULL OR ("paymentIntentId" IS NOT NULL AND "orderId" IS NOT NULL))) NOT VALID;
