ALTER TABLE "Invoice" ADD COLUMN "billingPriceApprovalId" UUID, ADD COLUMN "billingPolicyVersionId" UUID, ADD COLUMN "billingPayerCustomerEntityId" UUID, ADD COLUMN "billingLegalEntityId" UUID, ADD COLUMN "billingOrderBillToId" UUID;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_issuance_source_key" UNIQUE (id,"tenantId","companyId","orderId","billingLegalEntityId",currency,amount,"billingPriceApprovalId");
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_accepted_price_fk" FOREIGN KEY ("billingPriceApprovalId","tenantId","companyId","billingLegalEntityId","orderId",currency,amount,"billingOrderBillToId","billingPayerCustomerEntityId","billingPolicyVersionId") REFERENCES "OrderPriceApproval"("snapshotId","tenantId","companyId","legalEntityId","orderId",currency,total,"billToId","payerCustomerEntityId","policyVersionId") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_billing_policy_fk" FOREIGN KEY ("billingPolicyVersionId","tenantId","companyId","billingLegalEntityId",currency) REFERENCES "BillingPolicyVersion"(id,"tenantId","companyId","legalEntityId",currency) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "Invoice" ADD CONSTRAINT "Invoice_billing_complete_check" CHECK (num_nonnulls("billingPriceApprovalId","billingPolicyVersionId","billingPayerCustomerEntityId","billingLegalEntityId","billingOrderBillToId")=0 OR (num_nonnulls("billingPriceApprovalId","billingPolicyVersionId","billingPayerCustomerEntityId","billingLegalEntityId","billingOrderBillToId")=5 AND "tenantId" IS NOT NULL AND "issuedAt" IS NOT NULL AND "issuedByUserId" IS NOT NULL AND amount>0));
-- New owned price authority only; no historical adoption.
CREATE TABLE "InvoiceIssuanceReceipt" ("id" UUID NOT NULL PRIMARY KEY DEFAULT public.uuid_generate_v7(),"tenantId" UUID NOT NULL,"companyId" UUID NOT NULL,"legalEntityId" UUID NOT NULL,"orderId" UUID NOT NULL,"invoiceId" UUID NOT NULL,"priceApprovalId" UUID NOT NULL,"currency" VARCHAR(3) NOT NULL,"total" DECIMAL(20,4) NOT NULL,"actorUserId" UUID NOT NULL,"companyMembershipId" UUID NOT NULL,"tenantMembershipId" UUID NOT NULL,"operationId" UUID NOT NULL,"intentHash" CHAR(64) NOT NULL,"reason" TEXT NOT NULL,"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP);
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_key_0" UNIQUE ("tenantId","operationId");
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_key_1" UNIQUE ("invoiceId");
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_key_2" UNIQUE ("priceApprovalId");
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_key_3" UNIQUE ("id","tenantId","companyId","legalEntityId","orderId","invoiceId");
CREATE INDEX "InvoiceIssuanceReceipt_owner_idx" ON "InvoiceIssuanceReceipt"("tenantId","companyId","orderId");
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_check" CHECK (total>0 AND "intentHash" ~ '^[a-f0-9]{64}$' AND length(btrim(reason)) BETWEEN 1 AND 1000);
CREATE TRIGGER "InvoiceIssuanceReceipt_immutable" BEFORE UPDATE OR DELETE ON "InvoiceIssuanceReceipt" FOR EACH ROW EXECUTE FUNCTION cp_billing_history_immutable();
CREATE TRIGGER "InvoiceIssuanceReceipt_no_truncate" BEFORE TRUNCATE ON "InvoiceIssuanceReceipt" FOR EACH STATEMENT EXECUTE FUNCTION cp_billing_history_immutable();

ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_entity_fk" FOREIGN KEY ("legalEntityId","tenantId","companyId") REFERENCES "FinanceLegalEntity"("id","tenantId","companyId") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_order_fk" FOREIGN KEY ("tenantId","orderId","companyId") REFERENCES "Order"("tenantId","id","ownerOrgId") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_actor_fk" FOREIGN KEY ("companyMembershipId","actorUserId","tenantId","companyId") REFERENCES "CompanyMembership"("id","userId","tenantId","companyId") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_bridge_fk" FOREIGN KEY ("companyMembershipId","tenantMembershipId","actorUserId","tenantId") REFERENCES "CompanyMembership"("id","tenantMembershipId","userId","tenantId") ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE "InvoiceIssuanceReceipt" ADD CONSTRAINT "InvoiceIssuanceReceipt_invoice_fk" FOREIGN KEY ("invoiceId","tenantId","companyId","orderId","legalEntityId","currency","total","priceApprovalId") REFERENCES "Invoice"("id","tenantId","companyId","orderId","billingLegalEntityId","currency","amount","billingPriceApprovalId") ON DELETE RESTRICT ON UPDATE RESTRICT;

CREATE TABLE "BillingInvoiceOutbox" (id UUID PRIMARY KEY DEFAULT public.uuid_generate_v7(), "receiptId" UUID NOT NULL UNIQUE,"tenantId" UUID NOT NULL,"companyId" UUID NOT NULL,"legalEntityId" UUID NOT NULL,"orderId" UUID NOT NULL,"invoiceId" UUID NOT NULL UNIQUE,"eventType" TEXT NOT NULL CHECK ("eventType"='invoice.issued'), state TEXT NOT NULL CHECK(state='held_no_accounting_authority'),"createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,CONSTRAINT "BillingInvoiceOutbox_source_fk" FOREIGN KEY ("receiptId","tenantId","companyId","legalEntityId","orderId","invoiceId") REFERENCES "InvoiceIssuanceReceipt"(id,"tenantId","companyId","legalEntityId","orderId","invoiceId") ON UPDATE RESTRICT ON DELETE RESTRICT);
CREATE INDEX "BillingInvoiceOutbox_owner_idx" ON "BillingInvoiceOutbox"("tenantId","companyId",state,"createdAt");
CREATE TRIGGER "BillingInvoiceOutbox_immutable" BEFORE UPDATE OR DELETE ON "BillingInvoiceOutbox" FOR EACH ROW EXECUTE FUNCTION cp_billing_history_immutable();
CREATE TRIGGER "BillingInvoiceOutbox_no_truncate" BEFORE TRUNCATE ON "BillingInvoiceOutbox" FOR EACH STATEMENT EXECUTE FUNCTION cp_billing_history_immutable();
CREATE FUNCTION cp_invoice_billing_immutable() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF OLD."billingPriceApprovalId" IS NOT NULL AND (TG_OP='DELETE' OR ROW(OLD."tenantId",OLD."companyId",OLD."orderId",OLD.amount,OLD.currency,OLD."fxRate",OLD."fxRateAsOf",OLD."customerId",OLD."customerEntityId",OLD."billingPriceApprovalId",OLD."billingPolicyVersionId",OLD."billingPayerCustomerEntityId",OLD."billingLegalEntityId",OLD."billingOrderBillToId",OLD."invoiceNumber",OLD."issuedAt",OLD."issuedByUserId",OLD."dueAt") IS DISTINCT FROM ROW(NEW."tenantId",NEW."companyId",NEW."orderId",NEW.amount,NEW.currency,NEW."fxRate",NEW."fxRateAsOf",NEW."customerId",NEW."customerEntityId",NEW."billingPriceApprovalId",NEW."billingPolicyVersionId",NEW."billingPayerCustomerEntityId",NEW."billingLegalEntityId",NEW."billingOrderBillToId",NEW."invoiceNumber",NEW."issuedAt",NEW."issuedByUserId",NEW."dueAt")) THEN RAISE EXCEPTION 'Issued billing authority is immutable' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' AND OLD."billingPriceApprovalId" IS NULL AND NEW."billingPriceApprovalId" IS NOT NULL THEN RAISE EXCEPTION 'Historical invoice cannot be adopted' USING ERRCODE='23514'; END IF;
 IF TG_OP='UPDATE' AND OLD."billingPriceApprovalId" IS NOT NULL AND NEW.status IS DISTINCT FROM OLD.status AND NOT (OLD.status='issued' AND NEW.status='paid') THEN RAISE EXCEPTION 'Invoice lifecycle correction is not accepted' USING ERRCODE='23514'; END IF;
 RETURN CASE WHEN TG_OP='DELETE' THEN OLD ELSE NEW END; END $$;
CREATE TRIGGER "Invoice_billing_immutable" BEFORE UPDATE OR DELETE ON "Invoice" FOR EACH ROW EXECUTE FUNCTION cp_invoice_billing_immutable();
